### ISSUE TITLE
Add "clear cache and refresh" info text to web3 wallet dialog

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#1024]
I can't engage my wallet, when I click engage wallet, then browser, liquality is blacked out and I can only click the link to download it, but I already have it

*Source url:* https://live.sovryn.app/
*Reported by:* coryjamesjoncas@gmail.com
*Reported at:* 04 May at 12:46 UTC

*Location:* CA, Nova Scotia, Halifax
*Browser:* Chrome 90.0.4430.93

*OS:* macOS 10.15.7
*Screen:* 1440x900
*Viewport:* 1440x730

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/s37794fbs930t64asshg/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjAxMzIzODcsImRhdGEiOnsicmVwb3J0IjoiczM3Nzk0ZmJzOTMwdDY0YXNzaGciLCJ1c2VyIjoiR2l0SHViIn19.KBsi6jMdCIzivo6Dg6ppEwB_sT7EDrcSdEZmQRwpLpw)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/s37794fbs930t64asshg](https://ybug.io/dashboard/reports/detail/s37794fbs930t64asshg)

**Comment by soulBit** [comment]
Change is to add additional info text where indicated in red on screenshot:

![image](https://user-images.githubusercontent.com/765825/120831380-627b3380-c557-11eb-9877-154342ff6a0e.png)

Text should read something like "If you experience issues connecting, please clear your browser cache and refresh the page before trying again" - please check with Tzu for exact copy to use
