### ISSUE TITLE
Add SOV token to users MM watch list

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#1028]
Metamask now allows dapps to suggest adding new tokens to the wallet asset watchlist:

```
ethereum.request({
  method: 'wallet_watchAsset',
  params: {
    type: 'ERC20',
    options: {
      address: '0xb60e8dd61c5d32be8058bb8eb970870f07233155',
      symbol: 'FOO',
      decimals: 18,
      image: 'https://foo.io/token-image.svg',
    },
  },
});
```

https://docs.metamask.io/guide/rpc-api.html#wallet-watchasset

**Comment by tiltom** [comment]
The same case as with https://github.com/DistributedCollective/Sovryn-frontend/issues/1027 - this will open a Metamask dialog with a request so it should be done only after a user action. What is the proposed flow @t-z-u ?

**Comment by tiltom** [comment]
This can be work on once we have a new Portfolio page design.

**Comment by soulBit** [comment]
Migrated to Taiga in https://taiga.sovryn.app/project/sovryn-light/us/168
