### ISSUE TITLE
Do not allow user to send a transaction if it's estimated to fail

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#1033]
To check if transaction will fail you need two gas limit estimation calls:
a. to estimate how much transaction will cost 
b. do estimation call but add gas limit that was received in the step `a` and add `1` to it in the call config, ({ gas: estimated + 1 })

If result from call `b` is same as `a` + 1 then transaction will fail (used all gas that was sent), if it's same as `a` then it should be confirmed (ofc contract may just revert tx and it wouldn't use all of the provided gas, but we don't need to handle it and I don't think that's possible to handle).

**Comment by tiltom** [comment]
When do you think we would need this functionality @creed-victor , all over the dapp (`Trade` and `Finance` sections)?

Also, we would need some design for it (when and what we should display to users) @t-z-u .

**Comment by creed-victor** [comment]
> Where do you think we would need this functionality @creed-victor , all over the dapp (`Trade` and `Finance` sections)?
> 
> Also, we would need some design for it (when and what we should display to users) @t-z-u .

It should cover all transactions, however I see that story description is wrong and it will always be successful because checks will be coming in same block (no state changes), so identical result for all requests will be returned.

Closing until better solution found.
