### ISSUE TITLE
Add transackt back

### ISSUE THREAD

**Issue by t-z-u** [DistributedCollective/Sovryn-frontend#1044]

**Comment by t-z-u** [comment]
add the transakt modal
please use this logic and do not add with fast btc
<img width="205" alt="Screenshot 2021-05-07 at 16 19 26" src="https://user-images.githubusercontent.com/79344165/117471787-205ad400-af50-11eb-8812-daa3fa154da0.png">

**Comment by bitcoinuser** [comment]
@t-z-u Now that we have Margem trade and Spot Trade. The trade on Portfolio should be renamed, no?

**Comment by t-z-u** [comment]
https://xd.adobe.com/view/8cfbe700-2611-4ca0-5830-6cb565a5e5ab-faca/
