### ISSUE TITLE
Adjust right padding in Margin Trade pair Select

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1052]
Applied tailwind class to override default padding, but the CSS is ordered differently from dev -> prod build

![image](https://user-images.githubusercontent.com/765825/117587465-feab4980-b115-11eb-93f9-fd653952b9b7.png)

Class applied in commit:
https://github.com/DistributedCollective/Sovryn-frontend/commit/1d6bf15b9395c6383f78c51b55331a994fca71d6

**Comment by tiltom** [comment]
I don't get it, could you create a screenshot of what is wrong exactly? I tried it on testnet and it looks fine and we don't have it in the production yet, right?
