### ISSUE TITLE
Update Email Notification dialog styling on Margin Trade page

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1053]
Restyle dialog to match new design

Current:
![image](https://user-images.githubusercontent.com/765825/117587589-a4f74f00-b116-11eb-828f-29046c9ffb78.png)

New:
![image](https://user-images.githubusercontent.com/765825/117587569-842ef980-b116-11eb-8702-121e071618ea.png)

**Comment by t-z-u** [comment]
<img width="646" alt="Screenshot 2021-05-09 at 23 34 17" src="https://user-images.githubusercontent.com/79344165/117589018-1c30e100-b11f-11eb-9052-8003e1d67e80.png">
