### ISSUE TITLE
Left align values in Amount inputs

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1058]
Currently values in Amount inputs are centered, and the position of the value changes depending on length of asset name. These should be updated to left align values like the Review Transaction "approx entry price" on Margin Trade page, or "amount received" field on Spot Trade page. All amount inputs should use same approach (Swap, Spot, Margin Trade pages).

- [x] Left align values
- [x] Truncate values to 8 decimal places

![image](https://user-images.githubusercontent.com/765825/117588638-88f6ac00-b11c-11eb-90ab-425d764ffcaf.png)

**Comment by tiltom** [comment]
Are you sure we want 8 decimals? I worked on swap page adjustments last week and I had 4 decimals in the design there.
