### ISSUE TITLE
Engage Wallet button not translated to PT-BR on SWAP page on test.sovryn.app

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#1068]
Engage Wallet button not translated to PT-BR on SWAP page on test.sovryn.app

OBS. On Margin trade and Spot, the button Engage Wallet is translated.

![Captura de tela de 2021-05-10 10-45-36](https://user-images.githubusercontent.com/1178856/117669203-05b97280-b17d-11eb-86fa-394d7e4a0ef2.png)

**Comment by soulBit** [comment]
Engage wallet button has been removed from this page, but I've included the BUY/SELL text as translation strings now
