### ISSUE TITLE
fix swap logic

### ISSUE THREAD

**Issue by t-z-u** [DistributedCollective/Sovryn-frontend#1072]

**Comment by t-z-u** [comment]
https://user-images.githubusercontent.com/79344165/117718093-93c04800-b1d3-11eb-9f48-4866ec16fe98.mov

if i enter 10 sov and click the arrows, i should end up with 10 sov on the receiving side

**Comment by grinry** [comment]
10 SOV is 0.0002 rBTC, but 0.0002 rBTC is not equal 10 SOV.
So task is impossible to complete with only frontend work.

Solidity team should be asked to implement reverse target from source amount function for the swaps smart-contract first

**Comment by t-z-u** [comment]
@tiltom that would be great thanks!
i will also mention it as a dependancy in lead standup later

**Comment by t-z-u** [comment]
take the destination amount as the new source amount. example:
1. I enter 5000 SOV -> 5 BTC, then press switch
2. New source amount: 5BTC
3. Query the contract to calculate how many SOV I receive for 5 BTC
