### ISSUE TITLE
Create opt out of tracking button

### ISSUE THREAD

**Issue by t-z-u** [DistributedCollective/Sovryn-frontend#1091]
We need to create a button that allows users to opt out of the google analytics

**Comment by t-z-u** [comment]
@creed-victor if you could please explain the tech logic

**Comment by creed-victor** [comment]
We should have a link at the footer for analytics opt-out, clicking it should open dialog with some text why we want to track user, checkbox for opting-out and confirm button.
Checked checkbox would mean that tracking is enabled (default behaviour).
@t-z-u i think we will need some design and copy for that.

- when user opts-out set cookie about it, when opt-in remove it
- we use `react-ga` library for using google analytics, when user opted out - this must be not initialised
- it's possible that react-ga lib is used in other pages, not only in the initialisation - make sure these calls are also silently ignored so app would not crash when opted-out.
- i think dialog should also say, that user needs to refresh page after confirming so settings would actually start working (or you would need to remove all google analytics scripts injected to the dom and unsubscribe it's events - i dont think it's an optimal and safe way)

**Comment by soulBit** [comment]
@t-z-u here is the design/copy that I've used (in line with other dialogs), let me know if you want to make any adjustments:

![image](https://user-images.githubusercontent.com/765825/118376508-36a40800-b5c0-11eb-8734-54dea0f09026.png)

@creed-victor `react-ga` isn't used anywhere else in the dapp, if we add it elsewhere in the future then we should include a check for `window.ga` and opt out cookie

**Comment by t-z-u** [comment]
@soulBit styling looks good
