### ISSUE TITLE
RBTC/SOV Trading Chart is not updating automatically.

### ISSUE THREAD

**Issue by jjmr007** [DistributedCollective/Sovryn-frontend#1094]
**Describe the bug**
You need to refresh the page, but then it loads the default RBTC/DOC chart on trade tab, so the SOV/BTC pair price must be searched again.

**To Reproduce**
live.sovryn.app

**Expected behavior**
An automatic (reactive) update of the candles in the SOV/BTC prices

**Comment by creed-victor** [comment]
@jjmr007 feature was changed a little bit - it should stop auto refreshing after 10 minutes of user inactivity (temporary thing), because it causes milions of requests to our database per day. 
It will be changed back when database will be optimased.

Or auto refresh doesn't work at all right now?

**Comment by soulBit** [comment]
Closing this as new charts have been released
