### ISSUE TITLE
Add responsive styles to the diagram on Spot trading page

### ISSUE THREAD

**Issue by pietro-maximoff** [DistributedCollective/Sovryn-frontend#1099]
make the diagram responsive on any resolution
<img width="1292" alt="dim" src="https://user-images.githubusercontent.com/74987028/118116875-84b7e080-b3f3-11eb-8532-8c4abe6f10cd.png">

**Comment by tiltom** [comment]
I also adjusted the history table in this story since it wasn't very responsive.
