### ISSUE TITLE
Finance-V2 Shared Components

### ISSUE THREAD

**Issue by rick23p** [DistributedCollective/Sovryn-frontend#1103]
For the Liquidity/Lend/Borrow V2 pages as the designs are very similar we need to try make reusable components.
Let's add these components into "feat/1103-finance-v2-shared-components" branch (see the linked PR for more info about folder structure) and then we can use these in our pages.
attach you're names to the ones you are working. (please add any suggestion or ideas)

Designs:
Lend: https://xd.adobe.com/view/46cb0da6-bf3f-426b-7226-ffac76cf5eea-30fa/
Borrow: https://xd.adobe.com/view/ccae4509-4638-4022-671b-e3d18640011f-ba9f/
Liquidity: https://xd.adobe.com/view/0d30455c-8cc1-4b39-48a6-cd134bb23573-7b01/

Components:

- [x] PieChart @tiltom - **Done** (used on liquidity page, for lend/borrow it would require to add a secondary color mapping, will be done later)

<img width="121" alt="Screen Shot 1400-02-24 at 12 34 25 PM" src="https://user-images.githubusercontent.com/81699526/118240866-b93da200-b4b0-11eb-9060-12b0c166db6a.png">

- [x] Chart  @soulBit - **Done** (added to liquidity page, just needs to have a max width applied to PoolChart and data piped in/sample data removed)

<img width="347" alt="Screen Shot 1400-02-24 at 12 36 29 PM" src="https://user-images.githubusercontent.com/81699526/118241114-03268800-b4b1-11eb-9c89-b8cc8553b9bb.png">

- [x] RowTable @tiltom - **Done** (used on liquidity page)

<img width="406" alt="Screen Shot 1400-02-24 at 12 36 57 PM" src="https://user-images.githubusercontent.com/81699526/118241168-146f9480-b4b1-11eb-8e11-7bee5dff6af7.png">

- [x] CardRow Layout - @rick23p 

<img width="947" alt="Screen Shot 1400-02-24 at 12 38 03 PM" src="https://user-images.githubusercontent.com/81699526/118241305-3cf78e80-b4b1-11eb-9f91-da6ea8acc7b3.png">

- [x] TopInfo @tiltom - **Done** (used on liquidity page)

<img width="177" alt="Screen Shot 1400-02-24 at 12 37 31 PM" src="https://user-images.githubusercontent.com/81699526/118241225-27826480-b4b1-11eb-8610-01d87612ac8c.png">

- [x] DataBox @tiltom - **Done** (used on liquidity page)

<img width="239" alt="Screen Shot 1400-02-24 at 12 37 41 PM" src="https://user-images.githubusercontent.com/81699526/118241255-2fda9f80-b4b1-11eb-8941-ae3ab88ccac1.png">

- [x] HistoryTable - Status and Pool components were created, the rest of the table is highly screen-dependent so it's not possible to create some shared table. However, look at the liquidity page for inspiration.

<img width="947" alt="Screen Shot 1400-02-24 at 12 42 05 PM" src="https://user-images.githubusercontent.com/81699526/118241781-cad37980-b4b1-11eb-931b-70f049ed3e0f.png">

- [x] Status @tiltom - **Done** (used on liquidity page)

![image](https://user-images.githubusercontent.com/14878713/118243229-7c68af80-b49e-11eb-956e-00d219acb8cb.png)

- [x] Pool @tiltom - **Done** (used on liquidity page)

![image](https://user-images.githubusercontent.com/14878713/118243175-6eb32a00-b49e-11eb-88b0-ee096717a299.png)

**Comment by tiltom** [comment]
I have a suggestion regarding the HistoryTable - I think we should create only components for Pool and Status (see the images below) because the table on the Liquidity page looks quite different. What do you guys think?

![image](https://user-images.githubusercontent.com/14878713/118243175-6eb32a00-b49e-11eb-88b0-ee096717a299.png)
![image](https://user-images.githubusercontent.com/14878713/118243229-7c68af80-b49e-11eb-956e-00d219acb8cb.png)

**Comment by tiltom** [comment]
@soulBit - I saw somewhere on the Discord you were doing some chart prototype or so, could you use it here?

**Comment by soulBit** [comment]
@tiltom yep I'll move it into the new location and make it a little more generic so we can use it on all the pages
