### ISSUE TITLE
MAX button on Lending UI is triggering a round-up error

### ISSUE THREAD

**Issue by jjmr007** [DistributedCollective/Sovryn-frontend#1110]
**Describe the bug**
A user tried to lend the maximum (he hit the button "MAX") of what he has in USDT, the UI is doing a rounding error in excess

what UI shown:_______________0.414505132940496800 USDT
but the actual balanceOf is:__0.414505132940496778 USDT

![ROUND_UP](https://user-images.githubusercontent.com/17028457/118295638-197d1580-b4aa-11eb-800a-d1c47227210c.png)

so in [trying to lending](https://dashboard.tenderly.co/tx/rsk/0xc75aa97089dacf155d8650360e138014136b32afe3901ef06abab81f76f358f8) a revertion occurs with the error: 

Error Message:
ERC777: transfer amount exceeds balance
it likely is happening in the lending transaction of other assets

**To Reproduce**
1.- go to the [lending page](https://live.sovryn.app/lend).
2.- hit the rUSDT bar at the left to show the interface of lending/borrowing for USDT.
3.- select lend
4.- hit the MAX button
5.- hit "DEPOSIT USDT" button

sometimes [the transaction](https://explorer.rsk.co/tx/0xc75aa97089dacf155d8650360e138014136b32afe3901ef06abab81f76f358f8) will revert.

**Expected behavior**
The transaction should succeed.

**Desktop (please complete the following information):**

- OS: macOsx 11.3.1 (20E241)
- Browser chrome
- Wallet: Nifty 5.2.4

**Comment by t-z-u** [comment]
am i correct in thinking that we are talking about 0.000000000000000032 of a USDT??????? @jjmr007

**Comment by creed-victor** [comment]
> am i correct in thinking that we are talking about 0.000000000000000032 of a USDT??????? @jjmr007

Correct, most likely issue is that instead of 18 decimals it rounds to the 16 and also rounds-up numbers but it should round-down in case we use less decimals.

**Comment by jjmr007** [comment]
I think, (as far it is possible) to use all the 18 decimals is the best, in order not to leave any token-dust in any contract.

**Comment by soulBit** [comment]
Another case for reference:
https://dashboard.tenderly.co/tx/rsk/0x8ec9b3574802e28f149548d122434caf5d3ddfa01b9228506e536d289867b24d
