### ISSUE TITLE
Liquidity page - Make Pool rows pixel perfect

### ISSUE THREAD

**Issue by tiltom** [DistributedCollective/Sovryn-frontend#1119]
We need to make Pool rows pixel perfect and responsive (consult responsive behaviour with @t-z-u ).

Now:
![image](https://user-images.githubusercontent.com/14878713/118668224-f6799b00-b7f4-11eb-9e41-70da8946c4db.png)

Design:
![image](https://user-images.githubusercontent.com/14878713/118668299-05f8e400-b7f5-11eb-8392-f888cb69ba09.png)

**Comment by tiltom** [comment]
Design: https://xd.adobe.com/view/0d30455c-8cc1-4b39-48a6-cd134bb23573-7b01/screen/a2dc3659-1d63-4a9a-a5d8-1af55712982a/specs/

**Comment by pietro-maximoff** [comment]
1. Please check paddings and margins in the table, also check font-weight
<img width="1599" alt="2" src="https://user-images.githubusercontent.com/74987028/119143713-98e18a80-ba50-11eb-895f-bbefd40f3202.png">
<img width="736" alt="1" src="https://user-images.githubusercontent.com/74987028/119143721-9bdc7b00-ba50-11eb-83e6-23ffe6a9e1ed.png">

2. not responsive on 1220px
<img width="1217" alt="3" src="https://user-images.githubusercontent.com/74987028/119144013-ef4ec900-ba50-11eb-8c43-51b391c2e1bc.png">
3. as i can see in the design, SOV icon without white border
