### ISSUE TITLE
Liquidity page - Connect History table to the real data and add pagination

### ISSUE THREAD

**Issue by tiltom** [DistributedCollective/Sovryn-frontend#1120]
We need to connect Liquidity History table to real data and add pagination (max 6 items per page). Make it also pixel perfect and check the responsive behaviour (should be OK but just for case).

![image](https://user-images.githubusercontent.com/14878713/118668500-38a2dc80-b7f5-11eb-95e7-4441475600d0.png)

**Comment by tiltom** [comment]
Design: https://xd.adobe.com/view/0d30455c-8cc1-4b39-48a6-cd134bb23573-7b01/screen/a2dc3659-1d63-4a9a-a5d8-1af55712982a/specs/

**Comment by tiltom** [comment]
We are waiting for a backend endpoint.

**Comment by t-z-u** [comment]
is there a link to review?

**Comment by rick23p** [comment]
> is there a link to review?

Since we are having issues on test-net API we can't test it currently.
