### ISSUE TITLE
need to refresh after reward sov has been claimed and transaction complete to see sov balance. same for claiming (balance stays the same until user refreshes page)

### ISSUE THREAD

**Issue by t-z-u** [DistributedCollective/Sovryn-frontend#1146]

**Comment by t-z-u** [comment]
<img width="1104" alt="Screenshot 2021-05-22 at 14 17 28" src="https://user-images.githubusercontent.com/79344165/119228010-bd00a280-bb08-11eb-8a2f-15b3741d8f6e.png">

**Comment by rick23p** [comment]
The issue is happening only on Testnet. (Maybe node issue)

**Comment by tiltom** [comment]
@t-z-u - What are we going to do about this story? @rick23p wrote the issue is only on testnet, are we going to investigate it further or close it? Nobody is working on it at the moment and I don't think that's going to change unless it's moved to Todo.

**Comment by tiltom** [comment]
I tried it on localhost and it works fine, I am closing the ticket.
