### ISSUE TITLE
staking history/vesting unlock not loading

### ISSUE THREAD

**Issue by t-z-u** [DistributedCollective/Sovryn-frontend#1150]

**Comment by t-z-u** [comment]
<img width="1778" alt="Screenshot 2021-05-22 at 18 48 07" src="https://user-images.githubusercontent.com/79344165/119236278-673ef100-bb2e-11eb-89e3-e0a6dcc4cd66.png">
has been doing this for an hour

**Comment by pietro-maximoff** [comment]
waiting when testnode will be up

**Comment by pietro-maximoff** [comment]
fixed
