### ISSUE TITLE
Show USD value for ETHs tokens in dapp Portfolio

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1177]
If possible, we should show USD value for `ETHs` tokens in Portfolio page of dapp, it currently shows 0:

![image](https://user-images.githubusercontent.com/765825/119532936-41f3f200-bd7d-11eb-8253-a4b9dcb04491.png)

**Comment by tiltom** [comment]
The reason for this is, we don't have conversion rates for `ETHs` (see the screenshot). We will probably need some backend adjustments as well. What do you think @creed-victor ?

![image](https://user-images.githubusercontent.com/14878713/121532230-71526200-c9ff-11eb-8c2e-fe99eb0f7b65.png)

**Comment by grinry** [comment]
App uses swap rates for ETHs, SOV and BNB (assets which has no oracle rates), issue opened 20 days ago it should already show USD prices unless node itself fails:

<img width="1111" alt="Screenshot 2021-06-14 at 10 27 23" src="https://user-images.githubusercontent.com/5575688/121854653-4be78180-cca7-11eb-9e4b-1ced1ef28591.png">

**Comment by tiltom** [comment]
> App uses swap rates for ETHs, SOV and BNB (assets which has no oracle rates), issue opened 20 days ago it should already show USD prices unless node itself fails:
> 
> <img alt="Screenshot 2021-06-14 at 10 27 23" width="1111" src="https://user-images.githubusercontent.com/5575688/121854653-4be78180-cca7-11eb-9e4b-1ced1ef28591.png">

Is the screenshot from the production? It shows 0 on the local so I don't know if we have some issues with node or what but we can close the story if it works on the production.

**Comment by grinry** [comment]
Yes production, debugged testnet - platform has only cents in eth liquidity you can swap 1 BTC for 0.014372 ETH only (which is ~$35), because of it rates can't be calculated correctly.

Platform could use public rate apis from coinmarketcap for example, but it would show different rates than our swap rates then - which would be confusing for our users.

Closing this as there is no actual issue.
