### ISSUE TITLE
Investigate Liquidity Mining Row scroll issues

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1191]
"Just a suggestion with the user interface for liquidity mining. All of the options (as I view them on my desktop) require you to scroll across to find the deposit/withdrawal buttons to add the liquidity. It would be better (less confusing) if that need to scroll sideways wasn't there and it was all clear and obvious on the liquidity page." - on 50 inch TV with chrome

"Similar with my 15 inch 1080p (full HD) laptop monitor (Win 10, Chrome browser).  I can see buttons, but they are cut a bit on the right edge. After playing with magnification up and down and then resetting it to 100% then it aligns ok."

**Comment by tiltom** [comment]
I haven't been able to simulate it on my 4k 27-inch monitor - I tried multiple scale settings, the lowest resolution was 1504 x 846 and the highest 3840 x 2160. 

However, it's true that the rows have a horizontal scroll from 1200 to 1252px width and this could be the only reason for it. So I will try to remove the scroll for that specific edge-case.
