### ISSUE TITLE
Send GA event when user engages wallet

### ISSUE THREAD

**Issue by t-z-u** [DistributedCollective/Sovryn-frontend#1192]
Using react-ga lib add event which would be sent when user successfully engages wallet.
Adding wallet type and maybe address (should be hashed) included in the event would be helpful too.

**Comment by t-z-u** [comment]
@creed-victor is there a reason to change this and no longer have the UTM code?
been talking with slider and we are both a bit confused why it was taken out

**Comment by soulBit** [comment]
@t-z-u all good, the GA package we use includes the UTM stuff by default so no need to manually pass it in. I've provided Krillin with details on how the setup works, once we have confirmation from him that it looks ok then I will deploy to testnet
