### ISSUE TITLE
Transak fiat onramp doesn't fill receivers BTC address in the widget

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#1205]
Currently some users needs to open fastBtc, generate BTC address, copy it and then open fiat (transak) widget and address there. 

I think issue of not autofilling btc address is that when "Buy RBTC with fiat" button is clicked it creates race condition between requesting backend to create new address and opening widget - in this case widget wins the race and is opened without btc address.

Fix would be to first wait for address to be created and then initialise transak widget.

**Comment by soulBit** [comment]
@boltsr I can see this was updated in #1213 but it doesn't appear to be working (tested on staging env) - I think we need to follow Victor's method to resolve this, could you take a look?
