### ISSUE TITLE
On Swap window should show the price of the unity of each coin

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#1220]
Hi,

On Swap window should show the price of the unity of each coin. See the example:

![Captura de tela de 2021-05-30 13-07-40](https://user-images.githubusercontent.com/1178856/120111718-7256da00-c149-11eb-8f25-89f3ca6847f4.png)

**Comment by boltsr** [comment]
To implement this function, I think we need price feed API
