### ISSUE TITLE
Add all the correct pairs to spot list

### ISSUE THREAD

**Issue by t-z-u** [DistributedCollective/Sovryn-frontend#1248]
Full pair list to include on Spot:

SOV_RBTC
SOV_USDT
SOV_DOC
SOV_BPRO
SOV_ETH
SOV_MOC
RBTC_USDT
RBTC_DOC
RBTC_BPRO
RBTC_MOC
BPRO_USDT
BPRO_DOC
BPRO_MOC
USDT_DOC
USDT_MOC
ETH_RBTC
ETH_USDT
ETH_BPRO
ETH_MOC
ETH_DOC
DOC_MOC

**Comment by soulBit** [comment]
@t-z-u Betsy has updated and deployed backend changes for ETH/MoC price data now, we can start working on this

**Comment by creed-victor** [comment]
There pairs are already in the testnet and will be pushed with next release. If there is other pairs that needs to be added please list them in task description.
