### ISSUE TITLE
tidy origin sign up

### ISSUE THREAD

**Issue by t-z-u** [DistributedCollective/Sovryn-frontend#1285]
can you please tidy up the email sign up, loose the name field and make sure it all sits above the fold please

**Comment by creed-victor** [comment]
> can you please tidy up the email sign up, loose the name field and make sure it all sits above the fold please

was it cleared with krillin? need to be sure that email provider service and backend is adjusted for this, currently backend will not accept form without name

**Comment by tiltom** [comment]
> > can you please tidy up the email sign up, loose the name field and make sure it all sits above the fold please
> 
> was it cleared with krillin? need to be sure that email provider service and backend is adjusted for this, currently backend will not accept form without name

Have you spoken to krillin @t-z-u ?
