### ISSUE TITLE
'engage wallet' and pressing 'Liquality' leads them to the download page

### ISSUE THREAD

**Issue by t-z-u** [DistributedCollective/Sovryn-frontend#1299]
it appears that the liquality option is directing users to download the wallet

**Comment by creed-victor** [comment]
yes, if user has no liquality wallet installed, or if it's disabled

**Comment by soulBit** [comment]
Closing this, likely issue is related to multiple wallets being installed, password not entered in wallet yet, or wallet extension being inactive
