### ISSUE TITLE
Needed to refresh page to show swap done on swap history

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#1300]
Hi,

I did a swap but I needed to refresh the page to the swap appear on swap history.

Should show the swap without need to refresh the page.

**Comment by bitcoinuser** [comment]
Fixed.

**Comment by bitcoinuser** [comment]
Did a new test and looks like it's not fixed.

**Comment by pietro-maximoff** [comment]
tested with different pairs - all good without refreshing

**Comment by bitcoinuser** [comment]
> tested with different pairs - all good without refreshing

Strange that with me doesn't work. I'll test again later today to see if is already fixed. I think when the user close the confirmed transaction popup window, should show the swap on history.
