### ISSUE TITLE
Margin trade dialog - retrieve maintenance margin value from smart contract

### ISSUE THREAD

**Issue by tiltom** [DistributedCollective/Sovryn-frontend#1302]
Currently, there is a hardcoded value (15%) but it can change in the future (or we could have different maintenance margin for different pairs) so we need to change it and read from a smart contract.

We don't have such a contract now (confirm this with Circle of Order).

**Comment by tiltom** [comment]
Since this was moved from Backlog to To do, does that mean we have the contract for it now? @t-z-u @soulBit

**Comment by tjcloa** [comment]
maintenance margin is a part of loan token parameter set - one parameter set per collateral token of loan token
it means that maintenance margin can be read from each loan token contract for each collateral token listed for the loan token

**Comment by soulBit** [comment]
Migrated to Taiga in https://taiga.sovryn.app/project/sovryn-light/us/169?no-milestone=1
