### ISSUE TITLE
Implement Multicall for reading contract data in batches

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#1333]
It will make less contract calls and should increase loading speed for pages which requires a lot of data from blockchain (staking, bitocracy, asset rates)
https://github.com/makerdao/multicall

**Comment by soulBit** [comment]
Example implemented in https://github.com/DistributedCollective/governance-dapp/pull/121 and https://github.com/DistributedCollective/governance-dapp/pull/123

**Comment by tiltom** [comment]
I suppose we can close this story, right? In case we want to implement optimization on some specific page, we can create a new story just for that

**Comment by soulBit** [comment]
Closing this as suggested, we will open separate tickets for any areas of the dapp that need to implement it
