### ISSUE TITLE
Margin Trade position incorrect

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1338]
"Hi Sovryn, added to margin position yesterday. The second position should be 1 btc to 3x but it's showing as 2.1914 BTC as position size and position margin as 0.7305 BTC (3x) but it's suppose to be 3x 3 BTC and 1.0 BTC.

Is my bitcoin missing in transaction?

Wallet Address is 0x1254D9F362a3d1892D73dEF2928FD832BBEe759D"

![image](https://user-images.githubusercontent.com/765825/122032947-02428800-cdc8-11eb-91b0-8885ea2811ac.png)

https://sovryn.freshdesk.com/a/tickets/634

**Comment by boltsr** [comment]
We've discussed about this problem with Victor.
It is contract problem.

**Comment by bitnym** [comment]
Can we get more details on the "contract problem"?
