### ISSUE TITLE
Create initial user stories for QA

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1343]

**Comment by tiltom** [comment]
What is this story about?

**Comment by soulBit** [comment]
@tiltom we need to create some user stories for basic dapp interactions, for Jonathan to use as a base for his QA testing - if you would like to work on this, I can add more detail to the ticket

**Comment by tiltom** [comment]
@soulBit thanks for the explanation, I don't have time for it now, I just didn't know what this is about and I've seen this story in To do for quite some time. However, if I have time next week and it still will be here, I will contact you about more info :)
