### ISSUE TITLE
Suggestion - Show the swap fee and pool type on the swap page

### ISSUE THREAD

**Issue by TheSovrynGimp** [DistributedCollective/Sovryn-frontend#1376]
User Suggestion:
"As a suggestion I'd like to see the fee on the swaps page https://live.sovryn.app/swap. Idk how good is that for marketing, but as a trader I want to know what is the cost of my transactions before performing the trade and not having to research the wiki. Moreover, I don't see anywhere info about what pool (V1,V2) each trading pair belongs to"

The tx fee is shown already, but including the swap fee and pool type somewhere may help to be more transparent

**Comment by bitcoinuser** [comment]
I agree.

I think Swap page of Sovryn is not well designed. I think Sovryn in this case shouldn't reinvent the wheel and just follow what we have on the market. See this great example: https://www.orca.so/

![Captura de tela de 2021-06-21 11-25-57](https://user-images.githubusercontent.com/1178856/122778947-d15cca00-d283-11eb-98ad-e3c66e1a0720.png)
