### ISSUE TITLE
Improvement on Yield Farm page

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#1385]
Hi,

1- I think when an user don't have the asset or both assets on balance, the message instead of (Add liquidity and earn income) should be something like (You need x asset to add liquidity to this pool) 

2- If the user do not have the asset to add liquidity, the Deposit button should be inactive.

**Comment by creed-victor** [comment]
Would be nice, however each balance check make request to the node which slows down page from showing full info (you may already notice that there is some time when pools are not interactable/dimmed for some time).
So i'm against adding these additional calls until (and if) "multicalls" are implemented to the dapp.
