### ISSUE TITLE
"Approve tokens" is hidden under withdrawal dialog in Yield Farm page

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#1388]
When withdrawing from Yield Farm pool and if user needs to approve tokens to be spend, then "approve tokens" modal launches behind withdrawal modal, which causes it to be invisible.
Used ledger on mainnet to notice that.

**Comment by tiltom** [comment]
I haven't been able to simulate that, which wallet did you use? It looks good with Nifty.

![image](https://user-images.githubusercontent.com/14878713/123282166-8b656780-d50a-11eb-8c5b-3e330ae9c48b.png)

**Comment by grinry** [comment]
Ledger and chrome browser. Maybe it has something to do with the fact that I was withdrawing from multiple pools without waiting for tx to complete

**Comment by pietro-maximoff** [comment]
did a lot of testing and can't reproduce it
