### ISSUE TITLE
I don't see strings to translate some texts to PT-BR

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#143]
Fixed

**Comment by bitcoinuser** [comment]
![Captura de tela de 2021-01-12 14-17-26](https://user-images.githubusercontent.com/1178856/104349048-32b48c00-54e1-11eb-8bd0-e655e1eb015d.png)

**Comment by bitcoinuser** [comment]
One more:

![Captura de tela de 2021-01-17 14-22-12](https://user-images.githubusercontent.com/1178856/104850754-ba2e4080-58cf-11eb-97c5-1a0003bcbb62.png)

**Comment by bitcoinuser** [comment]
One more

![Captura de tela de 2021-01-17 15-30-57](https://user-images.githubusercontent.com/1178856/104852344-527cf300-58d9-11eb-92a4-8c3b64803170.png)

**Comment by creed-victor** [comment]
"Liquidate position" and "Repay loan" dialog strings added.

**Comment by bitcoinuser** [comment]
More:

![Captura de tela de 2021-01-22 22-12-57](https://user-images.githubusercontent.com/1178856/105564113-7b4d2000-5cff-11eb-89a5-a5e883a94150.png)

**Comment by bitcoinuser** [comment]
More:

![photo_2021-01-23_21-26-50](https://user-images.githubusercontent.com/1178856/105618032-dc3d2c80-5dc1-11eb-8f74-8e0ad2c6a3c8.jpg)

**Comment by bitcoinuser** [comment]
More

![Captura de tela de 2021-01-24 11-22-42](https://user-images.githubusercontent.com/1178856/105633379-f06f4100-5e36-11eb-8567-39f4f4ef280a.png)

**Comment by bitcoinuser** [comment]
@soulBit Could add this ones too? Thanks

![Captura de tela de 2021-02-01 10-15-41](https://user-images.githubusercontent.com/1178856/106479377-08734000-6489-11eb-8978-a41a819043a9.png)

![Captura de tela de 2021-02-01 12-24-37](https://user-images.githubusercontent.com/1178856/106479404-0f9a4e00-6489-11eb-9c4e-3224c8066b35.png)

**Comment by bitcoinuser** [comment]
Hi @soulBit, please add this, thanks

![Captura de tela de 2021-02-02 13-02-59](https://user-images.githubusercontent.com/1178856/106627624-bea55b00-6557-11eb-9587-7806d80fa70f.png)
