### ISSUE TITLE
The buttons show wrong on Yield

### ISSUE THREAD

**Issue by boltsr** [DistributedCollective/Sovryn-frontend#1436]
![Screen Shot 2021-07-07 at 10 02 04 AM](https://user-images.githubusercontent.com/38220699/124682121-63640400-df0d-11eb-9446-0edc22f33df5.png)

I've tested Google Chrome, Opera, Microsoft Edge.

**Comment by soulBit** [comment]
@boltsr I think it's just on `development` branch, this one should be resolved on latest Release build, can you give it a try there?

https://release.sovryn.pages.dev/yield-farm

**Comment by soulBit** [comment]
Closing this as discussed, issue will be resolved when release branch is merged back into development
