### ISSUE TITLE
XUSD Lending Pool Reward SOV reset after making additional deposits

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1456]
If a user deposits into the XUSD lending pool and earns some amount of Reward SOV, then makes another deposit into the pool, the previous Reward SOV will reset to 0.

before:
![image](https://user-images.githubusercontent.com/765825/125430301-606e6b96-7168-4afa-a01a-6a4b7dcef71d.png)

after:
![image](https://user-images.githubusercontent.com/765825/125430789-fecc4a74-e53a-4c39-8465-03b5f9402f4c.png)

We should check if there is an issue with the contract, or just frontend logic. This issue occurs on both testnet and mainnet.

User report:
https://discord.com/channels/729675474665603133/813119624098611260/864240442630864946

"Deposited XUSD a few hours ago into the lending pool and saw that my SOV reward was up to .08. Just deposited an additional amount of xUSD and the SOV reward completely reset. I don’t see anything to withdraw under rewards so it wasn’t extracted."

edit - followup from user:
"Update: I withdrew the xUSD and rewards registered higher than was shown. So I think it’s just the UI that failed to update since the original rewards from the first deposit were apparently there on the backend."

Please target `master` branch for this fix/PR.

**Comment by jameshowlett977** [comment]
`function getUserAccumulatedReward(address _poolToken, address _user) external view returns (uint256) {`

getUserAccumulatedReward - returns accumulated reward since last reward calculations
this amount will be started from zero after each `deposit` and other operations like 

We need to sum this value with another one:

`reward1 = getUserAccumulatedReward(pool token address, user address)`

`poolId = liquidityMining.getPoolId(pool token address)
userInfoList = liquidityMining.getUserInfoList(user address)
reward2 = infoList[poolId][2]`

`totalReward = reward1 + reward2`

**Comment by boltsr** [comment]
@jameshowlett977 I've tried but I get zero:
![Screen Shot 2021-07-15 at 1 57 29 AM](https://user-images.githubusercontent.com/38220699/125660924-adc668dd-e685-447c-b03d-5b4a1a11c909.png)
I get userInfoList and PoolID like this.
As you can see the screenshot, the pool id is 1 and the userInfoList[0][2] = 0

**Comment by jameshowlett977** [comment]
`function getUserInfoList(address _user) external view returns (UserInfo[] memory)`

`struct UserInfo {
		uint256 amount;
		uint256 rewardDebt;
                uint256 accumulatedReward;
}`

- if pool id is 1 you need to get `userInfoList[1][2]`, not `userInfoList[0][2]` or `userInfoList[1].accumulatedReward`, but please check how to access this array in js (my example is for solidity)

- accumulatedReward can be zero if amount is zero or you have claimed reward without a new deposit after it,
try to deposit (for zero amount 2 times) to get `accumulatedReward`

- I've just checked for iXUSD on testnet (poolId = 18), according to the screenshot you also has balance of iXUSD and accumulatedReward > 0

- poolId = 5 - deposit some tokens
- poolId = 1 - deposit some tokens 2 times
