### ISSUE TITLE
Lending Pool withdrawal fails if performed directly after a deposit

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1457]
Deposit into a pool (e.g. XUSD), once tx confirms immediately refresh, and try to withdraw the balance. The transaction should fail, as the `withdrawAmount` in LendingDialog component (which is passed to unlend contract call) is returning 0.

The issue may be because `useLending_balanceOf()` hook needs to be queried again when dialog is opened, not just on first render (currently this only happens when Lend page is initially opened).

**Comment by tiltom** [comment]
I tried it on local with the latest master and everything looks fine, could you confirm @soulBit if you can still simulate the problem?

**Comment by soulBit** [comment]
Closing this as we are unable to replicate any longer
