### ISSUE TITLE
Optimize Code Splitting

### ISSUE THREAD

**Issue by ShynRou** [DistributedCollective/Sovryn-frontend#1493]
Currently all dependencies are bundled in one giant chunk, that is loaded on every page, which results in long loading times, when not cached yet.

- [ ] Dynamic Import of \@sovryn/react-wallet
- [ ] Check for further heavy dependencies to split off

Should be started after #1475 (now #1347) is merged.

**Comment by ShynRou** [comment]
Stopped working on it for now. Dynamic Import of @sovryn/react-wallet requires changes to the react-wallet and wallet projects themselves, because the usage of React.Context prevents a the use of dynamic imports. One cannot dynamically import and use a ContextProvider via hooks, without breaking react. The usage of @sovryn/wallet also has to be made dynamic to reduce the bundle size dramatically since it includes heavy dependencies.

**Comment by soulBit** [comment]
Migrated to Taiga in https://taiga.sovryn.app/project/sovryn-light/us/165
