### ISSUE TITLE
Margin trading failing on testnet

### ISSUE THREAD

**Issue by pietro-maximoff** [DistributedCollective/Sovryn-frontend#1529]
https://dashboard.tenderly.co/tx/rsk-testnet/0x11c3019b3a3be3dd67453546afd08b1aad5b0fc1a1473f87db8457c2ac51115f

**Comment by pietro-maximoff** [comment]
waiting for Cowsant reply

**Comment by creed-victor** [comment]
Issue is with new smart-contract ABI on testnet, added PR with fix.
