### ISSUE TITLE
Allow target amount to be set for swaps, as well as input amount

### ISSUE THREAD

**Issue by TheSovrynGimp** [DistributedCollective/Sovryn-frontend#1533]
Allow users to specify the target 'receive' amount during swaps as well as the input amount:
![image](https://user-images.githubusercontent.com/86018066/126608406-fef05e9a-3d60-4b33-afc2-b84089abc98f.png)

Currently, users must iterate through the input amounts to achieve their desired output

**Comment by creed-victor** [comment]
Unfortunately smart-contract doesn't have function to calculate how much user must send to receive required amount right now.

Leaving open for discussions to research on how it can be done entirely from frontend side.
