### ISSUE TITLE
disable tab focus for firefox on trade

### ISSUE THREAD

**Issue by JoeStorm99** [DistributedCollective/Sovryn-frontend#1536]
on FF when a user enters an amount in the trade page u can see the focus is turned on

steps to repro: 
1. Launch FF
2. navigate to: https://test.sovryn.app/trade
3. enter an amount into the amount session

Note that the focus is see screenshot for more info
![Screenshot 2021-07-22 at 17 27 53](https://user-images.githubusercontent.com/85491205/126677504-f41bbf63-b284-424a-8e56-db82dee0ac16.png)

**Comment by pietro-maximoff** [comment]
seems it is already fixed

**Comment by soulBit** [comment]
@pietro-maximoff thanks for checking on this. Yes, Jonathan cannot replicate this any more so closing this
