### ISSUE TITLE
Slippage for Margin Trades

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1568]
Currently slippage is not used for Margin Trades. We need to implement similar functionality to the existing slippage setup from Swap/Spot page. This should be included for opening a Margin Trade, Increasing Position Size, and Closing Margin Trade.

- [x] Add slippage slider to TradeDialog component
- [x] Implement minReturn param on opening Margin Trade 
- [x] `marginTrade` contract call (and ensure ABI is up to date)
- [ ] Add `minReturn` support to Increasing Position Size
- [ ] Add `minReturn` support to Closing Margin Trade

XD Design for each action:
https://xd.adobe.com/view/f742b57d-92fc-44b4-4f93-49ade24a3795-8173/screen/abc54b60-f646-4757-bee9-a912c65da92e/specs/

**Comment by creed-victor** [comment]
Increasing and closing positions doesn't have minReturn (slippage) on SC side.
