### ISSUE TITLE
Margin Trade - Liquidation price not updating

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1571]
Margin position with loanID: `0x12f35517f86a89904ca73d67bf09789931bc9deb315ad3e1302fbb526f5e0365` has sucesfully done top-ups to the position, but the UI don't show a lower liquidation price.

User reported this to a CM via DM. This is a 2x LONG position (XUSD/BPro) created with 0.01 BPro as collateral. So initially the position should be of 0.02 BPro. Opening price: 42,167.86; today the position has 0.05987 BPro and a margin of 406.98% (so very hard to liquidate), but the liquidation price shown by the UI is still the same. 

Potentially related to #1389

**Comment by tiltom** [comment]
Putting this on hold since the trading abi changed and all trading transactions will fail until we merge https://github.com/DistributedCollective/Sovryn-frontend/pull/1559 .
