### ISSUE TITLE
Upgrade to WalletConnect v1.5.0 

### ISSUE THREAD

**Issue by brunocalmels** [DistributedCollective/Sovryn-frontend#1574]
**Is your feature request related to a problem? Please describe.**
Establishing a Wallet Connect session with any Wallet Connect client (specifically Defiant, in my case) takes a long time or even never completes. 

**Describe the solution you'd like**
A few days ago, Wallet Connect [released version 1.5.0](https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/1.5.0) that is supposed to alleviate congestion causing such problems.

**Describe alternatives you've considered**
None.

**Additional context**

Wallet Connect [tweet](https://twitter.com/WalletConnect/status/1419999849068564505):
> We are seeing once again a lot of traffic on our servers :warning:
>
>However this time we are tackling the problem differently and we have prepared a new release for WalletConnect v1.0 :tools:
>
>If you are a Dapp experiencing high latency with WalletConnect.... please upgrade to v1.5.0 asap :arrow_up:

**Comment by creed-victor** [comment]
Added to testnet with #1347
