### ISSUE TITLE
Suggestion: Font change to be easy to read information

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#161]
Hi,

I think the font used today on sovryn is very hard to read the information. See the example here:

![Captura de tela de 2021-01-14 11-23-32](https://user-images.githubusercontent.com/1178856/104604548-3caeca00-565c-11eb-89a5-7dfef010c3f0.png)

**Comment by bitcoinuser** [comment]
Another example:

![Captura de tela de 2021-01-14 12-31-35](https://user-images.githubusercontent.com/1178856/104612089-94e9ca00-5664-11eb-8df5-8cc4f4c49018.png)

**Comment by creed-victor** [comment]
@kayalight

**Comment by kayalight** [comment]
I am currently redesigning the whole dapp

**Comment by kayalight** [comment]
please close
