### ISSUE TITLE
Doesn't make sense cut the word Alavancag... on Desktop

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#162]
Hi,

Doesn't make sense cut the word Alavancag... on Desktop

![Captura de tela de 2021-01-14 11-45-28](https://user-images.githubusercontent.com/1178856/104606287-56e9a780-565e-11eb-9eb0-f92288a95f12.png)

**Comment by creed-victor** [comment]
Related to #164
