### ISSUE TITLE
Important to show complete word on Mobile PT-BR

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#165]
Hi, 

It's important to show the complete word on this case. I think what is inside parentheses could go to another line.

![photo_2021-01-14_14-17-50](https://user-images.githubusercontent.com/1178856/104625503-9242a100-5673-11eb-8035-5f674a9f5a77.jpg)

**Comment by creed-victor** [comment]
Related to #164
