### ISSUE TITLE
[Sovryn Dapp] #52 This is missleading for me - I...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#168]
This is missleading for me - I did not know at first that this button can be clicked. It has the "I am not clickable" grey :)

*Source url:* https://test.sovryn.app/lend
*Reported by:* 
*Reported at:* 14 Jan at 17:14 UTC

*Location:* DE, Hesse, Kassel
*Browser:* Chrome 87.0.4280.141

*OS:* Windows 10.0
*Screen:* 1920x1080
*Viewport:* 1920x937

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/w930gqhj8jpwzdpg49t1/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTA2NTAxMzAsImRhdGEiOnsicmVwb3J0IjoidzkzMGdxaGo4anB3emRwZzQ5dDEiLCJ1c2VyIjoiR2l0SHViIn19.wqqtzMVhjVbQX-Imrx2-0TGJUZwvqem4HjYVE8UUVWw)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/w930gqhj8jpwzdpg49t1](https://ybug.io/dashboard/reports/detail/w930gqhj8jpwzdpg49t1)

**Comment by creed-victor** [comment]
@kayalight

**Comment by kayalight** [comment]
I am currently redesigning the whole dapp

**Comment by kayalight** [comment]
please close
