### ISSUE TITLE
[YBUG.IO] #43 - Please make a how to how i can...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#176]
Please make a how to how i can provide liquidity and what i can earn by doing so

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* 
*Reported at:* 09 Jan at 21:00 UTC

*Location:* DE, Bavaria, Neu-Ulm
*Browser:* Firefox 84.0

*OS:* Linux unknown
*Screen:* 1536x864
*Viewport:* 1536x734

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/v5vhjgtj4bx1b76nd3pd/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTA2NTA1MDcsImRhdGEiOnsicmVwb3J0IjoidjV2aGpndGo0YngxYjc2bmQzcGQiLCJ1c2VyIjoiR2l0SHViIn19.pzwvWywSqTcNu97Ti9DaB9D1Txx3Pigp89klCFhpv54)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/v5vhjgtj4bx1b76nd3pd](https://ybug.io/dashboard/reports/detail/v5vhjgtj4bx1b76nd3pd)

**Comment by soulBit** [comment]
@t-z-u I think adding a paragraph or two at the top of the new Liquidity Mining page would be good, similar in content to description on Buy SOV page:

![image](https://user-images.githubusercontent.com/765825/119369670-5916df00-bcac-11eb-9eb2-61197a94d463.png)
