### ISSUE TITLE
[YBUG.IO] #55 - Send (r)BTC: field label vague....

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#179]
Send (r)BTC: field label vague. Send where?

*Source url:* https://test.sovryn.app/sales
*Reported by:* 
*Reported at:* 14 Jan at 19:21 UTC

*Location:* ES, Catalonia, Barcelona
*Browser:* Chrome 87.0.4280.88

*OS:* Windows 10.0
*Screen:* 1920x1080
*Viewport:* 1536x750

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/1hptntkkay3km0md23p9/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTA2NTIxMDMsImRhdGEiOnsicmVwb3J0IjoiMWhwdG50a2theTNrbTBtZDIzcDkiLCJ1c2VyIjoiR2l0SHViIn19.hhI9oFWQYSGKiNBpV1WwWzoG88g8BFtdMJRSTCAWdK4)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/1hptntkkay3km0md23p9](https://ybug.io/dashboard/reports/detail/1hptntkkay3km0md23p9)

**Comment by creed-victor** [comment]
@kayalight

**Comment by kayalight** [comment]
<img width="1268" alt="Screenshot 2021-01-15 at 09 07 07" src="https://user-images.githubusercontent.com/77350089/104704938-33336980-5711-11eb-9666-36c0d3e675bf.png">

**Comment by kayalight** [comment]
<img width="528" alt="Screenshot 2021-01-15 at 09 06 38" src="https://user-images.githubusercontent.com/77350089/104704954-39c1e100-5711-11eb-94f7-db1c2944e10e.png">

**Comment by kayalight** [comment]
thats the way it is

**Comment by kayalight** [comment]
please close issue
