### ISSUE TITLE
[YBUG.IO] #60 - Hi, please help me

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#184]
Hi, please help me 
On 01/04, after linking my Metamask wallet, I transferred 0.09523217 BTC to my BTC address in Sovryn (bc1qjxq5sk9myjnp4ytl7lekl9hv4v5druvhaxr09jvr3asdgyrfnnlq4yjsek) using the TOP-UP feature (TXID: a44a1c07d8cf91e6407528ea195cb2dc44942b4fad60f0292bf01c46565c3f7d - Completed). 
They supposed to be credited as RBTC in Metamask, but I'm still waiting for those RBTCs. 
In addition, after the problems that occurred on the sovryn site, a new BTC address has generated me today (bc1qwsqxj5sxzhkx2zakvlygnwgusy2sccwun5g6v5ypsk0x6mu630ns7g52g6). 

How can I get those BTC back? 
plaease help me, thanks!

*Source url:* https://live.sovryn.app/wallet
*Reported by:* luishelguera@objetiva.com.ar
*Reported at:* 14 Jan at 23:05 UTC

*Location:* AR, Tucuman, Yerba Buena
*Browser:* Chrome 87.0.4280.141

*OS:* Windows 10.0
*Screen:* 1920x1080
*Viewport:* 1920x941

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/qcymr4br2yzqp9wff5j1/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTA2NjU1NjIsImRhdGEiOnsicmVwb3J0IjoicWN5bXI0YnIyeXpxcDl3ZmY1ajEiLCJ1c2VyIjoiR2l0SHViIn19.BXntx4ryRLusVVKMQvbu3pxO-SSAxxn569y1p-xJdRQ)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/qcymr4br2yzqp9wff5j1](https://ybug.io/dashboard/reports/detail/qcymr4br2yzqp9wff5j1)

**Comment by jamiemadrox779** [comment]
funds transferred
