### ISSUE TITLE
[YBUG.IO] #67 - I put my usdt on leding but I...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#209]
I put my usdt on leding but I cant see it anywhere. Even not in my lending history.

*Source url:* https://test.sovryn.app/lend
*Reported by:* tpacalt@gmail.com
*Reported at:* 16 Jan at 21:46 UTC

*Location:* CZ, Jihocesky kraj, Písek
*Browser:* Chrome 87.0.4280.141

*OS:* Windows 10.0
*Screen:* 1536x864
*Viewport:* 1536x722

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/hpq37hq5w8cqgbmjj3vw/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTA4MzM2MjIsImRhdGEiOnsicmVwb3J0IjoiaHBxMzdocTV3OGNxZ2JtamozdnciLCJ1c2VyIjoiR2l0SHViIn19.OG2aW6hNKlzQj9cj_4-mdZbiFhWlp87KCxV2MNa0P0c)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/hpq37hq5w8cqgbmjj3vw](https://ybug.io/dashboard/reports/detail/hpq37hq5w8cqgbmjj3vw)

**Comment by bitcoinuser** [comment]
I think he needs to click on redeem. 

This part is confusing and I think should be improved.

**Comment by bitcoinuser** [comment]
Maybe show the information of funds lent and borrowed on My wallet window too.

**Comment by creed-victor** [comment]
Yes, there is a chance that user just didn't know he needs to click "redeem", however he noted that lending history is also empty so there may be some other issue.

Our designer is working on new design that would remove some confusing parts.

**Comment by bitcoinuser** [comment]
> Yes, there is a chance that user just didn't know he needs to click "redeem", however he noted that lending history is also empty so there may be some other issue.
> 
> Our designer is working on new design that would remove some confusing parts.

Great to know that the design is working on new things. Hope he change the font too from some parts.
