### ISSUE TITLE
Dynamic button text like rskswap.com

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#222]
Hi,

I think the trade and swap windows could have dynamic text buttons, for example: 

1- All buttons like Long, Short, Leverage and fields Currency and Amount will be disabled. So the button (Place Trade) will be renamed to (Select position). So when the user select the position long or short, the button (Select position) will change dynamic to (Select leverage). So when the user select the leverage, the button (Select leverage) will change dynamic to (Select currency) and so on, until the final change to (Place trade). The idea is the same of rskswap:

![Captura de tela de 2021-01-17 20-40-07](https://user-images.githubusercontent.com/1178856/104859590-3db65480-5905-11eb-9a4d-e88d98934f68.png)

**Comment by creed-victor** [comment]
Flow will be improved with page redesign #346, #354
