### ISSUE TITLE
Repay button still active when transaction is being processing or already confirmed

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#234]
Hi,

I repaid a loan and during the transaction being processing or already confirmed, the button Repay still is active. But I think should be inative. One time I made a mistake of do two transactions because the Repay button was still active.

![Captura de tela de 2021-01-19 11-49-20](https://user-images.githubusercontent.com/1178856/105050889-018e0b80-5a4d-11eb-8423-908cd7698df5.png)

![Captura de tela de 2021-01-19 11-50-21](https://user-images.githubusercontent.com/1178856/105050904-0652bf80-5a4d-11eb-9cf9-c45749f9c9fe.png)

**Comment by creed-victor** [comment]
Thanks, as I understand "borrowed amount" also didn't change after confirmation?
Normally amount should be reduced or screen changed to "Loan repaid", but sometimes new block information is skipped for unknown reasons.

There is possibility of race condition issue somewhere.
Needs further investigation.

**Comment by bitcoinuser** [comment]
> Thanks, as I understand "borrowed amount" also didn't change after confirmation?

Yes, didn't change.

I think REPAY button should be inactive during the transaction pending too. Some people could click this again thinking something is not right.
