### ISSUE TITLE
Menu should be a modal with close button that cover all window on mobile

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#236]
Menu should be a modal with close button that cover all window on mobile
It's very hard to click on this menu. Very small.

![photo_2021-01-19_11-59-29](https://user-images.githubusercontent.com/1178856/105051931-0a331180-5a4e-11eb-8227-e7520ad02b92.jpg)

**Comment by bitcoinuser** [comment]
Here is an example of how I would like to see Sovryn menu on mobile. The site is liquality.io:

![photo_2021-01-23_12-01-31](https://user-images.githubusercontent.com/1178856/105597709-cd7b5900-5d72-11eb-93aa-3b75e0f810ef.jpg)

**Comment by pietro-maximoff** [comment]
fixed in branch - feat/fix-mobile-menu
