### ISSUE TITLE
Language option needs improvement on text color when not selected

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#237]
Language option needs improvement on text color when not selected

![Captura de tela de 2021-01-19 12-02-01](https://user-images.githubusercontent.com/1178856/105052326-84fc2c80-5a4e-11eb-8a42-f04b5f75c6e3.png)

**Comment by creed-victor** [comment]
Indeed, selector should be changed from native  to the custom ones we use for everything else.
