### ISSUE TITLE
After I liquidate a position and transaction confirmed, the window stay black being need to refresh the window

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#239]
After I liquidate a position and transaction confirmed, the window stay black being need to refresh the window

![Captura de tela de 2021-01-19 12-33-48](https://user-images.githubusercontent.com/1178856/105056356-dc9c9700-5a52-11eb-9b3a-89245baeb315.png)

**Comment by creed-victor** [comment]
@bitcoinuser if it happens again open developers console `command+option+j` (mac) or `control+shift+h`- it will help us to debug for why it happended.
You can also use `feedback` button.

**Comment by bitcoinuser** [comment]
I'm not able to reproduce this anymore. If I reproduce again, I reopen the issue.

**Comment by creed-victor** [comment]
Just got same issue myself :)

**Comment by bitcoinuser** [comment]
@creed-victor I still can reproduce this problem when closing a trade on test.sovryn.app
