### ISSUE TITLE
[YBUG.IO] Completely my bad on this, but...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#270]
Completely my bad on this, but we should probably get rid of the "trade" and "swap" functions for cSOV?
a suggestion would be to add a disabled button that reads "claim SOV" that way we can add a modal that will have the interface to claim the SOV

*Source url:* https://live.sovryn.app/wallet
*Reported by:* 
*Reported at:* 23 Jan at 11:19 UTC

*Location:* SE, Stockholm County, Stockholm
*Browser:* Chrome 87.0.4280.88

*OS:* macOS 10.15.7
*Screen:* 1792x1120
*Viewport:* 1792x1022

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/xnrb49302apcc2sxmjkh/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTE0MDA3NTYsImRhdGEiOnsicmVwb3J0IjoieG5yYjQ5MzAyYXBjYzJzeG1qa2giLCJ1c2VyIjoiR2l0SHViIn19.Ma3sMQBwMSIiwwHggO8GX-ZPAFqlHfSaYAUyFAE4Bm4)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/xnrb49302apcc2sxmjkh](https://ybug.io/dashboard/reports/detail/xnrb49302apcc2sxmjkh)

**Comment by creed-victor** [comment]
@kayalight You also marked BPRO, was that a mistake?
Btw we don't have CSOV and SOV icons

**Comment by kayalight** [comment]
yes were provided with sov icon in the file
