### ISSUE TITLE
if i place a lev trade in BTC, the result Liquidate Position should be BTC, not DoC. I almost accidentally closed in a stablecoin I really don't want.

### ISSUE THREAD

**Issue by ororopickpocket** [DistributedCollective/Sovryn-frontend#275]
![liqpos](https://user-images.githubusercontent.com/69456639/105626047-cbc29b80-5e2d-11eb-995c-50638560652f.png)

**Comment by soulBit** [comment]
Closing as new UI should make it more obvious how to get required asset
