### ISSUE TITLE
Why show Lend and Borrow tabs window before the user click on the specific asset?

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#285]
Hi,

Why show Lend and Borrow tabs window before the user click on the specific asset?
I think the Lend and Borrow tabs should only appear if the user click on the asset window. And the Lend and Borrow tabs should appear below the asset window that I clicked. Now appear at the bottom of the page. Doesn't make sense.

See the way it works now:

![photo_2021-01-24_19-29-13](https://user-images.githubusercontent.com/1178856/105645832-f5ee7a80-5e7a-11eb-808c-29d184c144b8.jpg)

**Comment by creed-victor** [comment]
Hey,

Actually selection is BTC by default.
Currently dapp has very poor support for mobile, so yes it looks very strange when form is bellow everything, but new design is incoming.
