### ISSUE TITLE
Connected wallet show Loading message on Top-up history but shouldn't

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#286]
Hi,

I already connected a wallet and I don't have any incoming transaction on Top-up history. I think the message Loading doesn't make sense when the wallet is already connected and there's no incoming transaction.
Should be: No Top-up transaction found.

![Captura de tela de 2021-01-24 20-08-00](https://user-images.githubusercontent.com/1178856/105647323-8fba2580-5e83-11eb-9efd-737023187634.png)

**Comment by creed-victor** [comment]
Hey,

It's because on top-up system is disabled now on mainnet right now.
