### ISSUE TITLE
Shouldn't each `loanId` be unique?

### ISSUE THREAD

**Issue by jjmr007** [DistributedCollective/Sovryn-frontend#289]
**Describe the bug**
I have compared several `marginTrade` transactions and all of them has the same value for `loanId`parameter, zero.

**To Reproduce**

1. Inspect the contract transactions of iUSD contract: https://blockscout.com/rsk/mainnet/address/0x849C47F9c259E9D62F289bF1B2729039698D8387/transactions
2. Select any transaction msg.value different to zero; any `marginTrade` transaction
3. Look the value of each `loanId` input
4. All values are bytes32 zero (0x0000000000000000000000000000000000000000000000000000000000000000)

**Expected behavior**
Each `loanId`value should be unique.

Note: if it is confirmed to be a misunderstanding, please ignore this bug report

**Comment by creed-victor** [comment]
Hey @jjmr007, 
Calling margin trade with `loanId` as `0` means that new loan will be opened and smart-contract will assign unique one which will be used later for top-ups, closing position and etc.
So everything is correct here  ;)
