### ISSUE TITLE
User JOR325 opened a 4x position, 5 days later (price $39.000) the profit is shown as $25; 3 days later (price over $40.00) profit is $7,37

### ISSUE THREAD

**Issue by jjmr007** [DistributedCollective/Sovryn-frontend#290]
**Describe the bug**
User JOR325 opens a 4x position at the Tx: https://blockscout.com/rsk/mainnet/tx/0x48328e6a9d1f7dcd0f3d52d2e6ec10479bcb51f47ffaca3f4afcad4931be4b89/token-transfers

1. Initial price: $32.000; APR 1.93%, date 05/01/2021
2. The user inspects his position using the UI 2 days later the position was opened; Price: $39.300; Profit: $25.83, liquidation price: $27.650
3. The user inspects his position using the UI 2 days later the position was opened; Prie: $40.400; Profit: $7.37, liquidation price: $ 29.145
4. Number doesn't fit

**Expected behavior**
The APR shouldn't vary until the rollover date; there is no way to explein the variations on the value of parameters (liquidation price, and profit) observed in the UI.

**Screenshots**

![Jor_prblm](https://user-images.githubusercontent.com/17028457/105802184-084ae000-5f71-11eb-8231-d77955184e76.PNG)

**Comment by creed-victor** [comment]
Transaction was made 21 days ago, @ororopickpocket did contracts already was updated to show aam prices instead of oracle?

**Comment by soulBit** [comment]
Closing as stale
