### ISSUE TITLE
Menu with problem

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#304]
Hi,

![photo_2021-01-27_13-11-38](https://user-images.githubusercontent.com/1178856/106020484-983c7700-60a2-11eb-8450-9eb25bd47409.jpg)

**Comment by bitcoinuser** [comment]
Hi, @pietro-maximoff not fixed here. Tested on test.sovryn.app.

**Comment by pietro-maximoff** [comment]
i've checked here - test.sovryn.app and all screen is black
![IMG_7615](https://user-images.githubusercontent.com/74987028/107518048-9e147b00-6bbf-11eb-8708-4c46e4b8a9ab.PNG)

**Comment by bitcoinuser** [comment]
@pietro-maximoff Please drag the screen up to see if the problem happens for you.

**Comment by pietro-maximoff** [comment]
> @pietro-maximoff Please drag the screen up to see if the problem happens for you.

yeah got it, will fix it soon

**Comment by pietro-maximoff** [comment]
@bitcoinuser Please check again, maybe there was a cache, because now I can't reproduce it

**Comment by bitcoinuser** [comment]
> @bitcoinuser Please check again, maybe there was a cache, because now I can't reproduce it

Same problem here.
