### ISSUE TITLE
[YBUG.IO] Dear Support ....

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#306]
Dear Support ....

I transferred 0.001 BTC January 8 / 2021 to my BTC Wallet on Sovryn, shortly before Deposit was disabled and trading suspended.
When will this be reflected in my wallet ?

2021-01-09 13:30:34
BTC 0.001
Address: https://blockchain.coinmarketcap.com/address/bitcoin/bc1q9e5q0t7ffr8zr8cd5rt026k9t7sv2y87vlghzv94sv39qpu8aeqsh9yxcs

TxID: https://blockchain.coinmarketcap.com/tx/bitcoin/1be9fc757cd798222bc1e993c0d1ea693eadb8b032c6449f164b5f582f9ccf93

Regards Kidd

*Source url:* https://live.sovryn.app/wallet
*Reported by:* jayjaysclub@gmail.com
*Reported at:* 28 Jan at 09:38 UTC

*Location:* CH, Basel-Landschaft, Buckten
*Browser:* Chrome 87.0.4280.141

*OS:* Windows 10.0
*Screen:* 1536x864
*Viewport:* 1536x763

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/2xf537hbw5100scthck8/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTE4MjY2OTYsImRhdGEiOnsicmVwb3J0IjoiMnhmNTM3aGJ3NTEwMHNjdGhjazgiLCJ1c2VyIjoiR2l0SHViIn19.8-zhnarctNeCJPP3i_ADc58_hjWH1_kqA83UCVnDAW4)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/2xf537hbw5100scthck8](https://ybug.io/dashboard/reports/detail/2xf537hbw5100scthck8)

**Comment by jamiemadrox779** [comment]
solved and missing deposit processed
