### ISSUE TITLE
Dapp Origin Pre-Sale Banner

### ISSUE THREAD

**Issue by kayalight** [DistributedCollective/Sovryn-frontend#313]
This is a HTML5 banner to use on the dapp to direct users to the Origin Pre-Sale page

https://drive.google.com/file/d/1M8nf3TftbwwsA0xdZt5lliWHHgUou2mZ/view?usp=sharing

**Comment by creed-victor** [comment]
@kayalight I think file is corrupted, it only has logo, pattern images and some javascript files

**Comment by creed-victor** [comment]
my bad, it's actual banner

**Comment by kayalight** [comment]
I provided it as 1440px so that it should also work for Jamies small laptop?

**Comment by creed-victor** [comment]
Unless it's programatically scaled it will not work well for smaller screens. And most likely it will have issues with animations which will take a lot of time to fix.
It's better to just have different size versions that we would be able to show depending on user screen size

**Comment by kayalight** [comment]
great solution!
please let me know the different widths you require to do it this way and I will get these made for you

**Comment by creed-victor** [comment]
I think these sizes should cover most:
540px, 720px, 960px, 1140px.
1140px and 720px should be ok, maybe 290px too, in case we want to show it for whoever opens dapp with mobile

**Comment by kayalight** [comment]
great I will get these produced for you, it may take a few hours

**Comment by kayalight** [comment]
[index960x90.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/5897961/index960x90.zip)
[index1140x90.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/5897962/index1140x90.zip)
These are what I have until next week.
At some point the message will change and they will need updating

**Comment by creed-victor** [comment]
Ok, will wait for the rest before releasing

**Comment by kayalight** [comment]
https://drive.google.com/file/d/1w77IcZXBpvO9BFw-07zpcdge6gHFcUPe/view?usp=sharing

**Comment by kayalight** [comment]
@creed-victor

**Comment by kayalight** [comment]
we now have another set of banners being made with new message now @creed-victor

**Comment by creed-victor** [comment]
@kayalight maybe we can have one copy first, to test if it'd not killing devices with animations

**Comment by kayalight** [comment]
[banners.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/5911758/banners.zip)

**Comment by kayalight** [comment]
@creed-victor svg banners
