### ISSUE TITLE
(Place trade) button should be (Connect Wallet) when wallet is not connected

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#326]
Hi,

(Place trade) button should be (Connect Wallet) when wallet is not connected. Related to: https://github.com/DistributedCollective/Sovryn-frontend/issues/222

![photo_2021-01-31_18-55-13](https://user-images.githubusercontent.com/1178856/106399279-6b67c700-63f6-11eb-8876-234f3559d047.jpg)

**Comment by creed-victor** [comment]
Flow will be improved with page redesign #346, #354
