### ISSUE TITLE
New Swap UI

### ISSUE THREAD

**Issue by kayalight** [DistributedCollective/Sovryn-frontend#335]
https://drive.google.com/file/d/1dlHyJMqLgz3oAbx51A2eV9f0fZHPQBCE/view?usp=sharing

**Comment by kayalight** [comment]
more is on the way
the pop up for slippage will be done with all the pop ups for trading

**Comment by creed-victor** [comment]
@kayalight currently it's only swap page or file also has and margin trading and I can't just find it?

**Comment by kayalight** [comment]
[trading v1.2.xd.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/5912175/trading.v1.2.xd.zip)
@creed-victor @daisai3 
here is the file with the slippage window for swaps, please note that i changed the size of the text in the rbtc field amount from 18pt to 16pt

I also moved the pagination up slightly

there will be a footer for all pages but that will come with the margin trading pages

**Comment by kayalight** [comment]
@creed-victor @daisai3 in the file I forgot to change the input for the amount to send to this.
please use this style. If you need me to change the file just let me know

<img width="362" alt="Screenshot 2021-02-02 at 15 32 38" src="https://user-images.githubusercontent.com/77350089/106622810-e4d4f600-656b-11eb-8d2a-345b22445cd8.png">

**Comment by daisai3** [comment]
@kayalight , okay.

**Comment by kayalight** [comment]
[trading v1.2.xd.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/5912351/trading.v1.2.xd.zip)
@creed-victor @daisai3 sorry easier to just make the amends and reupload

**Comment by daisai3** [comment]
@kayalight , so this is the final design?

**Comment by kayalight** [comment]
@daisai3 yes my apologies

**Comment by daisai3** [comment]
@kayalight . no worries. 👍

**Comment by kayalight** [comment]
@daisai3 I realise I forgot to add the transaction review window, will upload soon

**Comment by daisai3** [comment]
@kayalight , please let me know once you upload it.

**Comment by kayalight** [comment]
https://youtu.be/mV5MWbzM9yk
[trading v1.2.1.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/5937920/trading.v1.2.1.zip)
@daisai3 
please get in touch with any questions, there are specific transitions settings and timing depending on the action

**Comment by kayalight** [comment]
https://youtu.be/RzsqhrSAfzM
[trading v1.2.1.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/5937948/trading.v1.2.1.zip)
@daisai3 please get in touch about transitions, there are different parameters for different cases

**Comment by daisai3** [comment]
@kayalight , could you share me this image asset?
![7](https://user-images.githubusercontent.com/42278459/107403389-674f4e00-6b48-11eb-8048-7746bca89dbd.png)

**Comment by kayalight** [comment]
[swap_horiz-24px.svg.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/5955272/swap_horiz-24px.svg.zip)
@daisai3

**Comment by daisai3** [comment]
@kayalight , thanks for sharing the assets.
I've some questions about the design.
1) Where I can find the logo on the header?
2) The slippage modal is shown when 'gear icon' is clicked?

**Comment by t-z-u** [comment]
<img width="1570" alt="Screenshot 2021-04-23 at 15 33 31" src="https://user-images.githubusercontent.com/79344165/115886970-5a54b200-a449-11eb-9c98-453384abd530.png">
The history does not show in order correctly, seems like the top one is fixed

**Comment by t-z-u** [comment]
optimize for use on mobile

**Comment by t-z-u** [comment]
https://xd.adobe.com/view/69436a68-ff42-4803-7f5d-11a6640108e7-1f72/
[Swap V2.1.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/6424082/Swap.V2.1.zip)
@tiltom if it has not been done already please update the components to reflect this design

**Comment by t-z-u** [comment]
https://xd.adobe.com/view/69436a68-ff42-4803-7f5d-11a6640108e7-1f72/
[Swap V2.1.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/6424147/Swap.V2.1.zip)

@tiltom @soulBit can you please make the send and receive sections pixel perfect

**Comment by tiltom** [comment]
I will take a look at it @t-z-u since I am working on it now. 

Btw - do we have some design for the mobile version, or should I just do my best effort and send you testnet link?

**Comment by t-z-u** [comment]
<img width="1792" alt="Screenshot 2021-05-05 at 16 27 22" src="https://user-images.githubusercontent.com/79344165/117167034-d1316980-adbe-11eb-9bce-bde9e2880dbb.png">
@tiltom please make sure that this is impossible to happen
I suggest taking the current sending asset out of the receiving dropdown

**Comment by tiltom** [comment]
Ok I will take a look at it @t-z-u .
