### ISSUE TITLE
Redeem RBTC and convert CSOV

### ISSUE THREAD

**Issue by kayalight** [DistributedCollective/Sovryn-frontend#341]
[CSOV-SOV.xd.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/5911898/CSOV-SOV.xd.zip)

**Comment by kayalight** [comment]
Hi victor,

here are the windows so that users can get back their rbtc or convert their csov

they would get to these modals by going to my wallet and clicking on the buttons "Redeem rBTC" and "Convert to SOV" on the CSOV line in the wallet

**Comment by kayalight** [comment]
@creed-victor

**Comment by creed-victor** [comment]
@kayalight I believe these fields are not inputs and will just show how many user will convert?

As for Redeem rBTC dialog, maybe it should be cSOV -> rBTC instead of rBTC -> rBTC?

**Comment by kayalight** [comment]
yes you are correct these are not inputs

ah good point let me update that and will send new file with the correct buttons

**Comment by kayalight** [comment]
actually @creed-victor i think there are some edge cases where users did not receive CSOV, so leaving it like this covers both cases
this is the file with correct button style

[CSOV-SOV.xd.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/5912042/CSOV-SOV.xd.zip)

**Comment by kayalight** [comment]
@creed-victor I will confirm that with ororo

**Comment by kayalight** [comment]
[CSOV-SOV.xd.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/5912162/CSOV-SOV.xd.zip)
Havent heard from ororo but think you are correct on this so have updated the file accordingly

**Comment by kayalight** [comment]
@creed-victor
