### ISSUE TITLE
Margin Trading interface

### ISSUE THREAD

**Issue by kayalight** [DistributedCollective/Sovryn-frontend#346]

**Comment by kayalight** [comment]
@creed-victor 
[trading v1.3.xd.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/5918115/trading.v1.3.xd.zip)

**Comment by kayalight** [comment]
Best to have a quick 5 min call before you start on this @creed-victor

**Comment by kayalight** [comment]
@creed-victor I just noticed that the cta's on an open trade have the wrong font. It is work sans in the file. Please use Montserrat, apologies for this mistake

**Comment by kayalight** [comment]
[trading v1.4.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/5927367/trading.v1.4.zip)

this is updated after speaking with ororo 
there are also some very slight design changes

**Comment by t-z-u** [comment]
https://xd.adobe.com/view/f742b57d-92fc-44b4-4f93-49ade24a3795-8173/
[Margin Trade V2.0.xd.zip](https://githu@soulBit stributedCollective/Sovryn-frontend/files/6414149/Margin.Trade.V2.0.xd.zip)
@soulBit these should address the users feedback and have a little tidy up

**Comment by tiltom** [comment]
rUSDT rename done in https://github.com/DistributedCollective/Sovryn-frontend/pull/1025
