### ISSUE TITLE
[YBUG.IO] The layout before the last...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#353]
The layout before the last redesign was easier to  use, from my point of view. Earlier, the main menu was always visible,  now it pops up and suddenly covers the entire screen. Also,  I didn't find how to engage my wallet in the new design at first.

*Source url:* https://live.sovryn.app/wallet
*Reported by:* 
*Reported at:* 03 Feb at 21:18 UTC

*Location:* DE, Hamburg, Hamburg
*Browser:* Chrome 87.0.4280.141

*OS:* Windows 7
*Screen:* 1280x800
*Viewport:* 1107x663

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/sn1ry7nr62aqbyktk2h2/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTIzODcxMzcsImRhdGEiOnsicmVwb3J0Ijoic24xcnk3bnI2MmFxYnlrdGsyaDIiLCJ1c2VyIjoiR2l0SHViIn19.80mfiNYq1Z-jrZ6a8i7nRlkh7HT_M_UbdzwA9VQopJw)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/sn1ry7nr62aqbyktk2h2](https://ybug.io/dashboard/reports/detail/sn1ry7nr62aqbyktk2h2)

**Comment by kayalight** [comment]
@creed-victor why is it doing this?

**Comment by soulBit** [comment]
@t-z-u issue here is that Engage Wallet button turns invisible < 1200px screen width, and then is completely removed when width < 768px
