### ISSUE TITLE
[YBUG.IO] letters do not come to my mail....

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#358]
letters do not come to my mail. and writes that the wallet is not registered. How do i buy coins?

*Source url:* https://live.sovryn.app/
*Reported by:* vitalikorlov.iwowwe@gmail.com
*Reported at:* 05 Feb at 21:58 UTC

*Location:* RU, Kaluga Oblast, Kaluga
*Browser:* Chrome 88.0.4324.104

*OS:* Windows 7
*Screen:* 1024x768
*Viewport:* 997x579

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/6xynh60awyjn21qbn7bv/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTI1NjIzMTYsImRhdGEiOnsicmVwb3J0IjoiNnh5bmg2MGF3eWpuMjFxYm43YnYiLCJ1c2VyIjoiR2l0SHViIn19.ILIHaHWkCdY_-4_d5qsXM7kP_9ZDuRLNqq1XXT5Khec)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/6xynh60awyjn21qbn7bv](https://ybug.io/dashboard/reports/detail/6xynh60awyjn21qbn7bv)

**Comment by soulBit** [comment]
Closing this as wallet whitelisting has been removed
