### ISSUE TITLE
I opened a 5X short position that I think should have been liquidated, but was not

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#359]
Hi,

I opened a 5X short position that I think should have been liquidated, but was not

![Captura de tela de 2021-02-06 14-31-37](https://user-images.githubusercontent.com/1178856/107125469-fd555100-6888-11eb-9c27-5d96970b0644.png)

**Comment by creed-victor** [comment]
@jamiemadrox779 do you think liquidation price is wrong here or liquidation watcher doesn't do it's job?

**Comment by bitcoinuser** [comment]
I closed the position and the loss was 6.70 dollars. But the loss was different from the moment I closed the position. The moment I closed was 1.47 dollars.

![Captura de tela de 2021-02-08 11-03-09](https://user-images.githubusercontent.com/1178856/107230406-d10f1100-69fd-11eb-8037-108a34ea1e7f.png)

**Comment by creed-victor** [comment]
> I closed the position and the loss was 6.70 dollars. But the loss was different from the moment I closed the position. The moment I closed was 1.47 dollars.

@bitcoinuser did that position had some top-ups or partial withdrawals? or just opened and closed later without any additional actions?

**Comment by jamiemadrox779** [comment]
> @jamiemadrox779 do you think liquidation price is wrong here or liquidation watcher doesn't do it's job?

liquidation starts at 15% margin, not 18%

**Comment by bitcoinuser** [comment]
> or just opened and closed later without any additional actions

This.
