### ISSUE TITLE
After integrated the new cSOV token, token balances are not shown... It might be necesary a distinction between old and new cSOV tokens

### ISSUE THREAD

**Issue by jjmr007** [DistributedCollective/Sovryn-frontend#360]
**Describe the bug**
The user @matu is inspecting the balance of their assets in the sovryn "MyWallet" tab... but his cSOV are not shown
**To Reproduce**
If you're a user with a deposit of new cSOV tokens, and inspect in "MyWallet" tab of the UI, the balance should appear

**Expected behavior**
MyWallet should show the balance of cSOV tokens regardless if they are the new or the old ones

**Screenshots**
see below

**Desktop :**
Browser: Chrome, 
Windows 10

![error_mywallet_sovryn_dapp_2](https://user-images.githubusercontent.com/17028457/107129790-6dba9d00-689e-11eb-9e5f-96472a8d6712.png)

**Comment by jjmr007** [comment]
The user must try the following:

Likely the user is using cached (older) version of the dapp/UI - he needs to refresh his browser, and when refreshing, only one tab of the dapp can be opened (and no more than one), user will be prompted with a blue dialog asking to update dapp version then.

**Comment by t3st3r123** [comment]
Hi, this is matu#2113 

Here's some additional info.
- I did see CSOV (version 2) in Sovryn wallet earlier after those were sent
- After the recent update of dapp, Sovryn wallet no longer showed the correct balance

- Tested above suggested refresh and one tab (by jjmr007) - no change.
- Tested with Brave browser and Nifty Wallet with same results: CSOV visible in Web Wallet, but not Sovryn wallet
- Tested to back up my wallet from Windows to MAC:
1) Backed up my wallet to MAC (Big Sur) from my Windows 10 machine.
2) Used same setup as before with Chrome and Liquality Web Wallet
3) CSOV (V2) is visible in my web wallet, but not in Sovryn wallet (My Wallet UI) 

- Other users in TG and Discord are reporting similar behavior, so this is not an isolated issue

Thanks.

**Comment by creed-victor** [comment]
Ok, there was indeed a bug should be fixed now (user will need to refresh first).

**Comment by t3st3r123** [comment]
Yes, working now.  Thanks!
