### ISSUE TITLE
Add visible version number (git commit id) to app

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#362]
Adding a visible version number somewhere on the app will help debugging issues where the user has not updated to the latest version - e.g:

"Hi, I have a problem.  I want to send BTC to sovryn app, when I go to Fast-BTC-Relay I see the following message:
Address is empty. Anyone who can help me? Thanks"

**Comment by creed-victor** [comment]
Yes, was thinking about too.
I think adding git commit id to footer and console log should do the trick.

**Comment by soulBit** [comment]
@creed-victor good idea! I'll take a stab at this when I have some time this week and get you to review

**Comment by creed-victor** [comment]
> @creed-victor good idea! I'll take a stab at this when I have some time this week and get you to review

Just a note that git commit id should be retrieved in webpack config file and assigned to env variable, maybe something like `REACT_APP_GIT_COMMIT_ID` and printing it in dev console (maybe even from public/index.html file in case react app crashes) and also somewhere in the footer. 
Footer version may even be a hyperlink and open commit in the github when clicked.

**Comment by soulBit** [comment]
@creed-victor Thanks for the pointers, I originally had it copying the commit id to clipboard on click, but your idea is better :)

I'm not sure if the method I'm using to get the commit id in webpack.config,js is optimal, can you check that for me - if there's a way to do it without the package I installed, let's go for that! Same goes for the console.log in public/index.html, I couldn't access the env var with %GIT_COMMIT_ID% like I expected, I assume because it's not loaded from a .env and created by webpack?

If the commit id on the footer is too obtrusive we could also just show the first 7 characters like Github does.
