### ISSUE TITLE
need to disable button when user has clicked

### ISSUE THREAD

**Issue by kayalight** [DistributedCollective/Sovryn-frontend#375]
user is able to keep pressing close position which activates the browser wallet with a new transaction to confirm

**Comment by kayalight** [comment]
<img width="513" alt="Screenshot 2021-02-11 at 10 35 07" src="https://user-images.githubusercontent.com/77350089/107626281-75d75b80-6c55-11eb-8ab6-af27aa92e569.png">

**Comment by creed-victor** [comment]
I believe this dialog will be changed with new one? It renders issue as invalid

**Comment by creed-victor** [comment]
btw, do not add assignees to issues unless it's certain that it should assigned otherwise collaborators will not take these issues as it means that someone already working on it
