### ISSUE TITLE
[YBUG.IO] logo not visible on tab when...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#381]
logo not visible on tab when dark title bas

*Source url:* https://live.sovryn.app/wallet
*Reported by:* 
*Reported at:* 14 Feb at 18:00 UTC

*Location:* VE, Aragua, Maracay
*Browser:* Firefox 84.0

*OS:* Linux unknown
*Screen:* 1366x768
*Viewport:* 1366x667

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/ngfg4km55xx29z9c57jt/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTMzMjU2NDYsImRhdGEiOnsicmVwb3J0IjoibmdmZzRrbTU1eHgyOXo5YzU3anQiLCJ1c2VyIjoiR2l0SHViIn19.wHZLg1xLf3DZwOIEdi2s_IYG1su3lE9QtGTCCnrcaIU)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/ngfg4km55xx29z9c57jt](https://ybug.io/dashboard/reports/detail/ngfg4km55xx29z9c57jt)

**Comment by creed-victor** [comment]
@kayalight any idea what reporter meant by this here?

> logo not visible on tab when dark title bas

**Comment by kayalight** [comment]
@creed-victor no idea at all

**Comment by creed-victor** [comment]
Closing then
