### ISSUE TITLE
Switch bootstrap with tailwindcss

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#388]
Tailwind makes it easier to define custom classes and purge unused classes than bootstrap which means we will have smaller builds.

- [x] configure webpack to use tailwindcss
- [x] make sure hot reloading works when css file is changed
- [x] redesign components using tailwindcss classes instead of bootstrap
- [ ] deprecate bootstrap

Configuration already available at feat/redesign branch

**Comment by soulBit** [comment]
@creed-victor I can see references to Bootstrap components in a few places (e.g. Button/Nav/Tab are used in ButtonGroup and LendingContainer), are we planning to keep these? I'll close this ticket if so

**Comment by creed-victor** [comment]
> @creed-victor I can see references to Bootstrap components in a few places (e.g. Button/Nav/Tab are used in ButtonGroup and LendingContainer), are we planning to keep these? I'll close this ticket if so

No, all bootstrap components and code should be removed and tailwindcss used instead

**Comment by ShynRou** [comment]
@soulBit currently bootstrap itself is still imported and react-bootstrap components are still used.

```
src/app/containers/LiquidityPage/index.tsx:
  8: import { Tab, Tabs } from 'react-bootstrap';

src/app/pages/BorrowPage/index.tsx:
  2: import { Container } from 'react-bootstrap';

src/app/pages/BorrowPage/components/ButtonGroup/index.tsx:
  2: import { Button, Nav, Tab } from 'react-bootstrap';

src/app/pages/BorrowPage/components/CurrencyContainer/index.tsx:
  2: import { Container, Nav, Tab } from 'react-bootstrap';

src/app/pages/BorrowPage/components/LendingHistory/index.tsx:
  2: import { Collapse, Table } from 'react-bootstrap';

src/app/pages/LendingPage/components/CurrencyContainer/index.tsx:
  2: import { Container } from 'react-bootstrap';

src/styles/sass/styles.scss:
  10: @import '~bootstrap/scss/bootstrap';
```
