### ISSUE TITLE
Input components

### ISSUE THREAD

**Issue by kayalight** [DistributedCollective/Sovryn-frontend#396]

**Comment by kayalight** [comment]
[Components - input fields.xd.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/6004311/Components.-.input.fields.xd.zip)
Hi @creed-victor didnt want to block you so will send over pages since it is also split up in here

**Comment by creed-victor** [comment]
Progress

- [x] basic input
- [ ] read-only input
- [ ] input with bottom text
