### ISSUE TITLE
ETH Bridge interface

### ISSUE THREAD

**Issue by t-z-u** [DistributedCollective/Sovryn-frontend#429]

**Comment by t-z-u** [comment]
[eth bridge v1.1.zip](https://githu@creed-victor com/DistributedCollective/Sovryn-frontend/files/6049277/eth.bridge.v1.1.zip)
@creed-victor 
https://youtu.be/nH2KsQ-P7Po
please reach out with any questions
I will work on the gif animations for the window (mm and liquality)

**Comment by creed-victor** [comment]
Duplicate of #422

**Comment by creed-victor** [comment]
> [eth bridge v1.1.zip](https://githu@creed-victor com/DistributedCollective/Sovryn-frontend/files/6049277/eth.bridge.v1.1.zip)
> @creed-victor
> https://youtu.be/nH2KsQ-P7Po
> please reach out with any questions
> I will work on the gif animations for the window (mm and liquality)

download link somehow is broken
