### ISSUE TITLE
If I scroll down the window using scroll bar from browser, the Top Up window disappear

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#442]
Hi,

If I scroll down the window using scroll bar from browser, the Top Up window disappear. I'm only able to scroll down using keyboard.

![Captura de tela de 2021-03-03 16-44-19](https://user-images.githubusercontent.com/1178856/109863256-2ecefb80-7c40-11eb-9205-83ea329feea7.png)

**Comment by creed-victor** [comment]
Got it. Click-outside to close functionality should be disabled and close button "X" added.

**Comment by bitcoinuser** [comment]
Hi @soulBit @creed-victor , thanks for the fix. The same problem happens here:

![Captura de tela de 2021-03-11 11-29-32](https://user-images.githubusercontent.com/1178856/110802898-656ace80-825d-11eb-9481-a4f4d8325a79.png)

**Comment by soulBit** [comment]
Thanks @bitcoinuser, I've added a new ticket in the bitocracy repo for this one
