### ISSUE TITLE
[YBUG.IO] I participated in the Origin...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#448]
I participated in the Origin Presale 0.0445 BTC with SOV receiving RSK wallet : 0xa92f3F5B61625faf8C1D25dbFd96F00Ca7F137Cf. Why it is not whitelisted? I can't claim my SOV please help!!

*Source url:* https://live.sovryn.app/wallet
*Reported by:* natakorn.ar@gmail.com
*Reported at:* 06 Mar at 01:52 UTC

*Location:* TH, Bangkok, Bangkok
*Browser:* Chrome 88.0.4324.190

*OS:* Windows 10.0
*Screen:* 1920x1080
*Viewport:* 1920x937

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/93zzyn4rqzh9xz49t39y/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTQ5OTU1NDAsImRhdGEiOnsicmVwb3J0IjoiOTN6enluNHJxemg5eHo0OXQzOXkiLCJ1c2VyIjoiR2l0SHViIn19.FaoZX2-aYi4xqEQpEu-6Xrn8YQYdW4yNs4aH-ag22-0)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/93zzyn4rqzh9xz49t39y](https://ybug.io/dashboard/reports/detail/93zzyn4rqzh9xz49t39y)

**Comment by soulBit** [comment]
Closing this as whitelisting has been removed
