### ISSUE TITLE
[YBUG.IO] bro its not allowing my metamask...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#468]
bro its not allowing my metamask to connect...

*Source url:* https://live.sovryn.app/wallet
*Reported by:* 
*Reported at:* 11 Mar at 05:53 UTC

*Location:* US, Texas, El Paso
*Browser:* Chrome 88.0.4324.190

*OS:* Windows 10.0
*Screen:* 1536x864
*Viewport:* 1536x799

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/8zzwkvg3xzphkk43spph/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTU0NDE5OTUsImRhdGEiOnsicmVwb3J0IjoiOHp6d2t2ZzN4enBoa2s0M3NwcGgiLCJ1c2VyIjoiR2l0SHViIn19.Iw4SYdtri6V1tnmMWWoSF1QzrDqcDoSeB8oJQJvGw18)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/8zzwkvg3xzphkk43spph](https://ybug.io/dashboard/reports/detail/8zzwkvg3xzphkk43spph)

**Comment by soulBit** [comment]
Issue appears to be resolved with latest wallet connecter/flow
