### ISSUE TITLE
[YBUG.IO] No liquidity in USDT to close my...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#474]
No liquidity in USDT to close my short. And when I switch to BTC, the amount does not update.

*Source url:* https://live.sovryn.app/
*Reported by:* 
*Reported at:* 14 Mar at 20:23 UTC

*Location:* IL, Tel Aviv, Tel Aviv
*Browser:* Chrome 89.0.4389.82

*OS:* macOS 10.15.7
*Screen:* 1680x1050
*Viewport:* 1680x945

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/tqydv9g2ccd5gqxjb557/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTU3NTM0MzUsImRhdGEiOnsicmVwb3J0IjoidHF5ZHY5ZzJjY2Q1Z3F4amI1NTciLCJ1c2VyIjoiR2l0SHViIn19.XixLhphJYvjeihFM7JlSGsF_Dy9esWpnf2nzSBSZnbk)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/tqydv9g2ccd5gqxjb557](https://ybug.io/dashboard/reports/detail/tqydv9g2ccd5gqxjb557)

**Comment by soulBit** [comment]
Users second point is working as intended, the amount isn't meant to be in BTC
