### ISSUE TITLE
Some users aren't able to query their closed margin positions

### ISSUE THREAD

**Issue by jjmr007** [DistributedCollective/Sovryn-frontend#480]
**Describe the bug**
After some users closing a margin position, like these transactions:

https://explorer.rsk.co/tx/0xb29a2246389dae4f01864707a6e8e5f84e323aa28c8cd6e6074770a7ac88410f

or 

https://explorer.rsk.co/tx/0xe51cf4bc8fe331c099765ccb82b2f27438dc26f26545bd395b1ba98ff2eafef5

they were unable to see their closed positions in the history of the UI: live.sovryn.app
so they couldn't see at which price their positions closed.

**To Reproduce**

1. Go to 'live.sovryn.app'
2. Open a long position (no reports of users having issues about short positions)
3. Wait some days, and close the position
4. Oftenly the trade board doesn't shows the closed position to query the close price.

**Expected behavior**
You should be able to see a list of all your closed positions. But what you have is this experience
![NO_CLOSED](https://user-images.githubusercontent.com/17028457/111644450-3c56ba80-87d6-11eb-860e-413cc94cb734.PNG)

**Desktop (please complete the following information):**

Brave: Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)
Windows 10 Pro: Release 20H2

**Comment by soulBit** [comment]
Closing as resolved with new history
