### ISSUE TITLE
Rename Lend/Borrow to Loans

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#485]
Hi,

I think the button Lend/Borrow should be renamed to Loans.

Why?
Because when translating Lend/Borrow to Portuguese, the string stay very long and it's "ugly". Will be Emprestar/Tomar Empréstimo.

![Captura de tela de 2021-03-20 12-37-48](https://user-images.githubusercontent.com/1178856/111876307-fbe57100-897c-11eb-9af7-8c8534502cc0.png)

**Comment by creed-victor** [comment]
Yep, totally makes sense
