### ISSUE TITLE
New menu for dapp

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#492]
Hi,

I think Sovryn could have top buttons like Binance page. On Binance, the user hover the mouse on the button and appear other options.
For example on Sovryn we have Market Maker and Lend / Borrow. I think should be just one button called Finance that when the user hover the mouse appear more options like Market Maker, Lend, Borrow and with each option a little description. See the example here:

![Captura de tela de 2021-03-21 17-37-05](https://user-images.githubusercontent.com/1178856/111920330-1a2a9a00-8a6d-11eb-8550-f041676d4105.png)
 
Related to https://github.com/DistributedCollective/Sovryn-frontend/issues/485

**Comment by t-z-u** [comment]
[new menu.xd.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/6270848/new.menu.xd.zip)

**Comment by t-z-u** [comment]
[new menu.xd.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/6271120/new.menu.xd.zip)

**Comment by t-z-u** [comment]
<img width="1029" alt="Screenshot 2021-04-09 at 14 25 54" src="https://user-images.githubusercontent.com/79344165/114187167-99f6a680-993f-11eb-8bb9-481e43b5436d.png">

**Comment by t-z-u** [comment]
please note that "buy btc" in the file is now is now "buy SOV"

**Comment by bitcoinuser** [comment]
I think this improvement should be done together with https://github.com/DistributedCollective/Sovryn-frontend/pull/614, because for now, with Buy SOV option on menu, on PT-BR language, there's no space and stay strange as you can see here:

![Captura de tela de 2021-04-11 10-45-39](https://user-images.githubusercontent.com/1178856/114306972-0eeaed00-9ab4-11eb-8284-dac35a46feaf.png)

**Comment by t-z-u** [comment]
It should be being worked on for this release

**Comment by bitcoinuser** [comment]
![image](https://user-images.githubusercontent.com/1178856/114307862-ebc23c80-9ab7-11eb-9d11-9e53002f4873.png)

I think Staking should be inside the Finance button, together with Lend, Borrow and Liquidity. And I think should have a button called Sovryn and inside it should have Governance and Stats.

**Comment by t-z-u** [comment]
@bitcoinuser please see the design added to this 2 days ago that is what is being made
