### ISSUE TITLE
[YBUG.IO] i cant seem to claim my origin...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#547]
i cant seem to claim my origin sov, just shows 0 as amount to claim when i press withdraw and cant enter an amount manually

*Source url:* https://live.sovryn.app/wallet
*Reported by:* julianvanmarle@gmail.com
*Reported at:* 29 Mar at 13:15 UTC

*Location:* GB, England, Walthamstow
*Browser:* Chrome 89.0.4389.90

*OS:* Windows 10.0
*Screen:* 2048x1152
*Viewport:* 2048x1042

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/n432vak1rhd0pvwrymy9/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTcwMjM3MjEsImRhdGEiOnsicmVwb3J0IjoibjQzMnZhazFyaGQwcHZ3cnlteTkiLCJ1c2VyIjoiR2l0SHViIn19.0MHIovjZ02Zjnync5Gaj-8VO_ZM0_q8woiaUGvwhA-c)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/n432vak1rhd0pvwrymy9](https://ybug.io/dashboard/reports/detail/n432vak1rhd0pvwrymy9)

**Comment by soulBit** [comment]
Closing as this should be resolved with latest smart contract fixes
