### ISSUE TITLE
Upgrade lightweight chart to Tradingview analysis chart

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#559]
https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/?feature=technical-analysis-charts

**Comment by t-z-u** [comment]
@soulBit hows this going?

**Comment by soulBit** [comment]
@t-z-u Armando sent the signed license agreement over to Tradingview last week, but we haven't heard back from them yet. Once they give us access to the code and docs I can start the implementation, it should only take a couple of days to integrate into the dapp

**Comment by soulBit** [comment]
Access has been granted, will be working on it this week

**Comment by soulBit** [comment]
@creed-victor library files are here:
[Sovryn-frontend_charting_library_files.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/6416806/Sovryn-frontend_charting_library_files.zip)
