### ISSUE TITLE
[YBUG.IO] This part is still the most...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#563]
This part is still the most confusing page. I've supplied RBTC to the USDT pool and see my balance displayed as supplied but I can't see anything else happening.

On the loans tab I can see the numbers moving on the profit section so I know something is happening.

Love the new stats page, keep it up!

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* 
*Reported at:* 01 Apr at 13:53 UTC

*Location:* US, California, Anaheim
*Browser:* Chrome 89.0.4389.105

*OS:* macOS 11.2.3
*Screen:* 1440x900
*Viewport:* 1392x757

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/j6k0j32vfgktpf8rh0tm/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTcyODUyNDIsImRhdGEiOnsicmVwb3J0IjoiajZrMGozMnZmZ2t0cGY4cmgwdG0iLCJ1c2VyIjoiR2l0SHViIn19.yjerSB79nsF7-WxAmzyu-eupxd7FJRgkI8EwS1wschg)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/j6k0j32vfgktpf8rh0tm](https://ybug.io/dashboard/reports/detail/j6k0j32vfgktpf8rh0tm)

**Comment by soulBit** [comment]
Closing this as already in roadmap
