### ISSUE TITLE
I'm confused with different limits

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#564]
Hi,

I'm confused with different limits

![Captura de tela de 2021-04-01 11-07-06](https://user-images.githubusercontent.com/1178856/113306612-a98c4480-92da-11eb-8ea9-d38b5a73ee3a.png)

**Comment by creed-victor** [comment]
Looks, like 0.01 is harcoded here, should be retrieved from backend like min / max values.
