### ISSUE TITLE
[YBUG.IO] connected my liquality wallet......

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#572]
connected my liquality wallet... rSK ONLY settings.. genrated deoposit address from top up button... copy pasted into Liquality withdrew my BTC .... and BTC arrived in my wallet instead of RBTC... help
  \#1. I SENT BTC FROM LIQUALITY WALLET  TO GENERATED ADDRESS FROM TOP UP... I WAITED.... THEN I SEE BTC IN SOVRYN APP INSTEAD OF RBTC... what did i do wrong?\

*Source url:* https://live.sovryn.app/wallet
*Reported by:* k.orozco6@gmail.com
*Reported at:* 02 Apr at 03:17 UTC

*Location:* US, California, La Crescenta
*Browser:* Chrome 89.0.4389.114

*OS:* macOS 10.13.6
*Screen:* 1920x1080
*Viewport:* 1920x969

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/xt5m5a2a9a299ccnwhwm/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTczMzM0ODMsImRhdGEiOnsicmVwb3J0IjoieHQ1bTVhMmE5YTI5OWNjbndod20iLCJ1c2VyIjoiR2l0SHViIn19.fPAxScYxxmi7sfWqIyORJkXmFHjGaDH5GIoYhFew-Q8)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/xt5m5a2a9a299ccnwhwm](https://ybug.io/dashboard/reports/detail/xt5m5a2a9a299ccnwhwm)

**Comment by soulBit** [comment]
Labelling for `BTC` is now consistently shown as `rBTC`
