### ISSUE TITLE
[YBUG.IO] Please add APY% based on Pool! ty

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#573]
Please add APY% based on Pool! ty

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* 
*Reported at:* 02 Apr at 17:39 UTC

*Location:* US, Florida, Lake Worth
*Browser:* Chrome 89.0.4389.105

*OS:* macOS 10.15.5
*Screen:* 1440x900
*Viewport:* 1440x793

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/qqxsvvr1fsgm19bkatk4/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTczODUyMDgsImRhdGEiOnsicmVwb3J0IjoicXF4c3Z2cjFmc2dtMTlia2F0azQiLCJ1c2VyIjoiR2l0SHViIn19.5-RC_dJ3TsFUlcra32E2vg963g62E0SWnmeXDooPzro)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/qqxsvvr1fsgm19bkatk4](https://ybug.io/dashboard/reports/detail/qqxsvvr1fsgm19bkatk4)

**Comment by soulBit** [comment]
Closing as this is already in roadmap
