### ISSUE TITLE
Fastbtc window could have a larger width (So no need to scroll down to see information)

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#581]
Hi,

Fastbtc window could have a larger width (So no need to scroll down to see information)

![Captura de tela de 2021-04-04 14-56-08](https://user-images.githubusercontent.com/1178856/113517577-1dd31c00-9557-11eb-83ff-a6be7ef01a4c.png)

**Comment by t-z-u** [comment]
@creed-victor I believe this happens because we merged "deposit" (fastbtc) and "buy" (transact)
