### ISSUE TITLE
Option to buy assets (crypto) using fiat or depositing BTC should be on top menu too

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#583]
Hi,

I see a lot of people that don't know yet that is possible to buy RBTC with fiat or depositing BTC because it's hard to find it. I think the option to buy assets (crypto) using fiat or depositing BTC should be on top menu too. In my opinion the option to buy with fiat, should allow not only RBTC but the other assets listed on Sovryn too.

Something like Binance page:

![Captura de tela de 2021-04-04 17-46-26](https://user-images.githubusercontent.com/1178856/113521227-79f56a80-956e-11eb-8d49-1b64a060c235.png)

Related to: https://github.com/DistributedCollective/Sovryn-frontend/issues/492

**Comment by t-z-u** [comment]
Yes I agree with you this would be a good place to host this. I don't know when it will be possible to buy other assets with fiat too.
