### ISSUE TITLE
[YBUG.IO] Hi - Today I received a pop up...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#588]
Hi - Today I received a pop up saying 'Your wallet is not authorised to use the Sovryn Dapp'.  This is the first time I have seen this.  Could you clarify why I am getting this pop up? I have followed the instructions and have engaged my Meta Wallet onto the RSK Mainnet.  I have also been providing rBTC liquidity through this wallet, so not sure to understand.  Can you confirm why that would be the case? Am I still authorised to engage in Market-Making (the pop up did not appear on the Market-Making page, just the 'Trade' and 'Loans' page)? Want to make sure I am still eligible to potentially receive SOV tokens! Feel free to reach out to me by email.

Thanks

*Source url:* https://live.sovryn.app/lend
*Reported by:* mlb999@gmail.com
*Reported at:* 05 Apr at 19:27 UTC

*Location:* US, New York, New York
*Browser:* Chrome 89.0.4389.90

*OS:* macOS 10.12.2
*Screen:* 1280x800
*Viewport:* 1280x660

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/yzb68n9cn0c3w8tfrc1z/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTc2NTA4OTQsImRhdGEiOnsicmVwb3J0IjoieXpiNjhuOWNuMGMzdzh0ZnJjMXoiLCJ1c2VyIjoiR2l0SHViIn19.Z_AvmvwRoikBzs1xqRJDWGo503ue0m7hDVHT9Ot7p9o)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/yzb68n9cn0c3w8tfrc1z](https://ybug.io/dashboard/reports/detail/yzb68n9cn0c3w8tfrc1z)

**Comment by soulBit** [comment]
Closing this as whitelisting is now removed
