### ISSUE TITLE
[YBUG.IO] SOV asset would be nice to have...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#592]
SOV asset would be nice to have in My Wallet.

*Source url:* https://live.sovryn.app/wallet
*Reported by:* 
*Reported at:* 06 Apr at 12:05 UTC

*Location:* FI, Uusimaa, Helsinki
*Browser:* Chrome 89.0.4389.114

*OS:* Windows 10.0
*Screen:* 1536x864
*Viewport:* 1536x722

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/8bdgfkhrh29k7t377v89/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTc3MTA3NTUsImRhdGEiOnsicmVwb3J0IjoiOGJkZ2ZraHJoMjlrN3QzNzd2ODkiLCJ1c2VyIjoiR2l0SHViIn19.d4URcDjHXne2GVDLTw8jgPZ36h39j-5uT-MOR5C833g)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/8bdgfkhrh29k7t377v89](https://ybug.io/dashboard/reports/detail/8bdgfkhrh29k7t377v89)

**Comment by soulBit** [comment]
Closing as already in roadmap
