### ISSUE TITLE
[YBUG.IO] Cant view the blue box to update...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#593]
Cant view the blue box to update the app when on a desktop in either Chrome or Edge

*Source url:* https://live.sovryn.app/
*Reported by:* padloo@protonmail.com
*Reported at:* 06 Apr at 12:26 UTC

*Location:* DK, Capital Region, Copenhagen
*Browser:* Chrome 89.0.4389.114

*OS:* Windows 10.0
*Screen:* 1366x768
*Viewport:* 1366x657

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/dgqdqm5vdm4kzqbg7sw6/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTc3MTE5NzQsImRhdGEiOnsicmVwb3J0IjoiZGdxZHFtNXZkbTRrenFiZzdzdzYiLCJ1c2VyIjoiR2l0SHViIn19.aMkz-HYTk6w_DHvPy8t-RXnn-_N-nQhmkK9ZIKB9c50)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/dgqdqm5vdm4kzqbg7sw6](https://ybug.io/dashboard/reports/detail/dgqdqm5vdm4kzqbg7sw6)

**Comment by soulBit** [comment]
New "update" modal/service worker should resolve this issue
