### ISSUE TITLE
[YBUG.IO] Supplied Balance is collect but...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#608]
Supplied Balance is collect but total added in USDT/BTC pool shows up only the newest amount.  It should be same for me. 
I supplied rBRC liq twice.

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* sw21520002000@yahoo.co.jp
*Reported at:* 09 Apr at 13:47 UTC

*Location:* JP, Shizuoka, Shizuoka
*Browser:* Chrome 89.0.4389.114

*OS:* Windows 10.0
*Screen:* 1536x864
*Viewport:* 2304x1083

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/88v5mdhbj8zhr6qrxpbp/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTc5NzYwNTAsImRhdGEiOnsicmVwb3J0IjoiODh2NW1kaGJqOHpocjZxcnhwYnAiLCJ1c2VyIjoiR2l0SHViIn19.nbyTeYdrrBqW0OwgFkZ-lRwS0fteC0vXjI8LXP5s2xc)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/88v5mdhbj8zhr6qrxpbp](https://ybug.io/dashboard/reports/detail/88v5mdhbj8zhr6qrxpbp)

**Comment by soulBit** [comment]
Closing as issue resolved
