### ISSUE TITLE
update portfolio page

### ISSUE THREAD

**Issue by t-z-u** [DistributedCollective/Sovryn-frontend#613]

**Comment by t-z-u** [comment]
[BUY SOV v1.2.2.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/6290965/BUY.SOV.v1.2.2.zip)
update the current "my wallet" section to the new design in this file

**Comment by t-z-u** [comment]
@pietro-maximoff absolutely killed it!
just got a msg from yago, asking to put RBTC at the top and SOV underneath.
also to please remove CSOV
![a](https://user-images.githubusercontent.com/79344165/114635800-690ace80-9cbd-11eb-8072-7eaea4fe802a.png)

**Comment by pietro-maximoff** [comment]
added here #754
