### ISSUE TITLE
Using the SWAP: SOV --> rBTC in testnet; when Liquality wallet is involved, the convertByPath transaction fails after a succesful approve transaction.

### ISSUE THREAD

**Issue by jjmr007** [DistributedCollective/Sovryn-frontend#615]
**Describe the bug**

Using the platform https://test.sovryn.app/ to do the SWAP SOV-->RBTC, with Liquality wallet engaged.
The operation involves two transactions: `approve` and `convertByPath` which spends respectively a gas limit of 70.000 units of gas and 750.000 units of gas.

However the injected gas limit for the transaction `convertByPath` in the case of the Liquality interaction is just set to around 90.000 units of gas.

**To Reproduce**

1. Go to 'https://test.sovryn.app'
2. Click on 'Swap'
3. Chose SOV --> rBTC conversion and place a trade
4. See error: The UI get stucked in "TRANSACTION PENDING" forever, but querying the block explorer you see that the `convertByPath` transaction failed with a log similar to:
`class org.ethereum.vm.program.Program$OutOfGasException: Not enough gas for 'ISZERO' cause spending: invokeGas[89222], gas[3], usedGas[89222];`

**Expected behavior**
A window of transaction confirmed. The Liquality wallet should receive the injection data of the right gas limit (of around 750.000 gas units) for the `convertByPath` transaction

**Screenshots**
Screenshots:
This is the `approve` tx which succeed:
![step1](https://user-images.githubusercontent.com/17028457/114319613-2a6bed00-9ae0-11eb-8525-46439160cfe8.PNG)
this is `convertionByPath` transaction:
![step2](https://user-images.githubusercontent.com/17028457/114319617-3192fb00-9ae0-11eb-8960-f45eb57a7f11.png)
After that the process get stucked
![step3](https://user-images.githubusercontent.com/17028457/114319620-35268200-9ae0-11eb-8e58-e842659a820d.PNG)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Liquality Version 0.22.0

**Additional context**
Actual version of Liquality don't give the user any advanced gas controls, so using Liquality implies that this swap will fail, and must try a second time, which then succeed.

**Comment by creed-victor** [comment]
@jjmr007 can you check if it still doesn't work?
