### ISSUE TITLE
[YBUG.IO] Love the work! Well done!

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#616]
Love the work! Well done!
Link to 'Bitocracy' from 'Live' is missing? Will be convenient to access Governance from page header links

*Source url:* https://live.sovryn.app/wallet
*Reported by:* moonxlander@gmail.com
*Reported at:* 11 Apr at 22:03 UTC

*Location:* GB, England, Poplar
*Browser:* Firefox 85.0

*OS:* Windows 10.0
*Screen:* 1708x960
*Viewport:* 1708x818

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/kykg8fz45hzst9p7jh00/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTgxNzg2MzAsImRhdGEiOnsicmVwb3J0Ijoia3lrZzhmejQ1aHpzdDlwN2poMDAiLCJ1c2VyIjoiR2l0SHViIn19.Euw7rntUORhEtIUmWSJEUmVHrKMSyQkO2UeCahnThxo)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/kykg8fz45hzst9p7jh00](https://ybug.io/dashboard/reports/detail/kykg8fz45hzst9p7jh00)

**Comment by t-z-u** [comment]
this is solved with the work soulbit did today on the menu.
if we have the same menu on bitocracy for now (that soulbit just made) and not open another window we will have a dirty hack until we are able to migrate governance and staking onto live @creed-victor
