### ISSUE TITLE
No space on top buttons on PT-BR

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#624]
Hi,

On PT-BR there are no space on top buttons. Would be good to find a solution. Maybe staking button could be inserted inside Finance.

![Captura de tela de 2021-04-12 10-57-21](https://user-images.githubusercontent.com/1178856/114406666-18d92280-9b7e-11eb-88ba-875058b296ab.png)

**Comment by bitcoinuser** [comment]
@soulBit Is it possible to fix this? Thanks.

**Comment by soulBit** [comment]
@bitcoinuser thanks for raising this, we'll be moving the staking/governance options into a "Bitocracy" dropdown, which should resolve the problem:
https://github.com/DistributedCollective/Sovryn-frontend/issues/755
