### ISSUE TITLE
I lent 588 DoC, but I'm only able to withdraw 21 DoC at a time

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#63]
Hi,

I Lent 588 DoC, but I'm only able to withdraw 21 DoC at a time

**Comment by creed-victor** [comment]
Fixed with [v0.1.9](https://github.com/DistributedCollective/Sovryn-frontend/releases/tag/v0.1.9)

**Comment by bitcoinuser** [comment]
Hi @creed-victor, are you sute this is fixed. I updated sovryn and for me I still can only withdraw 21 DoC. Thanks.

**Comment by creed-victor** [comment]
@bitcoinuser thats strange, did app showed you notification asking to update?

**Comment by bitcoinuser** [comment]
> @bitcoinuser thats strange, did app showed you notification asking to update?

Yes. I still can only withdraw 21 DoC.

**Comment by bitcoinuser** [comment]
Fixed.
