### ISSUE TITLE
Confirm and cancel buttons are without strings to translate to PT-BR

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#633]
Confirm and cancel buttons are without strings to translate to PT-BR

![Captura de tela de 2021-04-12 23-06-50](https://user-images.githubusercontent.com/1178856/114486378-23c69e00-9be4-11eb-81d2-50778a646046.png)

**Comment by bitcoinuser** [comment]
Hi,

The text Pending too.

![Captura de tela de 2021-04-12 23-14-54](https://user-images.githubusercontent.com/1178856/114487135-718fd600-9be5-11eb-8d98-f904e5a2515a.png)

**Comment by creed-victor** [comment]
Hey, confirm/close is in the `common` group, will add pending there too
