### ISSUE TITLE
The profit balance changes to twice the value I click on BTC and then DOC on Lend window

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#64]
Hi,

The profit balance changes to twice the value when I click on BTC and then DOC on Lend window

**Comment by bitcoinuser** [comment]
Obs. Today I had the same problem of profit balance changes to twice the value. But I don't know how to reproduce. It's not reproducible as before. 
For now happened automatically, without any action.

**Comment by creed-victor** [comment]
Hm, ok, reopening.

**Comment by bitcoinuser** [comment]
I will close this issue. If I reproduce again, I reopen.

**Comment by bitcoinuser** [comment]
It's happening. So reopening.

**Comment by bitcoinuser** [comment]
Still not fixed.
