### ISSUE TITLE
[YBUG.IO] Cant not see correct RBTC total...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#644]
Cant not see correct RBTC total remaining value under liquidity mining events and also the share of reward pool and current sov reward looks incorrect
  \#1. Suppliec RBTC Balance 0.0104
However, 'Total Remaining' under Asset:RBTC in Liduidity Mining below shows 0.0000
This is incorrect - when i hadnt removed any RBTC, i was able to see 'current sov reward' & share of reward pool displayed. Is this a bug?\

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* moonxlander@gmail.com
*Reported at:* 13 Apr at 15:43 UTC

*Location:* GB, England, Poplar
*Browser:* Chrome 89.0.4389.90

*OS:* Windows 10.0
*Screen:* 1366x768
*Viewport:* 2732x1314

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/j35dcdkfdzqx0fcm1ck2/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTgzMjg2NDgsImRhdGEiOnsicmVwb3J0IjoiajM1ZGNka2ZkenF4MGZjbTFjazIiLCJ1c2VyIjoiR2l0SHViIn19.h18ODoteUBG_23Htd6UZ2vfG6vOhR3dh825P_F0XAa0)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/j35dcdkfdzqx0fcm1ck2](https://ybug.io/dashboard/reports/detail/j35dcdkfdzqx0fcm1ck2)

**Comment by creed-victor** [comment]
@BetsyBraddock this is user feedback, maybe you know what it is about about because i'm not sure how it should be in the ideal state

**Comment by BetsyBraddock** [comment]
Yes - sorry about this, I think it's just a typo (I think I used | instead of ||). I'll check and will fix tonight/tomorrow
