### ISSUE TITLE
Sometimes images appear small on Buy SOV page

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#646]
Sometimes Images appear small on Buy SOV page

See the two messages compared:

![Captura de tela de 2021-04-13 14-15-14](https://user-images.githubusercontent.com/1178856/114593988-1b617800-9c63-11eb-8235-537f68ae8db2.png)

![Captura de tela de 2021-04-13 14-15-39](https://user-images.githubusercontent.com/1178856/114594002-24524980-9c63-11eb-866a-acb6ef68de66.png)

**Comment by creed-victor** [comment]
@bitcoinuser is this issue is still valid? if so what is your brave browser version and OS version?

**Comment by bitcoinuser** [comment]
> @bitcoinuser is this issue is still valid? if so what is your brave browser version and OS version?

Yes, I still reproduce the problem. I use Ubuntu and Brave Versão 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Comment by bitcoinuser** [comment]
I don't reproduce this on https://redesign.sovryn.pages.dev/
