### ISSUE TITLE
[YBUG.IO] i supplied 0.05 rBTC and about 1...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#665]
i supplied 0.05 rBTC and about 125 SOV on this page the transaction was confirmed and balance on my metamask update, but right now i can neither see my contribution nor withdraw it

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* 
*Reported at:* 13 Apr at 20:19 UTC

*Location:* PL, Mazovia, Warsaw
*Browser:* Chrome 88.0.4324.182

*OS:* macOS 10.15.7
*Screen:* 1600x900
*Viewport:* 1600x751

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/cjgh0w56v4ybfvc1j091/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTgzNDUxNzUsImRhdGEiOnsicmVwb3J0IjoiY2pnaDB3NTZ2NHliZnZjMWowOTEiLCJ1c2VyIjoiR2l0SHViIn19.MIEZjgGE84IZ9HwZ8ujlSaaAyu0uZs27Yrif7YXGfhs)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/cjgh0w56v4ybfvc1j091](https://ybug.io/dashboard/reports/detail/cjgh0w56v4ybfvc1j091)

**Comment by creed-victor** [comment]
I think it's possible that users just doesn't notice withdraw tab

**Comment by BetsyBraddock** [comment]
In the new frontend (deployed last week), users should now see their SOV/BTC pool deposit history.

Not sure about the issue withdrawing SOV/BTC - I can see in the database that there are many LiquidityRemoved events, so it is definitely possible for people to do. 

You may be right and people just don't notice the tab
