### ISSUE TITLE
[YBUG.IO] Thus site is absolutely...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#669]
Thus site is absolutely atrocious using Firefox on an iPhone 8.  Scaling does not work; text and images are cut off...  QA needsto step up their game.

*Source url:* https://live.sovryn.app/
*Reported by:* JaBSter101@gmail.com
*Reported at:* 13 Apr at 21:13 UTC

*Location:* US, Massachusetts, Winchester
*Browser:* Safari 14.0.3

*OS:* iOS 14.4.2
*Screen:* 375x667
*Viewport:* 757x1268

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/5sk3n4hq8a0y2mk00t32/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTgzNDg0MTgsImRhdGEiOnsicmVwb3J0IjoiNXNrM240aHE4YTB5Mm1rMDB0MzIiLCJ1c2VyIjoiR2l0SHViIn19.pNGxIotWnzaBQIKEbwf4BF2LadyNfR27P-zlkAgtr58)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/5sk3n4hq8a0y2mk00t32](https://ybug.io/dashboard/reports/detail/5sk3n4hq8a0y2mk00t32)

**Comment by grinry** [comment]
No support for mobile yet
