### ISSUE TITLE
[YBUG.IO] After 30 second, everything goes...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#680]
After 30 second, everything goes black and i cant see nothing on the sovryn app

*Source url:* https://live.sovryn.app/
*Reported by:* 
*Reported at:* 13 Apr at 23:51 UTC

*Location:* CA, Quebec, Trois-Rivières
*Browser:* Chrome 89.0.4389.114

*OS:* Windows 10.0
*Screen:* 1366x768
*Viewport:* 1366x625

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/xpfsfy4d38xzb6hnwa1f/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTgzNTc5MTYsImRhdGEiOnsicmVwb3J0IjoieHBmc2Z5NGQzOHh6YjZobndhMWYiLCJ1c2VyIjoiR2l0SHViIn19.BP7fE-OWBY3PWBPGJ11tMpzaO9nWZtXXzFLFyJwId7M)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/xpfsfy4d38xzb6hnwa1f](https://ybug.io/dashboard/reports/detail/xpfsfy4d38xzb6hnwa1f)

**Comment by soulBit** [comment]
Backend issue should be resolved now
