### ISSUE TITLE
I think (Redeem) word should be used instead of (Withdraw)

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#69]
Hi,

I think (Redeem) word should be used instead of (Withdraw).

And I think instead of (Deposit amount) should be (Amount to redeem)

And the button (Withdraw Doc) be renamed to (Redeem Doc)

![Captura de tela de 2020-11-24 15-40-00](https://user-images.githubusercontent.com/1178856/100137690-928ca000-2e6b-11eb-9eb9-1fd939d331d0.png)

**Comment by bitcoinuser** [comment]
Another thing:

1- (Balance) should be renamed to (Lent)
2- (Account Balance) should be renamed to (Available to Lend)

**Comment by creed-victor** [comment]
Thanks for report.
"Deposit amount" label in withdraw tab was changed to "Amount to redeem", "Withdraw" tab renamed to "Redeem".
 Other suggestions may be reviewed later, because lending page may change in future when more currencies will be added.

**Comment by bitcoinuser** [comment]
> Another thing:
> 
> 1- (Balance) should be renamed to (Lent)
> 2- (Account Balance) should be renamed to (Available to Lend)

By other suggestions, you mean this?

**Comment by creed-victor** [comment]
> > Another thing:
> > 1- (Balance) should be renamed to (Lent)
> > 2- (Account Balance) should be renamed to (Available to Lend)
> 
> By other suggestions, you mean this?

Yes
