### ISSUE TITLE
[YBUG.IO] won't allow me to buy SOV

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#714]
won't allow me to buy SOV

*Source url:* https://live.sovryn.app/
*Reported by:* owain.mills@amaala.com
*Reported at:* 14 Apr at 18:17 UTC

*Location:* SA, Riyadh Region, Riyadh
*Browser:* Chrome 89.0.4389.114

*OS:* Windows 10.0
*Screen:* 1280x720
*Viewport:* 1232x610

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/djzp9gv4v5kystr54zq0/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg0MjQyODYsImRhdGEiOnsicmVwb3J0IjoiZGp6cDlndjR2NWt5c3RyNTR6cTAiLCJ1c2VyIjoiR2l0SHViIn19.bglqaYEM_hGNEL1cGUk-V49Wt4IEAw2L_TPyWkOR0mQ)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/djzp9gv4v5kystr54zq0](https://ybug.io/dashboard/reports/detail/djzp9gv4v5kystr54zq0)

**Comment by soulBit** [comment]
User appears to be trying to purchase more SOV than they have rBTC for, so the BUY SOV button is disabled. I suggest we add an additional error message above buy button to indicate exact reason for this
