### ISSUE TITLE
[YBUG.IO] i suggest to write rUSDT to do...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#718]
i suggest to write rUSDT to do not confusion with original usdt

*Source url:* https://live.sovryn.app/wallet
*Reported by:* 
*Reported at:* 14 Apr at 22:51 UTC

*Location:* HU, Budapest, Budapest
*Browser:* Chrome 89.0.4389.128

*OS:* macOS 11.2.3
*Screen:* 1440x900
*Viewport:* 1440x768

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/qxdq05pxrqaj450s0cxj/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg0NDA2ODgsImRhdGEiOnsicmVwb3J0IjoicXhkcTA1cHhycWFqNDUwczBjeGoiLCJ1c2VyIjoiR2l0SHViIn19.1D8wSmay8mCztCjOCaenG8Oi2SigEGvbhczfhWDNuWM)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/qxdq05pxrqaj450s0cxj](https://ybug.io/dashboard/reports/detail/qxdq05pxrqaj450s0cxj)

**Comment by soulBit** [comment]
This is implemented now
