### ISSUE TITLE
[YBUG.IO] I supplied 6083.917841 rUSDT to...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#722]
I supplied 6083.917841 rUSDT to the USDT/rBTC pool but the frontend shows me that I added 0.9178 only.

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* 
*Reported at:* 15 Apr at 01:25 UTC

*Location:* DE, Baden-Württemberg, Schwetzingen
*Browser:* Chrome 88.0.4324.192

*OS:* Windows 10.0
*Screen:* 1536x864
*Viewport:* 1536x758

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/6vdjszr9f4p2j730amz1/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg0NDk5MzAsImRhdGEiOnsicmVwb3J0IjoiNnZkanN6cjlmNHAyajczMGFtejEiLCJ1c2VyIjoiR2l0SHViIn19.7mWkKGrQ4PVbA6nr9Rjo7ZUlgmx7B6dr3IAiI-KCQJg)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/6vdjszr9f4p2j730amz1](https://ybug.io/dashboard/reports/detail/6vdjszr9f4p2j730amz1)

**Comment by s4t0shi-n4k4m0t0** [comment]
tx: 0xee8cdfea77e6f6425e60743013553ab5e3acfb53fcda5597052bd3d2d242d1cc

**Comment by creed-victor** [comment]
should have been fixed for some time now
