### ISSUE TITLE
Force user to use latest dapp version to make any transactions

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#728]
Dapp should check every x seconds / minutes if there is newer version and show dialog which asks users to update app.

Check possibly can be made in the service worker

**Comment by t-z-u** [comment]
https://xd.adobe.com/view/bb53ecb3-0da4-4662-715a-4b75a876db2c-cd62/
msg me for password
[Update modal.xd.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/6330889/Update.modal.xd.zip)
