### ISSUE TITLE
I had a closed trade that is not showing anymore on closed trading activity

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#730]
Hi,

I had a closed trade that is not showing anymore on closed trading activity

My address is: 0x992230F727e8DB1B3ba71f6Afba8be33D18aA02B

![Captura de tela de 2021-04-15 10-44-43](https://user-images.githubusercontent.com/1178856/114879723-d6128700-9dd7-11eb-9069-e26410238607.png)

**Comment by bitcoinuser** [comment]
Same problem for Lending History

**Comment by creed-victor** [comment]
@bitcoinuser still no history for you?

**Comment by bitcoinuser** [comment]
> @bitcoinuser still no history for you?

Yes, still no history.

**Comment by bitcoinuser** [comment]
On Version Build ID: d58151e I can see the history again. So closing.
