### ISSUE TITLE
[YBUG.IO] RBTC/USDT pool adds wrong amount of rbtc

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#736]
Hi,
Yesterday I deposited some rbtc in the rbtc/usdt pool, in different times, but not all the coins were added to the pool. Only 0.51 rbtc participate on the liquidity mining, but the total money was 1.09 rbtc.
Could you explain me why the rest is not considered or if there is any kind of problem?
Thanks

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* 
*Reported at:* 15 Apr at 17:26 UTC

*Location:* AR, Buenos Aires F.D., Buenos Aires
*Browser:* Chrome 89.0.4389.128

*OS:* Windows 10.0
*Screen:* 1536x960
*Viewport:* 1536x822

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/2yfmhsjfgvqgnrbfmvhw/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg1MDc1NzEsImRhdGEiOnsicmVwb3J0IjoiMnlmbWhzamZndnFnbnJiZm12aHciLCJ1c2VyIjoiR2l0SHViIn19._hIzZIIs8iujYNj1PDwy6N190jGQfvPVNNFVH3TKAXg)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/2yfmhsjfgvqgnrbfmvhw](https://ybug.io/dashboard/reports/detail/2yfmhsjfgvqgnrbfmvhw)

**Comment by soulBit** [comment]
Issue should be resolved now with latest updates to Liquidity mining page
