### ISSUE TITLE
On stats page the all time volume grow to for example 712 btc, then sometimes later go to 708

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#737]
Hi,

On stats page the all time volume grow to for example 712 btc, then go to 708.

I think the all time volume should just go higher no?

**Comment by soulBit** [comment]
This has been removed from the Stats page as there were some inconsistencies in how this was being displayed. Improved TVL/volume statistics are on roadmap alongside upgrades to backend
