### ISSUE TITLE
[YBUG.IO] Where ca I see circ supply and...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#740]
Where ca I see circ supply and how much that is staked of the circ supply? That stat  would be interesting.

*Source url:* https://live.sovryn.app/stats
*Reported by:* 
*Reported at:* 15 Apr at 19:45 UTC

*Location:* SE, Östergötland County, Norrköping
*Browser:* SamsungBrowser 13.2

*OS:* Android 10
*Screen:* 360x740
*Viewport:* 360x668

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/15r9n8t8h3f4npqjf8g7/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg1MTU5NjIsImRhdGEiOnsicmVwb3J0IjoiMTVyOW44dDhoM2Y0bnBxamY4ZzciLCJ1c2VyIjoiR2l0SHViIn19.iUqARgQxJWhHz2uGyO9MGJG1bs5tamM4Ni9ROQ6Bjsw)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/15r9n8t8h3f4npqjf8g7](https://ybug.io/dashboard/reports/detail/15r9n8t8h3f4npqjf8g7)

**Comment by soulBit** [comment]
Circulating supply is visible on BUY SOV page, and current staking figures are visible on wiki here:
https://wiki.sovryn.app/en/metrics/staking-running-total

Improvements will be made in the future to include all of this information directly within the dapp
