### ISSUE TITLE
Disable dapp for all non-desktop browsers (screen smaller than 1024px), ask users to use desktop browser

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#753]

**Comment by t-z-u** [comment]
[sovryn device not supported.xd.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/6330024/sovryn.device.not.supported.xd.zip)
https://xd.adobe.com/view/e088f6da-5b23-45b3-4b65-1ebaf1be32ca-96b9/
