### ISSUE TITLE
Header changes

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#755]
- [ ] create new dropdown group named `Bitocracy`
- [ ] move `Stake` and `Governance` navlinks to `Bitocracy` dropdown
- [ ] Make Stake and Governance dropdowns open in the new tab again
- [ ] Add icon which means that link will open in the new tab (ask tzu to make one)
- [ ] Do same thing for bitocracy.sovryn.app
- [ ] Open dropdowns on hover instead of click

**Comment by bitcoinuser** [comment]
Two more suggestions:

1- Just need to hover the mouse (no need to click) to show the other buttons from dropdown.
2- Add descriptions like the binance.com dropdown menu.

**Comment by bitcoinuser** [comment]
This kind of menu from gate.io site is interesting:

![Captura de tela de 2021-04-18 23-43-33](https://user-images.githubusercontent.com/1178856/115174710-20c62480-a0a0-11eb-9a51-4469c20a405a.png)

**Comment by bitcoinuser** [comment]
The menu still is not good on PT-BR on https://test.sovryn.app/.

![Captura de tela de 2021-04-21 14-35-04](https://user-images.githubusercontent.com/1178856/115597423-a23fd180-a2af-11eb-9f36-2ffe6340d9c8.png)
