### ISSUE TITLE
[YBUG.IO] Wrong total remaining is...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#762]
Wrong total remaining is displaying and share of reward pool didn't move after last deposit

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* 
*Reported at:* 16 Apr at 13:44 UTC

*Location:* US, California, Anaheim
*Browser:* Chrome 90.0.4430.72

*OS:* macOS 10.15.7
*Screen:* 1440x900
*Viewport:* 1361x718

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/jxgz5snd9m9k7rh30d5f/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg1ODA2NzIsImRhdGEiOnsicmVwb3J0IjoianhnejVzbmQ5bTlrN3JoMzBkNWYiLCJ1c2VyIjoiR2l0SHViIn19.KAlcnGOss9NmZ9q2UuO7pzaJ5yX1jPrbWUjwIDEvEoM)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/jxgz5snd9m9k7rh30d5f](https://ybug.io/dashboard/reports/detail/jxgz5snd9m9k7rh30d5f)

**Comment by soulBit** [comment]
Stats should now be up to date
