### ISSUE TITLE
[YBUG.IO] Hello.

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#766]
Hello.

I by mistake used this:
3JHFPFGSdQPYGKYxA272MbPbtgLqWyqCfc
when trying to transfer money to my liquality wallet. This is seen when selecting buy SOV and Get rBTC.
I copied at the wrong place... so stupid.
Is my BitCoin lost now?

Kind regards

Joe

*Source url:* https://live.sovryn.app/
*Reported by:* joeringvold@gmail.com
*Reported at:* 16 Apr at 23:45 UTC

*Location:* NO, Viken, Jessheim
*Browser:* Chrome 89.0.4389.128

*OS:* Windows 10.0
*Screen:* 1920x1080
*Viewport:* 1920x973

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/jnr1db10zzgr542vxbw2/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg2MTY3NDYsImRhdGEiOnsicmVwb3J0Ijoiam5yMWRiMTB6emdyNTQydnhidzIiLCJ1c2VyIjoiR2l0SHViIn19.hxl0v1gO8Fwxuewsqg3ghYs3islaHIwOpgGn3_B5rA0)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/jnr1db10zzgr542vxbw2](https://ybug.io/dashboard/reports/detail/jnr1db10zzgr542vxbw2)

**Comment by soulBit** [comment]
@jjmr007 I'm hoping this one is already resolved by now, could you double check user received their rBTC and close this ticket if so/contact user for a followup
