### ISSUE TITLE
[YBUG.IO] There seems to be an issue with...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#768]
There seems to be an issue with the display for the USDT Pool, amounts off by a decimal.   I am not sure if it affected the current share of reward pool
  \#1. Incorrect by a decimal put in\
  \#2. Didn't affect withdrawl though\

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* 
*Reported at:* 17 Apr at 03:39 UTC

*Location:* NL, North Holland, Amsterdam
*Browser:* Chrome 89.0.4389.128

*OS:* Windows 10.0
*Screen:* 1536x864
*Viewport:* 1536x722

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/cr7g2acnba5bp762v9d6/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg2MzA3OTEsImRhdGEiOnsicmVwb3J0IjoiY3I3ZzJhY25iYTVicDc2MnY5ZDYiLCJ1c2VyIjoiR2l0SHViIn19.hU2ii_AHNzVV_UFeBoZysRyRe4nIGf3kKor_Ty-nmUk)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/cr7g2acnba5bp762v9d6](https://ybug.io/dashboard/reports/detail/cr7g2acnba5bp762v9d6)

**Comment by soulBit** [comment]
@BetsyBraddock I believe this is resolved now, can you close if so?

**Comment by BetsyBraddock** [comment]
Thanks @soulBit it was an ongoing issue that is now resolved
