### ISSUE TITLE
[YBUG.IO] Unable to see my pooling stats.

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#770]
Unable to see my pooling stats. 
Also, provide description to supplied balance.

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* fsund001@gmail.com
*Reported at:* 17 Apr at 12:19 UTC

*Location:* GB, England, Tottenham
*Browser:* Chrome 90.0.4430.72

*OS:* Windows 10.0
*Screen:* 1500x1000
*Viewport:* 1500x862

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/kt13vhb3npxr74crkcjh/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg2NjE5NzMsImRhdGEiOnsicmVwb3J0Ijoia3QxM3ZoYjNucHhyNzRjcmtjamgiLCJ1c2VyIjoiR2l0SHViIn19.w_uKAr2QKLgFfeviL2LYbcqPnm3UowK_wPirCcmnP0s)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/kt13vhb3npxr74crkcjh](https://ybug.io/dashboard/reports/detail/kt13vhb3npxr74crkcjh)

**Comment by soulBit** [comment]
This issue should be resolved now with latest updates
