### ISSUE TITLE
[YBUG.IO] I provided ~$600 dollar worth of...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#776]
I provided ~$600 dollar worth of sov and rbtc combinded. I don't understand the 0.23 value

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* fsund001@gmail.com
*Reported at:* 17 Apr at 12:54 UTC

*Location:* GB, England, Tottenham
*Browser:* Chrome 90.0.4430.72

*OS:* Windows 10.0
*Screen:* 1500x1000
*Viewport:* 1500x862

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/0gt5zxzz1r00gktnq4t3/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg2NjQwOTQsImRhdGEiOnsicmVwb3J0IjoiMGd0NXp4enoxcjAwZ2t0bnE0dDMiLCJ1c2VyIjoiR2l0SHViIn19.XKD3yrrQ6AA3cEOvunSvop_rp1DfygOQdnjCL9j7LS8)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/0gt5zxzz1r00gktnq4t3](https://ybug.io/dashboard/reports/detail/0gt5zxzz1r00gktnq4t3)

**Comment by soulBit** [comment]
Updated liquidity mining UI has been released with more accurate reflection of user deposits/rewards
