### ISSUE TITLE
[YBUG.IO] Yesterday, April 16th, I entered...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#778]
Yesterday, April 16th, I entered into a RBTC-SOV market making transaction for between 90-95 RBTC and the transaction does not appear in my account. The RBTC and SOV have been withdrawn from my Sovryn account, however. Please advise. Thank you

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* runjpf@yahoo.com
*Reported at:* 17 Apr at 16:02 UTC

*Location:* US, California, San Francisco
*Browser:* Chrome 89.0.4389.128

*OS:* Windows 10.0
*Screen:* 1536x864
*Viewport:* 1536x722

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/1s0dwyjfck2y68jpns74/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg2NzUzNTMsImRhdGEiOnsicmVwb3J0IjoiMXMwZHd5amZjazJ5NjhqcG5zNzQiLCJ1c2VyIjoiR2l0SHViIn19.Wv5GwmmkreQjbPllnH3pW6KChI-qxS1ruslnLplEWhA)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/1s0dwyjfck2y68jpns74](https://ybug.io/dashboard/reports/detail/1s0dwyjfck2y68jpns74)

**Comment by soulBit** [comment]
Closing this as SOV pool reward stats are in the works
