### ISSUE TITLE
[YBUG.IO] you get logged out of your...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#786]
you get logged out of your wallet to frequently and cant navigate the pages. once you log into your wallet yo should have access to all pages of the portal without having to log back in.

*Source url:* https://live.sovryn.app/wallet
*Reported by:* 
*Reported at:* 17 Apr at 22:19 UTC

*Location:* AU, Victoria, Melbourne
*Browser:* Chrome 89.0.4389.128

*OS:* Windows 10.0
*Screen:* 1536x864
*Viewport:* 1536x754

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/wdf9y2kj2gnswcjxp12r/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg2OTc5NzQsImRhdGEiOnsicmVwb3J0Ijoid2RmOXkya2oyZ25zd2NqeHAxMnIiLCJ1c2VyIjoiR2l0SHViIn19.7lWfUakgnKjkl9o9c0iy3bQphRCC2dGzRNAs7LadZLY)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/wdf9y2kj2gnswcjxp12r](https://ybug.io/dashboard/reports/detail/wdf9y2kj2gnswcjxp12r)

**Comment by soulBit** [comment]
I believe this is due to bitocracy pages being separate dapp
