### ISSUE TITLE
Regression on Buy SOV page on PT-BR on test.sovryn.app

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#791]
Hi,

Regression on Buy SOV page on PT-BR on test.sovryn.app

![Captura de tela de 2021-04-17 19-59-19](https://user-images.githubusercontent.com/1178856/115128940-be91f480-9fb7-11eb-8d76-987c9f3bc9c2.png)

**Comment by bitcoinuser** [comment]
Same thing for ES language:

![Captura de tela de 2021-04-17 20-14-12](https://user-images.githubusercontent.com/1178856/115129142-93a8a000-9fb9-11eb-8659-483839772041.png)

**Comment by bitcoinuser** [comment]
Hi @creed-victor could you look at this?
Obs. On new design https://redesign.sovryn.pages.dev/ still have the problem.

**Comment by soulBit** [comment]
To be resolved once full redesign has been deployed
