### ISSUE TITLE
[YBUG.IO] My address 0x3e700B9080778cD7EB2...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#796]
My address 0x3e700B9080778cD7EB22650e2CbF3c337210f365 has provided 489.29 USDT liquidity now. When i chose "MAX" at Withdrawal, I see that correct amount. But the overview calculation has an error. Shows 4990.00 "Remaining" USDT as liquidity provided.

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* r21online@pm.me
*Reported at:* 18 Apr at 04:18 UTC

*Location:* SG, Singapore
*Browser:* Firefox 87.0

*OS:* macOS 10.15
*Screen:* 1440x900
*Viewport:* 1355x731

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/q14mcvr8xy4ndjgp57x0/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg3MTk1MjMsImRhdGEiOnsicmVwb3J0IjoicTE0bWN2cjh4eTRuZGpncDU3eDAiLCJ1c2VyIjoiR2l0SHViIn19.58wh6S6ZggQRHBFwfyDmLeeZV0blF441QhBmXCB9iFU)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/q14mcvr8xy4ndjgp57x0](https://ybug.io/dashboard/reports/detail/q14mcvr8xy4ndjgp57x0)

**Comment by soulBit** [comment]
Updated liquidity mining UI has been released with more accurate reflection of user deposits/rewards
