### ISSUE TITLE
[YBUG.IO] I did do some USDT/RBTC trades....

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#797]
I did do some USDT/RBTC trades. They are not listed in this "Trading activity" history list.

*Source url:* https://live.sovryn.app/trade
*Reported by:* r21online@pm.me
*Reported at:* 18 Apr at 04:19 UTC

*Location:* SG, Singapore
*Browser:* Firefox 87.0

*OS:* macOS 10.15
*Screen:* 1440x900
*Viewport:* 1355x731

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/7x9z3ptc18hwxhhjxatc/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg3MTk1OTUsImRhdGEiOnsicmVwb3J0IjoiN3g5ejNwdGMxOGh3eGhoanhhdGMiLCJ1c2VyIjoiR2l0SHViIn19.q7tlkYHK6sGjQwLtqUL15MBr1XAUie6hXDG2cLZdD-Y)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/7x9z3ptc18hwxhhjxatc](https://ybug.io/dashboard/reports/detail/7x9z3ptc18hwxhhjxatc)

**Comment by soulBit** [comment]
Closing this as Swap history is currently visible in Portfolio page, and we will be moving it to the appropriate place on Swap page in upcoming release. I have emailed the user explaining this
