### ISSUE TITLE
[YBUG.IO] I think I figured out that the ...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#798]
I think I figured out that the "trading activity history" ("closed") may only show "Trades" and not "Swaps" history.  I was interested to see the history of my Swaps.  Is there any way to view that?

*Source url:* https://live.sovryn.app/trade
*Reported by:* r21online@pm.me
*Reported at:* 18 Apr at 04:45 UTC

*Location:* SG, Singapore
*Browser:* Firefox 87.0

*OS:* macOS 10.15
*Screen:* 1440x900
*Viewport:* 1355x731

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/q65693drxbg8q61g43d3/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg3MjExNzQsImRhdGEiOnsicmVwb3J0IjoicTY1NjkzZHJ4Ymc4cTYxZzQzZDMiLCJ1c2VyIjoiR2l0SHViIn19.ZYwrDzUCVvPBrS40jINSWU96AepJpcQxv75rDMx3gu0)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/q65693drxbg8q61g43d3](https://ybug.io/dashboard/reports/detail/q65693drxbg8q61g43d3)

**Comment by soulBit** [comment]
Closing this as Swap history is currently visible in Portfolio page, and we will be moving it to the appropriate place on Swap page in upcoming release. I have emailed the user explaining this
