### ISSUE TITLE
[YBUG.IO] Completely non responsive site....

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#799]
Completely non responsive site. Looks very unprofessional one must say. Must be fixed.

*Source url:* https://live.sovryn.app/
*Reported by:* fsund001@gmail.com
*Reported at:* 18 Apr at 06:29 UTC

*Location:* GB, England, Stoke Newington
*Browser:* Chrome 89.0.4389.114

*OS:* Android 10
*Screen:* 360x780
*Viewport:* 749x1571

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/w0fc7rbb56p82c8wjnp2/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg3MjczOTcsImRhdGEiOnsicmVwb3J0IjoidzBmYzdyYmI1NnA4MmM4d2pucDIiLCJ1c2VyIjoiR2l0SHViIn19.UAAtQcBvcqOO55qCAeqBy0e42HNwuy94n2zgnn9ICJ0)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/w0fc7rbb56p82c8wjnp2](https://ybug.io/dashboard/reports/detail/w0fc7rbb56p82c8wjnp2)

**Comment by soulBit** [comment]
Closing this as mobile styling will rectified in an upcoming release
