### ISSUE TITLE
[YBUG.IO] Claim SOV button not available....

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#802]
Claim SOV button not available. Origin sales here

*Source url:* https://live.sovryn.app/wallet
*Reported by:* 
*Reported at:* 18 Apr at 17:04 UTC

*Location:* GR, Attica, Athens
*Browser:* Chrome 89.0.4389.128

*OS:* Windows 10.0
*Screen:* 1366x768
*Viewport:* 1034x666

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/grqkja0752pm96x4a42t/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg3NjU0NzIsImRhdGEiOnsicmVwb3J0IjoiZ3Jxa2phMDc1MnBtOTZ4NGE0MnQiLCJ1c2VyIjoiR2l0SHViIn19.onZ9AJcd9mXfZFhAETiU3P9C0CNTaUsQ7dsoNYUV0H8)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/grqkja0752pm96x4a42t](https://ybug.io/dashboard/reports/detail/grqkja0752pm96x4a42t)

**Comment by soulBit** [comment]
Closing this as a known issue that is being worked on
