### ISSUE TITLE
Can't lend DoC 

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#803]
Hi,

A friend is trying to lend 10 DoC using Liquality wallet.

Obs. See the zip file attached with the video with the error
Obs1. The user has RBTC as you can see here: 
Obs2. His address is: 0x306516a1C5a2dbc81e049525d4FC3AF4A612d437

![photo_2021-04-18_14-41-37](https://user-images.githubusercontent.com/1178856/115155048-6ceb7780-a054-11eb-8408-2c7248b19243.jpg)

[Sovryn_Teste.mp4.zip](https://github.com/DistributedCollective/Sovryn-frontend/files/6331837/Sovryn_Teste.mp4.zip)

**Comment by soulBit** [comment]
@bitcoinuser are they using latest version of Liquality? Should be version 0.24.0

**Comment by bitcoinuser** [comment]
> @bitcoinuser are they using latest version of Liquality? Should be version 0.24.0

Yes, he is on Liquality 0.24.0.

**Comment by creed-victor** [comment]
@bitcoinuser latest liquality wallet forces gas limit to 2 million for rsk network, until its fixed users should have at least 10$ of rbtc in their wallet and use "slow" option for transaction speed.
