### ISSUE TITLE
[YBUG.IO] I am not being allowed to borrow...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#806]
I am not being allowed to borrow. See the screen shot. The transaction hash is 0x593f149c809457a571930bfa17c3b6f01298c8fff5f9f91938e79d8c0e1aba2a

I have alittle over .09rbtc and wanted to borrow 2k in usdt and was unable to. I Lended out .04 rbrtc and tried to borrow 1k thinking that might matter but it did not. I am still getting the same failed message.

*Source url:* https://live.sovryn.app/lend
*Reported by:* betthefarm2nite@protonmail.com
*Reported at:* 19 Apr at 04:57 UTC

*Location:* CA, Quebec, Montreal
*Browser:* Firefox 87.0

*OS:* Windows 10.0
*Screen:* 1920x1080
*Viewport:* 1418x954

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/jbhn6crj3tdza9tk3t44/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg4MDgyNzgsImRhdGEiOnsicmVwb3J0IjoiamJobjZjcmozdGR6YTl0azN0NDQiLCJ1c2VyIjoiR2l0SHViIn19.Kr0GyFqDZcw-G0fDCizaubTnKisq1jY4zAL1G_Xufsg)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/jbhn6crj3tdza9tk3t44](https://ybug.io/dashboard/reports/detail/jbhn6crj3tdza9tk3t44)

**Comment by soulBit** [comment]
Issue is due to running out of gas

https://dashboard.tenderly.co/tx/rsk/0x593f149c809457a571930bfa17c3b6f01298c8fff5f9f91938e79d8c0e1aba2a
