### ISSUE TITLE
[YBUG.IO] Hi,

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#821]
Hi,

I'm immediately receiving a failed transaction status when attempting to swap rBTC to Sov using ledger before I am even prompted to accept the transaction on ledger device. Am I doing something wrong?

*Source url:* https://live.sovryn.app/
*Reported by:* benjamintibbott@gmail.com
*Reported at:* 19 Apr at 18:49 UTC

*Location:* GB, Scotland, Motherwell
*Browser:* Chrome 89.0.4389.128

*OS:* Windows 10.0
*Screen:* 1280x720
*Viewport:* 1422x678

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/bq83wvca94s3k6rpnmt9/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg4NTgxNzUsImRhdGEiOnsicmVwb3J0IjoiYnE4M3d2Y2E5NHMzazZycG5tdDkiLCJ1c2VyIjoiR2l0SHViIn19.7XrWRq_02QGTqWea4RuUq2F8HoqY40SwzgU0w9_ipz8)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/bq83wvca94s3k6rpnmt9](https://ybug.io/dashboard/reports/detail/bq83wvca94s3k6rpnmt9)

**Comment by soulBit** [comment]
User likely needs to enable contract data on the device
