### ISSUE TITLE
[YBUG.IO] I can not follow the right steps...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#824]
I can not follow the right steps to buy.
I have sent BTCB (Binance) to Metamask. I can not get rBTC and/or SOV.
'Top up Wallet' meaning which wallet?

*Source url:* https://live.sovryn.app/
*Reported by:* pvanool@gmail.com
*Reported at:* 20 Apr at 13:16 UTC

*Location:* NL, North Brabant, Waspik
*Browser:* Chrome 89.0.4389.128

*OS:* Windows 10.0
*Screen:* 1920x1080
*Viewport:* 1920x937

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/c2wpjapggcqxgqkdt6np/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg5MjQ2MTYsImRhdGEiOnsicmVwb3J0IjoiYzJ3cGphcGdnY3F4Z3FrZHQ2bnAiLCJ1c2VyIjoiR2l0SHViIn19.-1KIWpKHhnDWFjCpUwd-RcnBRQRMCcUTYHlu5b-zXwM)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/c2wpjapggcqxgqkdt6np](https://ybug.io/dashboard/reports/detail/c2wpjapggcqxgqkdt6np)

**Comment by soulBit** [comment]
User needs to send BTC via FastBTC or deposit rBTC in their wallet
