### ISSUE TITLE
[YBUG.IO] Using Metamask.   Successfully...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#829]
Using Metamask.   Successfully used the DAPP to convert BTC into rbtc.    Cannot get the system to prompt me on the Metamask side to accept the purchase of SOV.

I did see the dialog box once only briefly then  Metamask appeared to reboot and it was gone.  

Pulling down on the metamask screen to refresh the page does not work either.

*Source url:* https://live.sovryn.app/
*Reported by:* 
*Reported at:* 20 Apr at 19:32 UTC

*Location:* CA, Ontario, St. Thomas
*Browser:* Chrome 90.0.4430.66

*OS:* Android 8.1.0
*Screen:* 412x618
*Viewport:* 412x594

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/bmmhdbygnwv2hcfta20v/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg5NDcxNjcsImRhdGEiOnsicmVwb3J0IjoiYm1taGRieWdud3YyaGNmdGEyMHYiLCJ1c2VyIjoiR2l0SHViIn19.LMvKmFE8lVglEx0CZ3WkDcUl9xiUrGgehdfgtPt8e4g)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/bmmhdbygnwv2hcfta20v](https://ybug.io/dashboard/reports/detail/bmmhdbygnwv2hcfta20v)

**Comment by soulBit** [comment]
Mobile metamask not supported currently
