### ISSUE TITLE
[YBUG.IO] Can't select Liquality wallet...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#836]
Can't select Liquality wallet option.
  \#1. I've installed Liquality wallet, but still can't select it and continue.\

*Source url:* https://live.sovryn.app/
*Reported by:* 
*Reported at:* 21 Apr at 00:12 UTC

*Location:* US, Utah, Herriman
*Browser:* Chrome 89.0.4389.128

*OS:* Windows 10.0
*Screen:* 1920x1080
*Viewport:* 1920x947

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/4rt9xrh6ssgswk8bymcw/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg5NjM5NjEsImRhdGEiOnsicmVwb3J0IjoiNHJ0OXhyaDZzc2dzd2s4YnltY3ciLCJ1c2VyIjoiR2l0SHViIn19.abSzSMYIXAkLSkCKoFOCyGxA_jPpxcofskiq5n2qdsA)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/4rt9xrh6ssgswk8bymcw](https://ybug.io/dashboard/reports/detail/4rt9xrh6ssgswk8bymcw)

**Comment by soulBit** [comment]
Liquality needs to have "set as default web3 wallet" option enabled, and no other browser wallets present
