### ISSUE TITLE
Affiliates

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#839]
XD Design:
https://xd.adobe.com/view/bfbd8a0a-b3ae-4985-61c4-910ad1670e1e-c98c/

- Access dapp with URL including `?ref=WALLET_ADDRESS`  - e.g. `https://live.sovryn.app/?ref=0x616cC7a216dBb411F0632E6B65ce2B1A9D9a05f3`
- Set "SovAffiliate" cookie in browser with referral wallet address
- When user makes a Margin Trade, check if user has already been referred by checking contract and pass that address into margin contract call, if it exists. If not then use the referrer address from cookie (as this is the first time user has been referred). Users should not be able to use their own address as referrer.
- Once transaction has been confirmed, referrer can navigate to `/affiliate` route/page and see detailed information on their rewards, as per design
- Include menu item for Affiliate page under "Rewards" dropdown menu in Header
- No claim buttons will be visible on affiliate page

**Comment by t-z-u** [comment]
https://xd.adobe.com/view/8ac3606b-5a4c-49e2-7388-9e7415d4261e-fcf2/

**Comment by pietro-maximoff** [comment]
waiting for PR in sovryn-smart-contracts https://github.com/DistributedCollective/Sovryn-smart-contracts/pull/233

**Comment by powerhousefrank** [comment]
> waiting for PR in sovryn-smart-contracts [DistributedCollective/Sovryn-smart-contracts#233](https://github.com/DistributedCollective/Sovryn-smart-contracts/pull/233)

This PR was merged, but undone later due to lack of testing.

A new PR should be created by @tjcloa or @santosinarp

**Comment by t-z-u** [comment]
https://xd.adobe.com/view/bfbd8a0a-b3ae-4985-61c4-910ad1670e1e-c98c/

**Comment by t-z-u** [comment]
https://xd.adobe.com/view/b2a4cc75-3b89-49ce-7da3-e7dcb7729644-c495/

**Comment by soulBit** [comment]
Claim SOV and Fees buttons have been removed from features

**Comment by soulBit** [comment]
On hold till LendV2 contracts have been deployed, and updated smart affiliate contracts set up by Circle of Order

**Comment by t-z-u** [comment]
can we make this live now?

**Comment by soulBit** [comment]
Moved back on hold till smart contract issues with swaps has been resolved, and updated affiliates contracts deployed to testnet
