### ISSUE TITLE
Yellow color on short trade should be red to reflect candles graph

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#84]
Hi

Yellow color on short trade should be red to reflect candles graph. As you can see on on long trade the color is green and reflect candles graph.

![Captura de tela de 2020-12-04 09-59-45](https://user-images.githubusercontent.com/1178856/101167035-08d19500-3618-11eb-8851-f368f5570f4e.png)

**Comment by creed-victor** [comment]
Thanks, forwarded to our UX designer.
