### ISSUE TITLE
[YBUG.IO] Metamask has disappeared from...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#857]
Metamask has disappeared from the browser wallet options...????

*Source url:* https://live.sovryn.app/
*Reported by:* oppenheimtony@aol.com
*Reported at:* 22 Apr at 13:05 UTC

*Location:* GB, England, Reading
*Browser:* Chrome 87.0.4280.67

*OS:* macOS 11.2.3
*Screen:* 1440x900
*Viewport:* 1440x689

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/6r7hn07hd30wzsfafwpm/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkwOTY3MjMsImRhdGEiOnsicmVwb3J0IjoiNnI3aG4wN2hkMzB3enNmYWZ3cG0iLCJ1c2VyIjoiR2l0SHViIn19.I1L15jUzWoMMa7I6jeLuPvU8Oqx37E0EyJQUL-ZqBUw)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/6r7hn07hd30wzsfafwpm](https://ybug.io/dashboard/reports/detail/6r7hn07hd30wzsfafwpm)

**Comment by soulBit** [comment]
User needs to select Browser
