### ISSUE TITLE
[YBUG.IO] Can you explain or provide a...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#859]
Can you explain or provide a link to explain why the SOV token should be considered useful? What is it actually used for?

*Source url:* https://live.sovryn.app/
*Reported by:* treflip_richard@hotmail.com
*Reported at:* 22 Apr at 14:48 UTC

*Location:* GB, England, Ruislip
*Browser:* Chrome 89.0.4389.114

*OS:* Android 11
*Screen:* 393x830
*Viewport:* 393x679

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/x8mpb3b9n23zrk2jpz3d/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkxMDI5MTgsImRhdGEiOnsicmVwb3J0IjoieDhtcGIzYjluMjN6cmsyanB6M2QiLCJ1c2VyIjoiR2l0SHViIn19.7Lq0LNBIRTUfxDYnCiW95Tfc2dzgjZMR9Gzoj-_OWvI)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/x8mpb3b9n23zrk2jpz3d](https://ybug.io/dashboard/reports/detail/x8mpb3b9n23zrk2jpz3d)

**Comment by soulBit** [comment]
@t-z-u we already have this information visible further down the page in "Stake & Vote" section, but may be worth including a link to it here just above the "Buy SOV" button (e.g. "What is SOV? Click here to find out more"). Close this ticket if you don't think it's needed, or a solution is already in the roadmap
