### ISSUE TITLE
[YBUG.IO] Hi. I'm trying to buy SOV with...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#865]
Hi. I'm trying to buy SOV with RBTC. I engaged with Liquality wallet extension. I'm trying to send 0.001674037315361936 RBTC (slow network fee) and get an error: insufficient funds to pay for pending and new transaction. Can you please help me to fix it

*Source url:* https://live.sovryn.app/
*Reported by:* djdavid@ukr.net
*Reported at:* 22 Apr at 18:12 UTC

*Location:* UA, Kharkivska Oblast, Kharkiv
*Browser:* Chrome 89.0.4389.128

*OS:* Windows 10.0
*Screen:* 1920x1200
*Viewport:* 1381x852

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/4vdhcy7c8nfp67sv5k1m/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkxMTUxMzAsImRhdGEiOnsicmVwb3J0IjoiNHZkaGN5N2M4bmZwNjdzdjVrMW0iLCJ1c2VyIjoiR2l0SHViIn19.daSh_fyXu8VPOAxCz6ZqDQSW3k2Dy2XO7k5r2OSmtks)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/4vdhcy7c8nfp67sv5k1m](https://ybug.io/dashboard/reports/detail/4vdhcy7c8nfp67sv5k1m)

**Comment by soulBit** [comment]
Sent user an email with potential solution (reducing total rBTC being spent to work around Liquality gas fee estimation issue)
