### ISSUE TITLE
[YBUG.IO] I didn't abort the transaction,...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#875]
I didn't abort the transaction, any idea what is going wrong here?

*Source url:* https://live.sovryn.app/
*Reported by:* benjamincarroll93@gmail.com
*Reported at:* 23 Apr at 02:16 UTC

*Location:* CA, Ontario, Kitchener
*Browser:* Chrome 90.0.4430.85

*OS:* macOS 10.15.7
*Screen:* 1440x900
*Viewport:* 1440x692

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/gc0wzxsf75hdns1r4xgf/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkxNDQxNzYsImRhdGEiOnsicmVwb3J0IjoiZ2Mwd3p4c2Y3NWhkbnMxcjR4Z2YiLCJ1c2VyIjoiR2l0SHViIn19.ibsEWhhuBJfy5FQDksjWAJoYI7wpQb1IeV4d0EI32UY)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/gc0wzxsf75hdns1r4xgf](https://ybug.io/dashboard/reports/detail/gc0wzxsf75hdns1r4xgf)

**Comment by soulBit** [comment]
Sent user follow-up email providing potential solutions

**Comment by thefishbomb** [comment]
Also having the same issue if anyone has a good solution.

**Comment by soulBit** [comment]
@thefishbomb please create a ticket with our Helpdesk and someone will assist, or you can ask over at our discord:
https://sovryn.freshdesk.com/
https://discord.gg/kBTNx4zjRf
