### ISSUE TITLE
I would like to translate all strings from test.sovryn.app to Portuguese Brazilian...

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#88]
Hi,

I would like to translate all strings from test.sovryn.app to Portuguese Brazilian but some strings I see on test.soveryn.app don't exist on https://github.com/DistributedCollective/Sovryn-frontend/blob/development/src/locales/en/translation.json

Why?

Thanks.

**Comment by creed-victor** [comment]
Hey, thanks for your PR's!

Most likely some of components were missed and text from there wasn't moved to translations file.
If you know which texts doesn't exists - comment here and we will add them

**Comment by bitcoinuser** [comment]
> If you know which texts doesn't exists - comment here and we will add them

There are many to write here. Just go to https://test.sovryn.app/, change language to PT-BR browse the window and everything that is still in English it's what is missing.

Thanks
