### ISSUE TITLE
[YBUG.IO] how do i see my full addresse ox...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#890]
how do i see my full addresse ox17.....2DEa?

*Source url:* https://live.sovryn.app/wallet
*Reported by:* 
*Reported at:* 23 Apr at 21:04 UTC

*Location:* US, Illinois, Chicago
*Browser:* Chrome 90.0.4430.72

*OS:* Windows 10.0
*Screen:* 1366x768
*Viewport:* 1366x661

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/wfxr57kbg1khbqp465tb/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkyMTE4NTEsImRhdGEiOnsicmVwb3J0Ijoid2Z4cjU3a2JnMWtoYnFwNDY1dGIiLCJ1c2VyIjoiR2l0SHViIn19.gptFlHkERjatUsk17yAVMg51t7ILtimS03RSMmx0aBU)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/wfxr57kbg1khbqp465tb](https://ybug.io/dashboard/reports/detail/wfxr57kbg1khbqp465tb)

**Comment by soulBit** [comment]
@t-z-u not sure if this is already part of the new redesign, if it is please close this. Otherwise  we should definitely include some way of confirming/copying exact address dapp is using

**Comment by soulBit** [comment]
Closing this as redundant, we now have a "copy address" menu option for currently engaged wallet
