### ISSUE TITLE
[YBUG.IO] I had provided .25 RBT and 257...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#892]
I had provided .25 RBT and 257 SOV into the LP yesterday from 0x3e700B9080778cD7EB22650e2CbF3c337210f365. Now, I can't see the provided liquidity in the SOV/BTC Pool section at the bottom, nor can I attempt to withdraw. When I click "max" it shows me only 9.6626 SOV to withdraw. I guess there is still work in progress.  I don't need to be worried do I? ;-)
Keep up the good work on Sovryn!!

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* r21online@pm.me
*Reported at:* 24 Apr at 01:55 UTC

*Location:* SG, Singapore
*Browser:* Firefox 88.0

*OS:* macOS 10.15
*Screen:* 2400x1350
*Viewport:* 1861x944

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/rxgbg4b2ydyajyk5bqvy/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkyMjkzNDYsImRhdGEiOnsicmVwb3J0IjoicnhnYmc0YjJ5ZHlhanlrNWJxdnkiLCJ1c2VyIjoiR2l0SHViIn19.p9NlwumIiCCi2ETpp2A_vQbfLNgqMmSK0ZUnXr1GtEM)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/rxgbg4b2ydyajyk5bqvy](https://ybug.io/dashboard/reports/detail/rxgbg4b2ydyajyk5bqvy)

**Comment by soulBit** [comment]
Improved description/UI for pool tokens is in roadmap
