### ISSUE TITLE
[YBUG.IO] it always goes to blank screen.

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#895]
it always goes to blank screen.

*Source url:* https://live.sovryn.app/trade
*Reported by:* Gewoonrobbe@gmail.com
*Reported at:* 24 Apr at 13:11 UTC

*Location:* BE, Flanders, Koksijde
*Browser:* Chrome 90.0.4430.85

*OS:* Windows 10.0
*Screen:* 1536x864
*Viewport:* 1536x722

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/zqk373yh93rnw2hbsp25/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkyNjk5MDcsImRhdGEiOnsicmVwb3J0IjoienFrMzczeWg5M3JudzJoYnNwMjUiLCJ1c2VyIjoiR2l0SHViIn19.DIVUaTkl20QHWrNclLCcHVqRuoeRQxr3NenS95IDkLQ)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/zqk373yh93rnw2hbsp25](https://ybug.io/dashboard/reports/detail/zqk373yh93rnw2hbsp25)

**Comment by soulBit** [comment]
Issue should be resolved now
