### ISSUE TITLE
[YBUG.IO] why does this happen? Please help

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#896]
why does this happen? Please help

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* js4spencer@yahoo.com
*Reported at:* 24 Apr at 14:50 UTC

*Location:* US, Georgia, Marietta
*Browser:* Chrome 89.0.4389.128

*OS:* Windows 10.0
*Screen:* 1280x720
*Viewport:* 1280x578

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/a7vc5tc1dqx0qc6pxvwp/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkyNzU4NjQsImRhdGEiOnsicmVwb3J0IjoiYTd2YzV0YzFkcXgwcWM2cHh2d3AiLCJ1c2VyIjoiR2l0SHViIn19.tGfoXbuF-9MgQBBN1bvCGCCzYGMTPFC3qZyHRvB9AbM)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/a7vc5tc1dqx0qc6pxvwp](https://ybug.io/dashboard/reports/detail/a7vc5tc1dqx0qc6pxvwp)

**Comment by soulBit** [comment]
User is experiencing issues with Liquality and gas fees/limits, sent a follow-up email to them providing a solution
