### ISSUE TITLE
[YBUG.IO] The update rate is very slow and...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#897]
The update rate is very slow and inaccurate

*Source url:* https://live.sovryn.app/trade
*Reported by:* powerpokets@gmail.com
*Reported at:* 24 Apr at 16:32 UTC

*Location:* ZA, Gauteng, Gauteng
*Browser:* Chrome 90.0.4430.85

*OS:* Windows 10.0
*Screen:* 1600x900
*Viewport:* 1600x757

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/shb2q8dmbnxrgasqh59j/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkyODE5NTYsImRhdGEiOnsicmVwb3J0Ijoic2hiMnE4ZG1ibnhyZ2FzcWg1OWoiLCJ1c2VyIjoiR2l0SHViIn19.S_8igHNLm3iQpvCo4_ZDTJ8As8iUIXhRp4DndeEiyT0)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/shb2q8dmbnxrgasqh59j](https://ybug.io/dashboard/reports/detail/shb2q8dmbnxrgasqh59j)

**Comment by soulBit** [comment]
Refresh rate of active trades has been improved so this should not be an issue any longer
