### ISSUE TITLE
[YBUG.IO] hello,

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#898]
hello,

My wallet got emptied from liquid when it connected to your wallet on sovryn

*Source url:* https://live.sovryn.app/wallet
*Reported by:* alexprimiano@outlook.com
*Reported at:* 24 Apr at 18:40 UTC

*Location:* CA, Quebec, Montreal
*Browser:* Chrome 90.0.4430.85

*OS:* macOS 10.15.7
*Screen:* 1440x900
*Viewport:* 1440x713

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/h3c7rj8pawkyy7nnbd3j/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkyODk2MTMsImRhdGEiOnsicmVwb3J0IjoiaDNjN3JqOHBhd2t5eTdubmJkM2oiLCJ1c2VyIjoiR2l0SHViIn19.h26NFMHUPKHmb-d6vQ4xbZsuNIexUyuXEfkEBT6ueWg)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/h3c7rj8pawkyy7nnbd3j](https://ybug.io/dashboard/reports/detail/h3c7rj8pawkyy7nnbd3j)

**Comment by soulBit** [comment]
User has contacted Liquality support to resolve this issue, it appears unrelated to Sovryn dapp
