### ISSUE TITLE
[YBUG.IO] Price per satoshi is lower then...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#900]
Price per satoshi is lower then real price way???

*Source url:* https://live.sovryn.app/trade
*Reported by:* 
*Reported at:* 25 Apr at 03:12 UTC

*Location:* GB, England, London
*Browser:* Safari 14.0.3

*OS:* iOS 14.4.2
*Screen:* 428x926
*Viewport:* 428x746

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/16q4rn8jtwak7ktb4rd3/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkzMjAzNDksImRhdGEiOnsicmVwb3J0IjoiMTZxNHJuOGp0d2FrN2t0YjRyZDMiLCJ1c2VyIjoiR2l0SHViIn19.VpizatKdpaT5EpUm0Qcvwgdz-9RaXNu-NhHwpEPXWq8)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/16q4rn8jtwak7ktb4rd3](https://ybug.io/dashboard/reports/detail/16q4rn8jtwak7ktb4rd3)

**Comment by soulBit** [comment]
Rate shown in swap UI takes slippage and current rate into account, so it will differ from chart price
