### ISSUE TITLE
[YBUG.IO] die Seite wird immer schwarz...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#901]
die Seite wird immer schwarz wenn ich irgend etwas anklicken will, bitte um Hilfe.

*Source url:* https://live.sovryn.app/trade
*Reported by:* moezarzar7@gmail.com
*Reported at:* 25 Apr at 04:10 UTC

*Location:* DE, Hesse, Frankfurt am Main
*Browser:* Chrome 90.0.4430.85

*OS:* macOS 10.15.7
*Screen:* 1440x900
*Viewport:* 1440x789

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/4343841dkhta6w1jbwcc/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkzMjM4NTcsImRhdGEiOnsicmVwb3J0IjoiNDM0Mzg0MWRraHRhNncxamJ3Y2MiLCJ1c2VyIjoiR2l0SHViIn19.DBi0enUmjfUz4jvvCtLU6vDUHPdEtuuCS-ROk60INw8)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/4343841dkhta6w1jbwcc](https://ybug.io/dashboard/reports/detail/4343841dkhta6w1jbwcc)

**Comment by soulBit** [comment]
Issue should be resolved now
