### ISSUE TITLE
[YBUG.IO] Can't see my LP rewards

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#902]
Can't see my LP rewards
  \#1. I am providing a healthy amount of SOV/RBTC LP but I can't see it anywhere on the platform other than when I look at the withdraw tab.
\

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* nlhybrid@yandex.com
*Reported at:* 25 Apr at 05:27 UTC

*Location:* TH, Bangkok, Bangkok
*Browser:* Chrome 89.0.4389.90

*OS:* Linux unknown
*Screen:* 1920x1080
*Viewport:* 1920x943

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/pxg47tajw6xshmxf1yqb/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkzMjg0MzUsImRhdGEiOnsicmVwb3J0IjoicHhnNDd0YWp3NnhzaG14ZjF5cWIiLCJ1c2VyIjoiR2l0SHViIn19.MT18RLPG57r0uNJnJOuXEKAzW0bhmlPq2MY0eeOLXdw)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/pxg47tajw6xshmxf1yqb](https://ybug.io/dashboard/reports/detail/pxg47tajw6xshmxf1yqb)

**Comment by soulBit** [comment]
Updated stats on roadmap for future release
