### ISSUE TITLE
[YBUG.IO] The app needs update to...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#908]
The app needs update to facilitate staking

*Source url:* https://live.sovryn.app/
*Reported by:* 
*Reported at:* 25 Apr at 17:13 UTC

*Location:* KE
*Browser:* Chrome 90.0.4430.82

*OS:* Android 11
*Screen:* 360x800
*Viewport:* 360x720

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/nt5sbx51fabpaxgs05wx/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkzNzA4MzksImRhdGEiOnsicmVwb3J0IjoibnQ1c2J4NTFmYWJwYXhnczA1d3giLCJ1c2VyIjoiR2l0SHViIn19.aNlLVcAol5MEHZmLBiw8jgD9jeMeO9WVeN1trFeQrpw)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/nt5sbx51fabpaxgs05wx](https://ybug.io/dashboard/reports/detail/nt5sbx51fabpaxgs05wx)

**Comment by soulBit** [comment]
Staking can already be performed from staking link in menus
