### ISSUE TITLE
[YBUG.IO] when will my shares of reward...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#910]
when will my shares of reward pool show up?

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* robertagoralski@gmail.com
*Reported at:* 25 Apr at 20:57 UTC

*Location:* LV
*Browser:* Chrome 90.0.4430.85

*OS:* macOS 10.15.7
*Screen:* 1920x1080
*Viewport:* 1789x930

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/fz6whmjt0108307yjjq9/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkzODQyNTEsImRhdGEiOnsicmVwb3J0IjoiZno2d2htanQwMTA4MzA3eWpqcTkiLCJ1c2VyIjoiR2l0SHViIn19.JMxFK322eJ7gQOyg4bGD2B4snjjw22LAIrO85Xc8dNg)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/fz6whmjt0108307yjjq9](https://ybug.io/dashboard/reports/detail/fz6whmjt0108307yjjq9)

**Comment by soulBit** [comment]
Sent user follow-up email with link to reward calculator
