### ISSUE TITLE
[YBUG.IO] how do you add usdt to soveryn app?

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#911]
how do you add usdt to soveryn app?

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* robertagoralski@gmail.com
*Reported at:* 25 Apr at 20:58 UTC

*Location:* LV
*Browser:* Chrome 90.0.4430.85

*OS:* macOS 10.15.7
*Screen:* 1920x1080
*Viewport:* 1789x930

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/mn4axqpp7wr2pjytsdm0/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkzODQyOTgsImRhdGEiOnsicmVwb3J0IjoibW40YXhxcHA3d3IycGp5dHNkbTAiLCJ1c2VyIjoiR2l0SHViIn19.YlH0_nRo3fLQge2gP0CVk4sy6dvIQjCQDXW20L-G8LU)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/mn4axqpp7wr2pjytsdm0](https://ybug.io/dashboard/reports/detail/mn4axqpp7wr2pjytsdm0)

**Comment by soulBit** [comment]
Sent user follow-up email with information on RSK tokenbridge
