### ISSUE TITLE
[YBUG.IO] I have USDT in my liquality...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#916]
I have USDT in my liquality wallet and I am trying to lend.  my deposit is rejected... thoughts

*Source url:* https://live.sovryn.app/lend
*Reported by:* psawras@gmail.com
*Reported at:* 26 Apr at 17:16 UTC

*Location:* US, California, Costa Mesa
*Browser:* Chrome 87.0.4280.88

*OS:* macOS 10.10.4
*Screen:* 1440x900
*Viewport:* 1440x820

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/angv163fxnw290m31r0r/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk0NTc0MjYsImRhdGEiOnsicmVwb3J0IjoiYW5ndjE2M2Z4bncyOTBtMzFyMHIiLCJ1c2VyIjoiR2l0SHViIn19.OCAo3fVP-8NL2p4ukNNba8lV1zDhW5h7wP8qTHvjIyM)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/angv163fxnw290m31r0r](https://ybug.io/dashboard/reports/detail/angv163fxnw290m31r0r)

**Comment by soulBit** [comment]
Sent user follow-up email with instructions to use RSK tokenbridge
