### ISSUE TITLE
[YBUG.IO] Transaction details and status 1...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#920]
Transaction details and status 1/2 pending for my .01589168 BTC appeared instantly and showed up in top up history instantly.
  \#1. Transaction appeared instantly from my testnet wallet. https://live.blockcypher.com/btc-testnet/tx/a89fa304a12853434955620f4602dec03242ddcddc652021c48577c2d95ab0bc/\

*Source url:* https://test.sovryn.app/wallet
*Reported by:* codycrypto@protonmail.com
*Reported at:* 27 Apr at 09:06 UTC

*Location:* US, Hawaii, Honolulu
*Browser:* Chrome 90.0.4430.85

*OS:* macOS 10.15.7
*Screen:* 2560x1440
*Viewport:* 2117x1271

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/sg3jyjryrstmy9n9cqzh/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk1MTQ0MDcsImRhdGEiOnsicmVwb3J0Ijoic2czanlqcnlyc3RteTluOWNxemgiLCJ1c2VyIjoiR2l0SHViIn19._p9kUzOHuJk4SwrjSWudDgE9LyTPRleWvk09IoqOI3Q)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/sg3jyjryrstmy9n9cqzh](https://ybug.io/dashboard/reports/detail/sg3jyjryrstmy9n9cqzh)

**Comment by soulBit** [comment]
Improved transaction status UI is on roadmap for upcoming release
