### ISSUE TITLE
[YBUG.IO] Feedback for Sovryn optimised...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#921]
Feedback for Sovryn optimised FastBTC
  \#1. test.sovryn.app/wallet
(official link provided by Sovryn staff on their social platforms)

System: Windows 10

Browser: Google Chrome (updated and with cache cleaned)

Wallet: Metamask (no other wallets on this browser)

email: ludovicocaluori@gmail.com\
  \#2. Metamask wallet seems engaged, it is well set on the settings provided by this page\
  \#3. The page however remains unasable due to this notification window\

*Source url:* https://test.sovryn.app/wallet
*Reported by:* ludovicocaluori@gmail.com
*Reported at:* 27 Apr at 09:08 UTC

*Location:* IT, Tuscany, Florence
*Browser:* Chrome 90.0.4430.85

*OS:* Windows 10.0
*Screen:* 1366x768
*Viewport:* 1366x657

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/1wkvtjj0vbp3pfa09dfg/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk1MTQ1MjksImRhdGEiOnsicmVwb3J0IjoiMXdrdnRqajB2YnAzcGZhMDlkZmciLCJ1c2VyIjoiR2l0SHViIn19.LiA3ME7qfYBdRJijbvnK9edZMdkvGWuyamLLqvXFeYQ)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/1wkvtjj0vbp3pfa09dfg](https://ybug.io/dashboard/reports/detail/1wkvtjj0vbp3pfa09dfg)

**Comment by t-z-u** [comment]
@soulBit hes on testnet with modals for mainnet
