### ISSUE TITLE
[YBUG.IO] Upon initial BTC transfer, the...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#922]
Upon initial BTC transfer, the BTC Deposit ID and a pop up *Transaction Details* with 1/2 Status pending appeared. After 1st confirmation, the RSK Relay Hash appeared.
  \#1. 1.
Upon initial BTC transfer, the BTC Deposit ID and a pop up *Transaction Details* with 1/2 Status pending appeared.
2.
Upon one confirmation, the RSK relay hash appeared instantly. \

*Source url:* https://test.sovryn.app/wallet
*Reported by:* codycrypto@protonmail.com
*Reported at:* 27 Apr at 09:12 UTC

*Location:* US, Hawaii, Honolulu
*Browser:* Chrome 90.0.4430.85

*OS:* macOS 10.15.7
*Screen:* 2560x1440
*Viewport:* 1522x1271

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/3nfxx0fzxgz1h9fsr8v5/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk1MTQ3NDYsImRhdGEiOnsicmVwb3J0IjoiM25meHgwZnp4Z3oxaDlmc3I4djUiLCJ1c2VyIjoiR2l0SHViIn19.KXQbGchVCzYrlN38hVBZOiNPtsDg5r4e1KINOZR_ICY)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/3nfxx0fzxgz1h9fsr8v5](https://ybug.io/dashboard/reports/detail/3nfxx0fzxgz1h9fsr8v5)

**Comment by soulBit** [comment]
Improved deposit status UI is in roadmap
