### ISSUE TITLE
[YBUG.IO] I cant select liquality wallet...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#923]
I cant select liquality wallet to transfer!!

*Source url:* https://live.sovryn.app/
*Reported by:* veronica.tanse@gmail.com
*Reported at:* 27 Apr at 09:12 UTC

*Location:* SG, Singapore
*Browser:* Chrome 90.0.4430.85

*OS:* macOS 10.15.7
*Screen:* 1440x900
*Viewport:* 1360x821

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/36j76rj2kn552dj2cwsz/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk1MTQ3NTcsImRhdGEiOnsicmVwb3J0IjoiMzZqNzZyajJrbjU1MmRqMmN3c3oiLCJ1c2VyIjoiR2l0SHViIn19.kXW7mu1BaO4kaAwk1PFPO7wBoqOBHLD4upGJS9EenDI)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/36j76rj2kn552dj2cwsz](https://ybug.io/dashboard/reports/detail/36j76rj2kn552dj2cwsz)

**Comment by soulBit** [comment]
Sent follow-up email to user providing setup instructions for Liquality wallet
