### ISSUE TITLE
[YBUG.IO] The page vis not showing

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#931]
The page vis not showing

*Source url:* https://test.sovryn.app/
*Reported by:* athulkrishnaphysio@gmail.com
*Reported at:* 27 Apr at 15:03 UTC

*Location:* IN, Kerala, Kochi
*Browser:* Chrome 89.0.4389.114

*OS:* Android 11
*Screen:* 360x800
*Viewport:* 360x720

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/mg8rt5kq058rd7bsnngh/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk1MzU4MzgsImRhdGEiOnsicmVwb3J0IjoibWc4cnQ1a3EwNThyZDdic25uZ2giLCJ1c2VyIjoiR2l0SHViIn19.C7ina1vZfn6oKdW0BkR2qkQ4dHemE-c4hC6zT9KhCxE)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/mg8rt5kq058rd7bsnngh](https://ybug.io/dashboard/reports/detail/mg8rt5kq058rd7bsnngh)

**Comment by soulBit** [comment]
Issue should be resolved now
