### ISSUE TITLE
[YBUG.IO] The graphs should go back...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#932]
The graphs should go back farther than a few days!  Thanks
  \#1. The graphs should go back farther than a few days!\

*Source url:* https://live.sovryn.app/trade
*Reported by:* 
*Reported at:* 27 Apr at 15:43 UTC

*Location:* CA, Ontario, Kingston
*Browser:* Firefox 88.0

*OS:* Windows 10.0
*Screen:* 1707x960
*Viewport:* 1279x645

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/fyhc006cms96vf7xxq04/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk1MzgyMzgsImRhdGEiOnsicmVwb3J0IjoiZnloYzAwNmNtczk2dmY3eHhxMDQiLCJ1c2VyIjoiR2l0SHViIn19.293RIUnihGq-WDohi4IQ2rg7gmFy9dqd_i72AJsh8l8)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/fyhc006cms96vf7xxq04](https://ybug.io/dashboard/reports/detail/fyhc006cms96vf7xxq04)

**Comment by soulBit** [comment]
Improved charts will be implemented in an upcoming release
