### ISSUE TITLE
[YBUG.IO] 1. i shouldn't have to engage my...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#934]
1. i shouldn't have to engage my wallet every time i switch tabs in the website (portfolio,stacking etc)
2. a SOV/USDT price should be easily visible on the website

*Source url:* https://live.sovryn.app/wallet
*Reported by:* 
*Reported at:* 27 Apr at 20:32 UTC

*Location:* CY, Nicosia, Nicosia
*Browser:* Chrome 90.0.4430.82

*OS:* Android 11
*Screen:* 412x892
*Viewport:* 412x855

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/4wr367pmm0tpqjkhsjv7/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk1NTU1NTEsImRhdGEiOnsicmVwb3J0IjoiNHdyMzY3cG1tMHRwcWpraHNqdjciLCJ1c2VyIjoiR2l0SHViIn19.LppiCb4vTs-9ynkF_0fUDbwm0kTy4-8UkyXzOsqaEF8)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/4wr367pmm0tpqjkhsjv7](https://ybug.io/dashboard/reports/detail/4wr367pmm0tpqjkhsjv7)

**Comment by soulBit** [comment]
This will be improved in upcoming release
