### ISSUE TITLE
[YBUG.IO] mobile view needs fixing

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#935]
mobile view needs fixing
  \#1. mobile view needs fixing\

*Source url:* https://live.sovryn.app/stats
*Reported by:* 
*Reported at:* 27 Apr at 20:34 UTC

*Location:* CY, Nicosia, Nicosia
*Browser:* Chrome 90.0.4430.82

*OS:* Android 11
*Screen:* 412x892
*Viewport:* 412x799

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/wpwng919df3bqffn3w6j/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk1NTU2NzcsImRhdGEiOnsicmVwb3J0Ijoid3B3bmc5MTlkZjNicWZmbjN3NmoiLCJ1c2VyIjoiR2l0SHViIn19.AEMHMaY2baQXLTak5FVb2MGpQ7sD6niqdoEbXOax5Jw)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/wpwng919df3bqffn3w6j](https://ybug.io/dashboard/reports/detail/wpwng919df3bqffn3w6j)

**Comment by soulBit** [comment]
@t-z-u please add to backlog or close ticket if already in development

**Comment by tiltom** [comment]
I don't want to sound pessimistic but on 412px width our whole app would need one big fix :D Also, we have a banner that says we don't support mobile browsers.
