### ISSUE TITLE
[YBUG.IO] Lagging

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#941]
Lagging

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* 
*Reported at:* 28 Apr at 11:02 UTC

*Location:* NL
*Browser:* Chrome 90.0.4430.82

*OS:* Android 11
*Screen:* 360x800
*Viewport:* 360x776

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/dx5xj4c2647skz86fhh2/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk2MDc3ODEsImRhdGEiOnsicmVwb3J0IjoiZHg1eGo0YzI2NDdza3o4NmZoaDIiLCJ1c2VyIjoiR2l0SHViIn19.bEdfT_DDxqt5-oluBiJmwGKtuE-_rEwQqvYUzqH1RxE)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/dx5xj4c2647skz86fhh2](https://ybug.io/dashboard/reports/detail/dx5xj4c2647skz86fhh2)

**Comment by soulBit** [comment]
Issue should now be resolved
