### ISSUE TITLE
[YBUG.IO] It messes up my phone by over...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#942]
It messes up my phone by over taking other apps all on it's own

*Source url:* https://live.sovryn.app/
*Reported by:* 
*Reported at:* 28 Apr at 11:10 UTC

*Location:* IN, Goa, Mormugao
*Browser:* Chrome 90.0.4430.66

*OS:* Android 8.1.0
*Screen:* 360x760
*Viewport:* 360x690

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/p7528aghdtt2a8a6mcwg/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk2MDgyMzMsImRhdGEiOnsicmVwb3J0IjoicDc1MjhhZ2hkdHQyYThhNm1jd2ciLCJ1c2VyIjoiR2l0SHViIn19.Mm3bBRGn_BRD5b7cOqXn5nJy-37yTzC7jV9922DFsz4)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/p7528aghdtt2a8a6mcwg](https://ybug.io/dashboard/reports/detail/p7528aghdtt2a8a6mcwg)

**Comment by soulBit** [comment]
Issue should be resolved now
