### ISSUE TITLE
[YBUG.IO] sovryn wont load today on google...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#943]
sovryn wont load today on google chrome installed on a macbook

*Source url:* https://live.sovryn.app/
*Reported by:* paulwivz64@me.com
*Reported at:* 28 Apr at 11:20 UTC

*Location:* GB, England, Bolton
*Browser:* Chrome 90.0.4430.93

*OS:* macOS 10.15.7
*Screen:* 1280x800
*Viewport:* 1200x620

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/ah0cacr35z9wa0mnktth/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk2MDg4MTksImRhdGEiOnsicmVwb3J0IjoiYWgwY2FjcjM1ejl3YTBtbmt0dGgiLCJ1c2VyIjoiR2l0SHViIn19.b1o__Q0XkFUogruDfB7SM-XQHWGfAUe0cCq9pS7nx_U)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/ah0cacr35z9wa0mnktth](https://ybug.io/dashboard/reports/detail/ah0cacr35z9wa0mnktth)

**Comment by soulBit** [comment]
Issue should now be resolved
