### ISSUE TITLE
[YBUG.IO] Hey, When I try and buy SOV it...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#944]
Hey, When I try and buy SOV it flashes up with a user blocked sign and will not allow me to move forward with the transaction. Any help is greatly appreciated!

*Source url:* https://live.sovryn.app/
*Reported by:* littlesamoles.e@gmail.com
*Reported at:* 28 Apr at 11:24 UTC

*Location:* GB
*Browser:* Chrome 90.0.4430.85

*OS:* macOS 10.13.6
*Screen:* 1440x900
*Viewport:* 1420x687

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/hkysyaw9h8q61wmsdr1y/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk2MDkwNjYsImRhdGEiOnsicmVwb3J0IjoiaGt5c3lhdzloOHE2MXdtc2RyMXkiLCJ1c2VyIjoiR2l0SHViIn19.-4gVh-tr3izbdX5HFyRR5kGPwz6IG60exEUtodWEIzU)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/hkysyaw9h8q61wmsdr1y](https://ybug.io/dashboard/reports/detail/hkysyaw9h8q61wmsdr1y)

**Comment by soulBit** [comment]
Provided user instructions on solution to this issue
