### ISSUE TITLE
[YBUG.IO] sovryn does not load with...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#945]
sovryn does not load with updated Brave browser

*Source url:* https://live.sovryn.app/
*Reported by:* 
*Reported at:* 28 Apr at 11:46 UTC

*Location:* DE, Free and Hanseatic City of Hamburg, Hamburg
*Browser:* Chrome 90.0.4430.85

*OS:* macOS 10.11.6
*Screen:* 1440x900
*Viewport:* 1374x706

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/fgczxzm9zj266dagsh8x/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk2MTAzOTEsImRhdGEiOnsicmVwb3J0IjoiZmdjenh6bTl6ajI2NmRhZ3NoOHgiLCJ1c2VyIjoiR2l0SHViIn19.GYPo_1awCwyOKZM8lWEgXVHZ5vb_E8yCEVE-ehV-wjU)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/fgczxzm9zj266dagsh8x](https://ybug.io/dashboard/reports/detail/fgczxzm9zj266dagsh8x)

**Comment by jjmr007** [comment]
no bug
