### ISSUE TITLE
[YBUG.IO] Been loading for at least an hour.

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#948]
Been loading for at least an hour. 
Signed into MM or not, no effect.
Updated chrome, refreshed, no joy.

*Source url:* https://live.sovryn.app/
*Reported by:* nzt-56@protonmail.com
*Reported at:* 28 Apr at 13:00 UTC

*Location:* US, New York, Potsdam
*Browser:* Chrome 90.0.4430.93

*OS:* Windows 10.0
*Screen:* 2560x1440
*Viewport:* 2560x1329

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/xc7ayvqwrqwft7n2mfqr/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk2MTQ4NjEsImRhdGEiOnsicmVwb3J0IjoieGM3YXl2cXdycXdmdDduMm1mcXIiLCJ1c2VyIjoiR2l0SHViIn19.HgT7x33g4STuENnz4P3D09rQ6pmjvQe1r2eYLiwznr0)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/xc7ayvqwrqwft7n2mfqr](https://ybug.io/dashboard/reports/detail/xc7ayvqwrqwft7n2mfqr)

**Comment by jjmr007** [comment]
No bug here
