### ISSUE TITLE
[YBUG.IO] It's not giving me the option to...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#950]
It's not giving me the option to connect my NIfty wallet anymore

*Source url:* https://live.sovryn.app/
*Reported by:* reubenspriggs43@gmail.com
*Reported at:* 28 Apr at 15:57 UTC

*Location:* NL, North Holland, Halfweg
*Browser:* Chrome 90.0.4430.85

*OS:* Windows 10.0
*Screen:* 1600x900
*Viewport:* 1455x625

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/2zsvfb8w2mmf0qpywg4j/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk2MjU0NTcsImRhdGEiOnsicmVwb3J0IjoiMnpzdmZiOHcybW1mMHFweXdnNGoiLCJ1c2VyIjoiR2l0SHViIn19.N3UvEf5rktRB4E2NMGUBx3rn4WRjNgxOxb6vDDasSA4)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/2zsvfb8w2mmf0qpywg4j](https://ybug.io/dashboard/reports/detail/2zsvfb8w2mmf0qpywg4j)

**Comment by jjmr007** [comment]
User must de-activate the other wallet extensions in order to give nifty the priority in the UI

Not a improvement suggestion.
Not a bug
