### ISSUE TITLE
[YBUG.IO] hi

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#952]
hi
i have been buying SOV on Sovryn. So far i have bought 122.4 sov @an average 49.5 USD. Is there a way to keep up on token price. when i check CoinGecko it list the price as 0.0065 USD.  ythis cant be correct. what am i missing?
thanks.

*Source url:* https://live.sovryn.app/
*Reported by:* robertagoralski@gmail.com
*Reported at:* 28 Apr at 18:22 UTC

*Location:* LV
*Browser:* Chrome 90.0.4430.85

*OS:* macOS 10.15.7
*Screen:* 1920x1080
*Viewport:* 1789x930

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/7ajcw5zcm6tyj3yfs1kj/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk2MzQxNTQsImRhdGEiOnsicmVwb3J0IjoiN2FqY3c1emNtNnR5ajN5ZnMxa2oiLCJ1c2VyIjoiR2l0SHViIn19.AppiqY5dD5SPnLyYLNxHdxQDRjra0k4yPP_IVc9p65U)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/7ajcw5zcm6tyj3yfs1kj](https://ybug.io/dashboard/reports/detail/7ajcw5zcm6tyj3yfs1kj)

**Comment by jjmr007** [comment]
Not a suggestion improvement, not a bug. Just a #User-feedback question
