### ISSUE TITLE
[YBUG.IO] my deposited amount is not showing

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#953]
my deposited amount is not showing

*Source url:* https://live.sovryn.app/
*Reported by:* jayaprakashahalebeedu.jp@gmail.com
*Reported at:* 28 Apr at 18:40 UTC

*Location:* IN, Karnataka, Bengaluru
*Browser:* Chrome 84.0.4147.105

*OS:* Windows 8.1
*Screen:* 1366x768
*Viewport:* 1366x657

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/nzd0tatcp24q1vwzxavj/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk2MzUyMjksImRhdGEiOnsicmVwb3J0IjoibnpkMHRhdGNwMjRxMXZ3enhhdmoiLCJ1c2VyIjoiR2l0SHViIn19._9xUGAfVoauG_xEM8kWoD_e1vZRNmDuXBxifMyjBjwM)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/nzd0tatcp24q1vwzxavj](https://ybug.io/dashboard/reports/detail/nzd0tatcp24q1vwzxavj)

**Comment by jjmr007** [comment]
duplicated
