### ISSUE TITLE
[YBUG.IO] Impossible to open the app on a...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#957]
Impossible to open the app on a VIVO Y95 Android octacore 4gb ram

*Source url:* https://live.sovryn.app/
*Reported by:* jonahtrader@gmail.com
*Reported at:* 29 Apr at 02:32 UTC

*Location:* IN, Goa, Mormugao
*Browser:* Chrome 90.0.4430.66

*OS:* Android 8.1.0
*Screen:* 360x760
*Viewport:* 360x690

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/4dxxkcxzs0s49j0xv6ss/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk2NjM1NDgsImRhdGEiOnsicmVwb3J0IjoiNGR4eGtjeHpzMHM0OWoweHY2c3MiLCJ1c2VyIjoiR2l0SHViIn19.heKA5hEeapTAH2rsIcjRAuPTipjfjq0A-7HWULDE5Rs)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/4dxxkcxzs0s49j0xv6ss](https://ybug.io/dashboard/reports/detail/4dxxkcxzs0s49j0xv6ss)

**Comment by soulBit** [comment]
Issue should be resolved now
