### ISSUE TITLE
Show pending transaction as the item in the order/history tables

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#959]
- [x] margin trading open positions table
- [x] swap history table

When user confirms transaction, pending transaction must appear in the table related by action (margin trade -> open positions table, swap -> swap history table).

- [x] Pending transactions must be always first on the list
- [x] Only show transactions with state pending or failed, completed transactions will be shown directly from the blockchain
- [x] Do not show failed transaction if user canceled transaction (meaning only transactions with txHash must be shown)

You can get list of user sent transactions using this selector:

https://github.com/DistributedCollective/Sovryn-frontend/blob/8fcef1e15f1423da977798be608e19d1e605eb69/src/store/global/transactions-store/selectors.ts#L24-L26

Transaction types are visible here:

https://github.com/DistributedCollective/Sovryn-frontend/blob/8fcef1e15f1423da977798be608e19d1e605eb69/src/store/global/transactions-store/types.ts#L14-L33

**Comment by peymannaderi3** [comment]
close #1008
