### ISSUE TITLE
[YBUG.IO] Error: insufficient funds to pay...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#962]
Error: insufficient funds to pay for pending and new transaction -- I'm getting that message whenever I click buy Buy SOV button on my Wallet confirmation Box and it also says that The User aborted the denied transaction.... why not enough fund for PENDING and New Transaction, while I'm just obtaining SOV?

*Source url:* https://live.sovryn.app/trade
*Reported by:* rjthermo@yahoo.com
*Reported at:* 29 Apr at 11:29 UTC

*Location:* SA, Eastern Province, Dammam
*Browser:* Chrome 90.0.4430.85

*OS:* Windows 7
*Screen:* 1366x768
*Viewport:* 1366x629

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/8vrpfgjd37xphj44cykr/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk2OTU3NTYsImRhdGEiOnsicmVwb3J0IjoiOHZycGZnamQzN3hwaGo0NGN5a3IiLCJ1c2VyIjoiR2l0SHViIn19.BMAQpK_vaY8d2WPH9rcK-9Q8U_0cxpXYdVdA5yFBgP0)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/8vrpfgjd37xphj44cykr](https://ybug.io/dashboard/reports/detail/8vrpfgjd37xphj44cykr)

**Comment by soulBit** [comment]
Sent user follow-up email with instructions on how to workaround this issue

**Comment by R5fan** [comment]
Could you perhaps post that email here? given that Im having the same problem.

**Comment by soulBit** [comment]
@R5fan the issue is specific to Liquality wallet, suggested workaround is lowering gas fee to "slow" and ensuring that you aren't using your full balance of rBTC, as Liquality currently has some issues with estimating/accounting for fees. If you're still experiencing issues after following these steps, I recommend contacting Liquality support or reaching out to our new support helpdesk here:

https://sovryn.freshdesk.com/support/home

**Comment by R5fan** [comment]
Im not using liquality though, Im using a ledger nano x hardware wallet. Ill open a support ticket, thx.

**Comment by creed-victor** [comment]
> Im not using liquality though, Im using a ledger nano x hardware wallet. Ill open a support ticket, thx.

@R5fan make sure you enabled "Contract data" access in your ledger RSK app settings
