### ISSUE TITLE
[YBUG.IO] I converted RBTC to SOV coins. I...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#971]
I converted RBTC to SOV coins. I currently have 195 SOV and $0RBTC. When I try to stake my 195 SOV (or any amount) and I am ready to confirm the transaction, the Liquidity wallet pops up but shows a transaction of $0 RBTC to approve. Of course it says insufficient funds because the executable is not recognizing the  SOV coins to stake. This is a bug that needs to be fixed. I can provide a screen shot or loom video to show the issue

*Source url:* https://live.sovryn.app/
*Reported by:* Luiseddie@gmail.com
*Reported at:* 30 Apr at 03:22 UTC

*Location:* US
*Browser:* Chrome 90.0.4430.93

*OS:* macOS 10.15.7
*Screen:* 1280x800
*Viewport:* 1238x594

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/pfyxr34pc1p3fa9bpq6k/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk3NTI5NzgsImRhdGEiOnsicmVwb3J0IjoicGZ5eHIzNHBjMXAzZmE5YnBxNmsiLCJ1c2VyIjoiR2l0SHViIn19.g8WJ890Vyv1gW5_pmGplngo274n3rYp55TUcYS0zXtI)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/pfyxr34pc1p3fa9bpq6k](https://ybug.io/dashboard/reports/detail/pfyxr34pc1p3fa9bpq6k)

**Comment by soulBit** [comment]
Provided user information on rBTC being required for gas fees
