### ISSUE TITLE
[YBUG.IO] Not working on Android and even...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#972]
Not working on Android and even bugs my phone entirely

*Source url:* https://live.sovryn.app/
*Reported by:* jonahtrader@gmail.com
*Reported at:* 30 Apr at 03:50 UTC

*Location:* IN, Goa, Ponda
*Browser:* Chrome 90.0.4430.66

*OS:* Android 8.1.0
*Screen:* 360x760
*Viewport:* 360x690

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/3cp38tjgrjcxyp1casss/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk3NTQ2NjAsImRhdGEiOnsicmVwb3J0IjoiM2NwMzh0amdyamN4eXAxY2Fzc3MiLCJ1c2VyIjoiR2l0SHViIn19.sxY3c73QG8d6wtC39-Up35luqS1R0sUd2yr_0ApxKhI)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/3cp38tjgrjcxyp1casss](https://ybug.io/dashboard/reports/detail/3cp38tjgrjcxyp1casss)

**Comment by soulBit** [comment]
Issue should be resolved now
