### ISSUE TITLE
[YBUG.IO] Been showing "Sovryn is loading"...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#973]
Been showing "Sovryn is loading" for over 20 minutes. tried multiple apps

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* simeon.udoh45@gmail.com
*Reported at:* 30 Apr at 08:08 UTC

*Location:* NG, Lagos, Lagos
*Browser:* Chrome 88.0.4324.182

*OS:* Linux unknown
*Screen:* 1366x768
*Viewport:* 1366x637

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/t945195zgcsrkp1qzy8d/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk3NzAxNDYsImRhdGEiOnsicmVwb3J0IjoidDk0NTE5NXpnY3Nya3AxcXp5OGQiLCJ1c2VyIjoiR2l0SHViIn19.Rkb7MX9PQj4_Qll0JTfM18bV8OmTr4_Rqs5324KBSAw)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/t945195zgcsrkp1qzy8d](https://ybug.io/dashboard/reports/detail/t945195zgcsrkp1qzy8d)

**Comment by soulBit** [comment]
Issue should be resolved now
