### ISSUE TITLE
[YBUG.IO] I cant see anything, why is it...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#974]
I cant see anything, why is it so bugged?

*Source url:* https://live.sovryn.app/trade
*Reported by:* kevinabt@live.de
*Reported at:* 30 Apr at 08:47 UTC

*Location:* DE, Baden-Württemberg, Konstanz
*Browser:* Chrome 90.0.4430.93

*OS:* Windows 10.0
*Screen:* 1280x720
*Viewport:* 1280x578

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/zszhpg93jqcdxz9ztg2g/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk3NzI0NTIsImRhdGEiOnsicmVwb3J0IjoienN6aHBnOTNqcWNkeHo5enRnMmciLCJ1c2VyIjoiR2l0SHViIn19.xUiPvWqXoamRt9ayHlvxyeUwRiKmY_BFklLvsoJvBPU)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/zszhpg93jqcdxz9ztg2g](https://ybug.io/dashboard/reports/detail/zszhpg93jqcdxz9ztg2g)

**Comment by soulBit** [comment]
Issue should be resolved now
