### ISSUE TITLE
[YBUG.IO] doesnt load

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#975]
doesnt load

*Source url:* https://live.sovryn.app/
*Reported by:* 
*Reported at:* 30 Apr at 08:59 UTC

*Location:* AU, Queensland, Brighton
*Browser:* Chrome 89.0.4389.128

*OS:* Windows 10.0
*Screen:* 1920x1080
*Viewport:* 1920x937

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/1pzn4j28ymh7g5m6snna/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk3NzMxNTMsImRhdGEiOnsicmVwb3J0IjoiMXB6bjRqMjh5bWg3ZzVtNnNubmEiLCJ1c2VyIjoiR2l0SHViIn19.3dMtXpiLh1aCIMdg5rvMEu3nG5BKt0f__z9WodXxjo4)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/1pzn4j28ymh7g5m6snna](https://ybug.io/dashboard/reports/detail/1pzn4j28ymh7g5m6snna)

**Comment by soulBit** [comment]
Issue should be resolved now
