### ISSUE TITLE
[YBUG.IO] Greetings!

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#976]
Greetings!
I just clicked on the info that appeared to update the app and install it and now I only get the message: Sovryn is loading ... and can't connect to Metamask, can't stake, trade, ...
I am using Chrome v.90.
Please can you help me resolve this problem so that I can continue to stake and trade.

*Source url:* https://live.sovryn.app/
*Reported by:* bedexx@gmail.com
*Reported at:* 30 Apr at 10:20 UTC

*Location:* HR, City of Zagreb, Sesvete
*Browser:* Chrome 90.0.4430.93

*OS:* Windows 10.0
*Screen:* 1920x1080
*Viewport:* 1920x947

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/jrsyqhsg8mrtyc7b3q0q/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk3NzgwMTIsImRhdGEiOnsicmVwb3J0IjoianJzeXFoc2c4bXJ0eWM3YjNxMHEiLCJ1c2VyIjoiR2l0SHViIn19.0lFkUSe4lzlbvsFmw3GmhF11WgKGpYmxrROIUmpy5bk)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/jrsyqhsg8mrtyc7b3q0q](https://ybug.io/dashboard/reports/detail/jrsyqhsg8mrtyc7b3q0q)

**Comment by soulBit** [comment]
Issue should be resolved now
