### ISSUE TITLE
[YBUG.IO] Hi There

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#977]
Hi There

I'm trying to connect my wallet on sovryn on my google chrome browser, but it just stays on loading page....please help...looks like a great project!!!

*Source url:* https://live.sovryn.app/
*Reported by:* mattbick1@gmail.com
*Reported at:* 30 Apr at 10:29 UTC

*Location:* GB
*Browser:* Chrome 90.0.4430.93

*OS:* macOS 10.15.7
*Screen:* 1792x1120
*Viewport:* 1289x768

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/q0h7ry38542awa98chv5/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk3Nzg1OTcsImRhdGEiOnsicmVwb3J0IjoicTBoN3J5Mzg1NDJhd2E5OGNodjUiLCJ1c2VyIjoiR2l0SHViIn19.4XfXCzvAnp-AIZ87GL9zU3z1lmtjC3K41ggobSA7MJA)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/q0h7ry38542awa98chv5](https://ybug.io/dashboard/reports/detail/q0h7ry38542awa98chv5)

**Comment by soulBit** [comment]
Issue should be resolved now
