### ISSUE TITLE
[YBUG.IO] There's no metamask wallet...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#980]
There's no metamask wallet option to connect. Before it was. Any advice how to fix it?

*Source url:* https://live.sovryn.app/
*Reported by:* jacekholdynski@gmail.com
*Reported at:* 30 Apr at 13:51 UTC

*Location:* PL, Mazovia, Warsaw
*Browser:* Chrome 77.0.3865.92

*OS:* Android 10
*Screen:* 393x873
*Viewport:* 393x677

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/b5wqcxmhjpjbqf455h16/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk3OTA2ODQsImRhdGEiOnsicmVwb3J0IjoiYjV3cWN4bWhqcGpicWY0NTVoMTYiLCJ1c2VyIjoiR2l0SHViIn19.WuCsQutg-vWyNBX5pL5cyN98fCQw3D5kLKyijCzConU)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/b5wqcxmhjpjbqf455h16](https://ybug.io/dashboard/reports/detail/b5wqcxmhjpjbqf455h16)

**Comment by soulBit** [comment]
Mobile Metamask is currently disabled due to high gas fees. Sent user follow-up email with instructions on how to workaround this issue
