### ISSUE TITLE
[YBUG.IO] Why I have been getting errors...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#982]
Why I have been getting errors whenever I Swap my RBTC with SOV from my Liqulity Wallet. I have been trying for almost one week now.

*Source url:* https://live.sovryn.app/trade
*Reported by:* rjthermo@yahoo.com
*Reported at:* 30 Apr at 19:47 UTC

*Location:* SA, Eastern Province, Dammam
*Browser:* Chrome 90.0.4430.85

*OS:* Windows 7
*Screen:* 1366x768
*Viewport:* 1366x629

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/zgctw6rq59ffcnw0rw78/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk4MTIwNTAsImRhdGEiOnsicmVwb3J0IjoiemdjdHc2cnE1OWZmY253MHJ3NzgiLCJ1c2VyIjoiR2l0SHViIn19.INQfdWQh1uHwPANTZzTWsMjOVSWMPD0ALq3LrgCFeJA)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/zgctw6rq59ffcnw0rw78](https://ybug.io/dashboard/reports/detail/zgctw6rq59ffcnw0rw78)

**Comment by soulBit** [comment]
Provided user potential solutions to Liquality wallet issues
