### ISSUE TITLE
[YBUG.IO] Why I keep getting this whenever...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#983]
Why I keep getting this whenever I click confirm from my Liquality Wallet to Swap my RBTC with SOV? I have been truying for almost a week now. Please help I really want to avail your promo.

*Source url:* https://live.sovryn.app/trade
*Reported by:* rjthermo@yahoo.com
*Reported at:* 30 Apr at 19:51 UTC

*Location:* SA, Eastern Province, Dammam
*Browser:* Chrome 90.0.4430.85

*OS:* Windows 7
*Screen:* 1366x768
*Viewport:* 1366x629

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/1h260srk2jbz9bx27brr/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk4MTIyNzEsImRhdGEiOnsicmVwb3J0IjoiMWgyNjBzcmsyamJ6OWJ4MjdicnIiLCJ1c2VyIjoiR2l0SHViIn19.-UOWxAY01HYCWoD45LAIWPrn3-lUyQHLD1NYWAOjSLI)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/1h260srk2jbz9bx27brr](https://ybug.io/dashboard/reports/detail/1h260srk2jbz9bx27brr)

**Comment by soulBit** [comment]
Provided user potential solutions to Liquality wallet issues
