### ISSUE TITLE
[YBUG.IO] Why my transaction is being...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#984]
Why my transaction is being DENIED? kindly ckeck it out what has gone wrong with my account.

With kind regards,
Rj Thermo

*Source url:* https://live.sovryn.app/trade
*Reported by:* rjthermo@yahoo.com
*Reported at:* 30 Apr at 20:18 UTC

*Location:* SA, Eastern Province, Dammam
*Browser:* Chrome 90.0.4430.85

*OS:* Windows 7
*Screen:* 1366x768
*Viewport:* 1366x629

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/z51wqds94m8jtg1x7cdw/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk4MTM5MzUsImRhdGEiOnsicmVwb3J0IjoiejUxd3Fkczk0bThqdGcxeDdjZHciLCJ1c2VyIjoiR2l0SHViIn19.10KPQGhu9wDNWzuSsqGSHJ-u0eg0pyt-dzEdbUlEV0c)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/z51wqds94m8jtg1x7cdw](https://ybug.io/dashboard/reports/detail/z51wqds94m8jtg1x7cdw)

**Comment by soulBit** [comment]
Closing as per #962
