### ISSUE TITLE
[YBUG.IO] I used my nifty wallet to...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#987]
I used my nifty wallet to connect to Sovryn...Now I can't connect using that wallet?!!  That portfolio is gone now?!!  WTF?

*Source url:* https://live.sovryn.app/
*Reported by:* ryanjosephhood@gmail.com
*Reported at:* 30 Apr at 23:33 UTC

*Location:* US, New York, Montgomery
*Browser:* Chrome 90.0.4430.72

*OS:* macOS 10.15.3
*Screen:* 1440x900
*Viewport:* 1242x718

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/7t66ybn9147bvb7gzw67/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk4MjU2NDIsImRhdGEiOnsicmVwb3J0IjoiN3Q2NnlibjkxNDdidmI3Z3p3NjciLCJ1c2VyIjoiR2l0SHViIn19.0oHajBtJCQzliYsfk2XO_lx17GtwwjWhPuYkXe6nwkU)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/7t66ybn9147bvb7gzw67](https://ybug.io/dashboard/reports/detail/7t66ybn9147bvb7gzw67)

**Comment by soulBit** [comment]
Sent follow-up message to user with potential solutions
