### ISSUE TITLE
[YBUG.IO] Dear Admin,

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#988]
Dear Admin,

Why I;m getting this message "Error: insufficient funds to pay for pending and new transaction" after I Click "Confirm" on my Liquality Wallet along with the send along Screen Shot Status while I did not abort my purchase or Swapping from RBTC to SOV.

Kindly please anyone out there help and answer me?This is my fourth message and I really want to participate on the SOV promo and its been almost a week now I'm in this hustle. I got my RBTC inside so please validate my trade.

I will greatly appreciate your immediate validation of this transaction.

Thanks and best regards,
Rj Thermo

*Source url:* https://live.sovryn.app/
*Reported by:* rjthermo@yahoo.com
*Reported at:* 01 May at 02:22 UTC

*Location:* SA, Eastern Province, Dammam
*Browser:* Chrome 90.0.4430.85

*OS:* Windows 7
*Screen:* 1366x768
*Viewport:* 1366x629

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/3t06p5b5337ctmh00084/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk4MzU3NzUsImRhdGEiOnsicmVwb3J0IjoiM3QwNnA1YjUzMzdjdG1oMDAwODQiLCJ1c2VyIjoiR2l0SHViIn19.jAvwaMPnM1ogYZe6Lz3LSL6biJfVt7FreH1dGZA803U)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/3t06p5b5337ctmh00084](https://ybug.io/dashboard/reports/detail/3t06p5b5337ctmh00084)

**Comment by soulBit** [comment]
User has reported this issue is resolved after using workaround
