### ISSUE TITLE
[YBUG.IO] Admin,

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#989]
Admin,

I tried also to Stake my fund but yet again the Screenshot shows another error. Why my transaction is being DENIED?

Please expedite the necessary remedy for this ordeal.

Hoping your urgent action with my account situation.

With Kind Regards
Rj

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* rjthermo@yahoo.com
*Reported at:* 01 May at 02:41 UTC

*Location:* SA, Eastern Province, Dammam
*Browser:* Chrome 90.0.4430.85

*OS:* Windows 7
*Screen:* 1366x768
*Viewport:* 1366x629

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/927yxvrtxvkk30xy1m3r/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk4MzY5MDUsImRhdGEiOnsicmVwb3J0IjoiOTI3eXh2cnR4dmtrMzB4eTFtM3IiLCJ1c2VyIjoiR2l0SHViIn19.0w5_iRuS7TedtUkBolUu9XQwVneMdAU-RPQjg6K6Hs4)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/927yxvrtxvkk30xy1m3r](https://ybug.io/dashboard/reports/detail/927yxvrtxvkk30xy1m3r)

**Comment by soulBit** [comment]
Closing as per #962
