### ISSUE TITLE
[YBUG.IO] I think I've connected RSK...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#990]
I think I've connected RSK mainnet (you can see RBTC and SOV funds) but I still get the message above.

I am using Metamask and selected network is  RSK mainnet and 
under "connected sites" I have lve.sovryn.app allowed.

I've also cleared browser cache. I am using updated Brave. 

It's been working until I switched to another wallet just to try it. (Metamask is the only web wallet currently active).

Maybe the message is some kind of not removed "flag" because I previously conected ETH network.

If more information required, I will be glad to colaborate. Eg: wallet configuration image.

Great project!

*Source url:* https://live.sovryn.app/wallet
*Reported by:* vigil.alberto@gmail.com
*Reported at:* 01 May at 08:06 UTC

*Location:* ES, Basque Country, Bilbao
*Browser:* Chrome 90.0.4430.93

*OS:* Windows 10.0
*Screen:* 1366x768
*Viewport:* 1366x629

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/37f99jn98m8rtm8jy539/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk4NTYzODAsImRhdGEiOnsicmVwb3J0IjoiMzdmOTlqbjk4bThydG04ank1MzkiLCJ1c2VyIjoiR2l0SHViIn19.ERvWWncSIL-tzQV4r2X_Cw4vuPtzJ_dNp6N1qMcYngg)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/37f99jn98m8rtm8jy539](https://ybug.io/dashboard/reports/detail/37f99jn98m8rtm8jy539)

**Comment by soulBit** [comment]
Closing as per #991
